---
permalink: audit/accessing-audit-log-file.html 
sidebar: sidebar 
keywords: storagegrid, audit, log, log file, access, accessing 
summary: 'Le partage d"audit contient le fichier audit.log actif et tous les fichiers journaux d"audit compressés.  Vous pouvez accéder aux fichiers journaux d’audit directement à partir de la ligne de commande du nœud d’administration.' 
---
= Accéder au fichier journal d'audit
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le partage d'audit contient les éléments actifs `audit.log` fichier et tous les fichiers journaux d'audit compressés.  Vous pouvez accéder aux fichiers journaux d’audit directement à partir de la ligne de commande du nœud d’administration.

.Avant de commencer
* Tu aslink:../admin/admin-group-permissions.html["autorisations d'accès spécifiques"] .
* Vous devez avoir le `Passwords.txt` déposer.
* Vous devez connaître l’adresse IP d’un nœud d’administration.


.Étapes
. Connectez-vous à un nœud d'administration :
+
.. Entrez la commande suivante : `ssh admin@_primary_Admin_Node_IP_`
.. Entrez le mot de passe indiqué dans le `Passwords.txt` déposer.
.. Entrez la commande suivante pour passer en root : `su -`
.. Entrez le mot de passe indiqué dans le `Passwords.txt` déposer.
+
Lorsque vous êtes connecté en tant que root, l'invite passe de `$` à `#` .



. Accédez au répertoire contenant les fichiers journaux d’audit :
+
`cd /var/local/log`

. Affichez le fichier journal d'audit actuel ou enregistré, selon les besoins.

