---
permalink: audit/cgrr-cross-grid-replication-request.html 
sidebar: sidebar 
keywords: cgrr, cross-grid replication request, audit message, 
summary: Ce message est généré lorsque StorageGRID tente une opération de réplication inter-grille pour répliquer des objets entre des buckets dans une connexion de fédération de grille. 
---
= CGRR : demande de réplication inter-réseau
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ce message est généré lorsque StorageGRID tente une opération de réplication inter-grille pour répliquer des objets entre des buckets dans une connexion de fédération de grille.

[cols="1a,1a,4a"]
|===
| Code | Champ | Description 


 a| 
CSIZ
 a| 
Taille de l'objet
 a| 
La taille de l'objet en octets.

L'attribut CSIZ a été introduit dans StorageGRID 11.8.  Par conséquent, les demandes de réplication inter-grille couvrant une mise à niveau de StorageGRID 11.7 vers 11.8 peuvent avoir une taille d'objet totale inexacte.



 a| 
S3AI
 a| 
ID de compte locataire S3
 a| 
L'ID du compte locataire propriétaire du bucket à partir duquel l'objet est répliqué.



 a| 
GFID
 a| 
ID de connexion à la fédération de grille
 a| 
L'ID de la connexion de fédération de grille utilisée pour la réplication inter-grille.



 a| 
OPÉRER
 a| 
Opération CGR
 a| 
Le type d'opération de réplication inter-grille qui a été tenté :

* 0 = Répliquer l'objet
* 1 = Répliquer l'objet en plusieurs parties
* 2 = Répliquer le marqueur de suppression




 a| 
S3BK
 a| 
Godet S3
 a| 
Le nom du bucket S3.



 a| 
S3KY
 a| 
Touche S3
 a| 
Le nom de la clé S3, sans inclure le nom du bucket.



 a| 
VSID
 a| 
ID de version
 a| 
L'ID de version de la version spécifique d'un objet en cours de réplication.



 a| 
RSLT
 a| 
Code de résultat
 a| 
Renvoie une erreur réussie (SUCS) ou générale (GERR).

|===