---
permalink: audit/gnrg-gnds-registration.html 
sidebar: sidebar 
keywords: storagegrid, audi, message, GNRG, GNDS Registration 
summary: 'Le service CMN génère ce message d"audit lorsqu"un service a mis à jour ou enregistré des informations le concernant dans le système StorageGRID .' 
---
= GNRG : Enregistrement GNDS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le service CMN génère ce message d'audit lorsqu'un service a mis à jour ou enregistré des informations le concernant dans le système StorageGRID .

[cols="1a,1a,4a"]
|===
| Code | Champ | Description 


 a| 
RSLT
 a| 
Résultat
 a| 
Le résultat de la demande de mise à jour :

* SUCS : Réussi
* SUNV : Service indisponible
* GERR : Autre échec




 a| 
GNID
 a| 
Nœud ID
 a| 
L'ID de nœud du service qui a initié la demande de mise à jour.



 a| 
GNTP
 a| 
Type d'appareil
 a| 
Le type de périphérique du nœud de grille (par exemple, BLDR pour un service LDR).



 a| 
GNDV
 a| 
Version du modèle d'appareil
 a| 
La chaîne identifiant la version du modèle de périphérique du nœud de grille dans le bundle DMDL.



 a| 
GNGP
 a| 
Groupe
 a| 
Le groupe auquel appartient le nœud de grille (dans le contexte des coûts de liaison et du classement des requêtes de service).



 a| 
GNIA
 a| 
Adresse IP
 a| 
L'adresse IP du nœud de grille.

|===
Ce message est généré chaque fois qu'un nœud de grille met à jour son entrée dans le bundle de nœuds de grille.
