---
permalink: audit/ilm-audit-messages.html 
sidebar: sidebar 
keywords: audit messages, ILM, IDEL, LKCU, ORLM 
summary: Les messages d’audit appartenant à la catégorie d’audit ILM sont utilisés pour les événements liés aux opérations du cycle de vie des informations. 
---
= Messages d'audit ILM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les messages d'audit appartenant à la catégorie d'audit ILM sont utilisés pour les événements liés aux opérations de gestion du cycle de vie de l'information (ILM).

[cols="1a,3a,1a"]
|===
| Code | Titre et description du message | Voir 


 a| 
IDEL
 a| 
Suppression initiée par ILM : ce message d'audit est généré lorsque ILM démarre le processus de suppression d'un objet.
 a| 
link:idel-ilm-initiated-delete.html["IDEL : suppression initiée par ILM"]



 a| 
LKCU
 a| 
Nettoyage des objets écrasés.  Ce message d'audit est généré lorsqu'un objet écrasé est automatiquement supprimé pour libérer de l'espace de stockage.
 a| 
link:lkcu-overwritten-object-cleanup.html["LKCU : Nettoyage des objets écrasés"]



 a| 
ORLM
 a| 
Règles d'objet respectées : ce message d'audit est généré lorsque les données d'objet sont stockées comme spécifié par les règles ILM.
 a| 
link:orlm-object-rules-met.html["ORLM : Règles d'objet respectées"]

|===