---
permalink: audit/index.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, log, structure, content 
summary: 'Ces instructions contiennent des informations sur la structure et le contenu des messages d"audit et des journaux d"audit StorageGRID .  Vous pouvez utiliser ces informations pour lire et analyser la piste d’audit de l’activité du système.' 
---
= Messages d'audit et journaux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ces instructions contiennent des informations sur la structure et le contenu des messages d'audit et des journaux d'audit StorageGRID .  Vous pouvez utiliser ces informations pour lire et analyser la piste d’audit de l’activité du système.

Ces instructions sont destinées aux administrateurs chargés de produire des rapports d'activité et d'utilisation du système qui nécessitent l'analyse des messages d'audit du système StorageGRID .

Pour utiliser le fichier journal texte, vous devez avoir accès au partage d’audit configuré sur le nœud d’administration.

Pour plus d'informations sur la configuration des niveaux de messages d'audit et l'utilisation d'un serveur syslog externe, consultezlink:../monitor/configure-audit-messages.html["Configurer les messages d'audit et les destinations des journaux"] .
