---
permalink: audit/lkcu-overwritten-object-cleanup.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, LKCU, Overwritten Object Cleanup 
summary: 'Ce message est généré lorsque StorageGRID supprime un objet écrasé qui nécessitait auparavant un nettoyage pour libérer de l"espace de stockage.  Un objet est écrasé lorsqu"un client S3 écrit un objet dans un chemin contenant déjà un objet.  Le processus de suppression se produit automatiquement et en arrière-plan.' 
---
= LKCU : Nettoyage des objets écrasés
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ce message est généré lorsque StorageGRID supprime un objet écrasé qui nécessitait auparavant un nettoyage pour libérer de l'espace de stockage.  Un objet est écrasé lorsqu'un client S3 écrit un objet dans un chemin contenant déjà un objet.  Le processus de suppression se produit automatiquement et en arrière-plan.

[cols="1a,1a,4a"]
|===
| Code | Champ | Description 


 a| 
CSIZ
 a| 
Taille du contenu
 a| 
La taille de l'objet en octets.



 a| 
LTYP
 a| 
Type de nettoyage
 a| 
_Usage interne uniquement._



 a| 
LUID
 a| 
UUID de l'objet supprimé
 a| 
L'identifiant de l'objet qui a été supprimé.



 a| 
CHEMIN
 a| 
Seau/clé S3
 a| 
Le nom du compartiment S3 et le nom de la clé S3.



 a| 
SEGC
 a| 
UUID du conteneur
 a| 
UUID du conteneur pour l'objet segmenté.  Cette valeur n'est disponible que si l'objet est segmenté.



 a| 
UUID
 a| 
Identifiant unique universel
 a| 
L'identifiant de l'objet qui existe encore.  Cette valeur n'est disponible que si l'objet n'a pas été supprimé.

|===