---
permalink: audit/mgau-management-audit-message.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, MGAU, Management audit message 
summary: 'La catégorie Gestion enregistre les demandes des utilisateurs dans l"API de gestion.  Chaque requête qui n"est pas une requête GET ou HEAD à l"API enregistre une réponse avec le nom d"utilisateur, l"IP et le type de requête à l"API.' 
---
= MGAU : Message d'audit de gestion
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La catégorie Gestion enregistre les demandes des utilisateurs dans l'API de gestion.  Chaque requête HTTP qui n'est pas une requête GET ou HEAD vers un URI d'API valide enregistre une réponse contenant le nom d'utilisateur, l'IP et le type de requête vers l'API.  Les URI d'API non valides (tels que /api/v3-authorize) et les demandes non valides adressées à des URI d'API valides ne sont pas enregistrées.

[cols="1a,1a,4a"]
|===
| Code | Champ | Description 


 a| 
MDIP
 a| 
Adresse IP de destination
 a| 
L'adresse IP du serveur (destination).



 a| 
MDNA
 a| 
Nom de domaine
 a| 
Le nom de domaine de l'hôte.



 a| 
MPAT
 a| 
Demande PATH
 a| 
Le chemin de la demande.



 a| 
MPQP
 a| 
Paramètres de requête de demande
 a| 
Les paramètres de requête pour la demande.



 a| 
MRBD
 a| 
Corps de la requête
 a| 
Le contenu du corps de la requête.  Alors que le corps de la réponse est enregistré par défaut, le corps de la demande est enregistré dans certains cas lorsque le corps de la réponse est vide.  Étant donné que les informations suivantes ne sont pas disponibles dans le corps de la réponse, elles sont extraites du corps de la requête pour les méthodes POST suivantes :

* Nom d'utilisateur et identifiant de compte dans *POST authorize*
* Nouvelle configuration des sous-réseaux dans *POST /grid/grid-networks/update*
* Nouveaux serveurs NTP dans *POST /grid/ntp-servers/update*
* ID de serveur mis hors service dans *POST /grid/servers/decommission*


*Remarque :* les informations sensibles sont soit supprimées (par exemple, une clé d’accès S3), soit masquées par des astérisques (par exemple, un mot de passe).



 a| 
MRMD
 a| 
Méthode de requête
 a| 
La méthode de requête HTTP :

* POSTE
* METTRE
* SUPPRIMER
* CORRECTIF




 a| 
MRSC
 a| 
Code de réponse
 a| 
Le code de réponse.



 a| 
MRSP
 a| 
Corps de la réponse
 a| 
Le contenu de la réponse (le corps de la réponse) est enregistré par défaut.

*Remarque :* les informations sensibles sont soit supprimées (par exemple, une clé d’accès S3), soit masquées par des astérisques (par exemple, un mot de passe).



 a| 
MSIP
 a| 
Adresse IP source
 a| 
L'adresse IP du client (source).



 a| 
MUUN
 a| 
URN de l'utilisateur
 a| 
L'URN (nom de ressource uniforme) de l'utilisateur qui a envoyé la demande.



 a| 
RSLT
 a| 
Résultat
 a| 
Renvoie une réussite (SUCS) ou l'erreur signalée par le backend.

|===