---
permalink: audit/object-retrieve-transactions.html 
sidebar: sidebar 
keywords: object retrieve, transactions, SGET, WGET 
summary: 'Vous pouvez identifier les transactions de récupération d"objets dans le journal d"audit en localisant les messages d"audit spécifiques à l"API S3.' 
---
= Transactions de récupération d'objets
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez identifier les transactions de récupération d'objets dans le journal d'audit en localisant les messages d'audit spécifiques à l'API S3.

Tous les messages d’audit générés lors d’une transaction de récupération ne sont pas répertoriés dans les tableaux suivants. Seuls les messages nécessaires au suivi de la transaction de récupération sont inclus.



== Messages d'audit de récupération S3

[cols="1a,1a,2a,1a,1a"]
|===
| Code | Nom | Description | Tracer | Voir 


 a| 
SGET
 a| 
GET S3
 a| 
Demande effectuée pour récupérer un objet d'un bucket.
 a| 
CBID, S3BK, S3KY
 a| 
link:sget-s3-get.html["SGET : S3 OBTENIR"]

|===


== Messages d'audit de récupération rapide

[cols="1a,1a,2a,1a,1a"]
|===
| Code | Nom | Description | Tracer | Voir 


 a| 
WGET
 a| 
Swift GET
 a| 
Demande effectuée pour récupérer un objet d'un conteneur.
 a| 
CBID, WCON, WOBJ
 a| 
link:wget-swift-get.html["WGET : Swift GET"]

|===


== Exemple : récupération d'objet S3

Lorsqu'un client S3 récupère un objet à partir d'un nœud de stockage (service LDR), un message d'audit est généré et enregistré dans le journal d'audit.

Notez que tous les messages d’audit générés lors d’une transaction ne sont pas répertoriés dans l’exemple ci-dessous.  Seuls ceux liés à la transaction de récupération S3 (SGET) sont répertoriés.



=== SGET : S3 OBTENIR

La récupération d’objet commence lorsque le client envoie une demande GetObject à un service LDR.  Le message contient le bucket à partir duquel récupérer l'objet et la clé S3 de l'objet, qui est utilisée pour identifier l'objet.

[listing, subs="specialcharacters,quotes"]
----
2017-09-20T22:53:08.782605 [AUDT:[RSLT(FC32):SUCS][TIME(UI64):47807][SAIP(IPAD):"10.96.112.26"][S3AI(CSTR):"43979298178977966408"][SACC(CSTR):"s3-account-a"][S3AK(CSTR):"SGKHt7GzEcu0yXhFhT_rL5mep4nJt1w75GBh-O_FEw=="][SUSR(CSTR):"urn:sgws:identity::43979298178977966408:root"][SBAI(CSTR):"43979298178977966408"][SBAC(CSTR):"s3-account-a"]\[S3BK\(CSTR\):"bucket-anonymous"\]\[S3KY\(CSTR\):"Hello.txt"\][CBID(UI64):0x83D70C6F1F662B02][CSIZ(UI64):12][AVER(UI32):10][ATIM(UI64):1505947988782605]\[ATYP\(FC32\):SGET\][ANID(UI32):12272050][AMID(FC32):S3RQ][ATID(UI64):17742374343649889669]]
----
Si la politique de compartiment le permet, un client peut récupérer des objets de manière anonyme ou récupérer des objets à partir d'un compartiment appartenant à un autre compte de locataire.  Le message d'audit contient des informations sur le compte locataire du propriétaire du bucket afin que vous puissiez suivre ces demandes anonymes et inter-comptes.

Dans l'exemple de message suivant, le client envoie une requête GetObject pour un objet stocké dans un bucket dont il n'est pas propriétaire.  Les valeurs de SBAI et SBAC enregistrent l'ID et le nom du compte locataire du propriétaire du bucket, qui diffèrent de l'ID et du nom du compte locataire du client enregistrés dans S3AI et SACC.

[listing, subs="specialcharacters,quotes"]
----
2017-09-20T22:53:15.876415 [AUDT:[RSLT(FC32):SUCS][TIME(UI64):53244][SAIP(IPAD):"10.96.112.26"]\[S3AI\(CSTR\):"17915054115450519830"\]\[SACC\(CSTR\):"s3-account-b"\][S3AK(CSTR):"SGKHpoblWlP_kBkqSCbTi754Ls8lBUog67I2LlSiUg=="][SUSR(CSTR):"urn:sgws:identity::17915054115450519830:root"]\[SBAI\(CSTR\):"43979298178977966408"\]\[SBAC\(CSTR\):"s3-account-a"\][S3BK(CSTR):"bucket-anonymous"][S3KY(CSTR):"Hello.txt"][CBID(UI64):0x83D70C6F1F662B02][CSIZ(UI64):12][AVER(UI32):10][ATIM(UI64):1505947995876415][ATYP(FC32):SGET][ANID(UI32):12272050][AMID(FC32):S3RQ][ATID(UI64):6888780247515624902]]
----


== Exemple : S3 Sélectionner sur un objet

Lorsqu'un client S3 émet une requête S3 Select sur un objet, des messages d'audit sont générés et enregistrés dans le journal d'audit.

Notez que tous les messages d’audit générés lors d’une transaction ne sont pas répertoriés dans l’exemple ci-dessous.  Seuls ceux liés à la transaction S3 Select (SelectObjectContent) sont répertoriés.

Chaque requête génère deux messages d'audit : l'un qui exécute l'autorisation de la demande S3 Select (le champ S3SR est défini sur « select ») et une opération GET standard ultérieure qui récupère les données du stockage pendant le traitement.

[listing, subs="specialcharacters,quotes"]
----
2021-11-08T15:35:30.750038 [AUDT:[RSLT(FC32):SUCS][CNID(UI64):1636385730715700][TIME(UI64):29173][SAIP(IPAD):"192.168.7.44"][S3AI(CSTR):"63147909414576125820"][SACC(CSTR):"Tenant1636027116"][S3AK(CSTR):"AUFD1XNVZ905F3TW7KSU"][SUSR(CSTR):"urn:sgws:identity::63147909414576125820:root"][SBAI(CSTR):"63147909414576125820"][SBAC(CSTR):"Tenant1636027116"][S3BK(CSTR):"619c0755-9e38-42e0-a614-05064f74126d"][S3KY(CSTR):"SUB-EST2020_ALL.csv"][CBID(UI64):0x0496F0408A721171][UUID(CSTR):"D64B1A4A-9F01-4EE7-B133-08842A099628"][CSIZ(UI64):0][S3SR(CSTR):"select"][AVER(UI32):10][ATIM(UI64):1636385730750038][ATYP(FC32):SPOS][ANID(UI32):12601166][AMID(FC32):S3RQ][ATID(UI64):1363009709396895985]]
----
[listing, subs="specialcharacters,quotes"]
----
2021-11-08T15:35:32.604886 [AUDT:[RSLT(FC32):SUCS][CNID(UI64):1636383069486504][TIME(UI64):430690][SAIP(IPAD):"192.168.7.44"][HTRH(CSTR):"{\"x-forwarded-for\":\"unix:\"}"][S3AI(CSTR):"63147909414576125820"][SACC(CSTR):"Tenant1636027116"][S3AK(CSTR):"AUFD1XNVZ905F3TW7KSU"][SUSR(CSTR):"urn:sgws:identity::63147909414576125820:root"][SBAI(CSTR):"63147909414576125820"][SBAC(CSTR):"Tenant1636027116"][S3BK(CSTR):"619c0755-9e38-42e0-a614-05064f74126d"][S3KY(CSTR):"SUB-EST2020_ALL.csv"][CBID(UI64):0x0496F0408A721171][UUID(CSTR):"D64B1A4A-9F01-4EE7-B133-08842A099628"][CSIZ(UI64):10185581][MTME(UI64):1636380348695262][AVER(UI32):10][ATIM(UI64):1636385732604886][ATYP(FC32):SGET][ANID(UI32):12733063][AMID(FC32):S3RQ][ATID(UI64):16562288121152341130]]
----