---
permalink: audit/olst-system-detected-lost-object.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, OLST, System Detected Lost Object 
summary: 'Ce message est généré lorsque le service DDS ne parvient pas à localiser de copies d"un objet dans le système StorageGRID .' 
---
= OLST : le système a détecté un objet perdu
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ce message est généré lorsque le service DDS ne parvient pas à localiser de copies d'un objet dans le système StorageGRID .

[cols="1a,1a,4a"]
|===
| Code | Champ | Description 


 a| 
CBID
 a| 
Identifiant du bloc de contenu
 a| 
Le CBID de l'objet perdu.



 a| 
NOID
 a| 
Nœud ID
 a| 
Si disponible, le dernier emplacement direct ou proche connu de l'objet perdu.  Il est possible d'avoir uniquement l'ID de nœud sans ID de volume si les informations de volume ne sont pas disponibles.



 a| 
CHEMIN
 a| 
Seau/clé S3
 a| 
Si disponible, le nom du compartiment S3 et le nom de la clé S3.



 a| 
RSLT
 a| 
Résultat
 a| 
Ce champ a la valeur AUCUN.  RSLT est un champ de message obligatoire, mais n'est pas pertinent pour ce message.  NONE est utilisé plutôt que SUCS afin que ce message ne soit pas filtré.



 a| 
UUID
 a| 
ID unique universel
 a| 
L'identifiant de l'objet perdu dans le système StorageGRID .



 a| 
VOLI
 a| 
ID du volume
 a| 
Si disponible, l'ID de volume du nœud de stockage pour le dernier emplacement connu de l'objet perdu.

|===