---
permalink: audit/orlm-object-rules-met.html 
sidebar: sidebar 
keywords: audit message, ORLM, Object Rules Met, ilm rule 
summary: 'Ce message est généré lorsque l"objet est stocké et copié avec succès comme spécifié par les règles ILM.' 
---
= ORLM : Règles d'objet respectées
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ce message est généré lorsque l'objet est stocké et copié avec succès comme spécifié par les règles ILM.


NOTE: Le message ORLM n'est pas généré lorsqu'un objet est stocké avec succès par la règle par défaut Créer 2 copies si une autre règle de la stratégie utilise le filtre avancé Taille de l'objet.

[cols="1a,1a,4a"]
|===
| Code | Champ | Description 


 a| 
CONSTRUIRE
 a| 
En-tête de godet
 a| 
Champ d'ID du bucket.  Utilisé pour les opérations internes.  Apparaît uniquement si STAT est PRGD.



 a| 
CBID
 a| 
Identifiant du bloc de contenu
 a| 
Le CBID de l'objet.



 a| 
CSIZ
 a| 
Taille du contenu
 a| 
La taille de l'objet en octets.



 a| 
LOC
 a| 
Emplacements
 a| 
L'emplacement de stockage des données d'objet dans le système StorageGRID .  La valeur de LOCS est "" si l'objet n'a aucun emplacement (par exemple, il a été supprimé).

CLEC : pour les objets à codage d'effacement, l'ID de profil de codage d'effacement et l'ID de groupe de codage d'effacement appliqué aux données de l'objet.

CLDI : pour les objets répliqués, l'ID du nœud LDR et l'ID du volume de l'emplacement de l'objet.

CLNL : ID du nœud ARC de l'emplacement de l'objet si les données de l'objet sont archivées.



 a| 
CHEMIN
 a| 
Seau/clé S3
 a| 
Le nom du compartiment S3 et le nom de la clé S3.



 a| 
RSLT
 a| 
Résultat
 a| 
Le résultat de l'opération ILM.

SUCS : L'opération ILM a réussi.



 a| 
RÈGLE
 a| 
Étiquette des règles
 a| 
L'étiquette lisible par l'homme attribuée à la règle ILM appliquée à cet objet.



 a| 
SEGC
 a| 
UUID du conteneur
 a| 
UUID du conteneur pour l'objet segmenté.  Cette valeur n'est disponible que si l'objet est segmenté.



 a| 
SGCB
 a| 
Conteneur CBID
 a| 
CBID du conteneur pour l'objet segmenté.  Cette valeur est disponible uniquement pour les objets segmentés et en plusieurs parties.



 a| 
STAT
 a| 
Statut
 a| 
L'état de fonctionnement de l'ILM.

TERMINÉ : les opérations ILM sur l’objet sont terminées.

DFER : L'objet a été marqué pour une future réévaluation ILM.

PRGD : l'objet a été supprimé du système StorageGRID .

NLOC : les données de l'objet ne peuvent plus être trouvées dans le système StorageGRID .  Ce statut peut indiquer que toutes les copies des données de l'objet sont manquantes ou endommagées.



 a| 
UUID
 a| 
Identifiant unique universel
 a| 
L'identifiant de l'objet dans le système StorageGRID .



 a| 
VSID
 a| 
ID de version
 a| 
L'ID de version d'un nouvel objet créé dans un bucket versionné.  Les opérations sur les buckets et les objets dans les buckets non versionnés n'incluent pas ce champ.

|===
Le message d'audit ORLM peut être émis plusieurs fois pour un même objet.  Par exemple, il est émis chaque fois que l’un des événements suivants se produit :

* Les règles ILM pour l'objet sont satisfaites pour toujours.
* Les règles ILM pour l'objet sont satisfaites pour cette époque.
* Les règles ILM ont supprimé l'objet.
* Le processus de vérification en arrière-plan détecte qu'une copie des données d'objet répliquées est corrompue.  Le système StorageGRID effectue une évaluation ILM pour remplacer l'objet corrompu.


.Informations connexes
* link:object-ingest-transactions.html["Transactions d'ingestion d'objets"]
* link:object-delete-transactions.html["Transactions de suppression d'objets"]

