---
permalink: audit/s3-select-request.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, S3SL, S3 Select request 
summary: 'Ce message indique qu"un utilisateur a lancé une tâche de sélection S3.' 
---
= S3SL : Demande de sélection S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ce message enregistre une fin après qu'une demande S3 Select a été renvoyée au client.  Le message S3SL peut inclure des détails sur le message d'erreur et le code d'erreur.  La demande n’a peut-être pas abouti.

[cols="1a,1a,4a"]
|===
| Code | Champ | Description 


 a| 
BYSC
 a| 
Octets analysés
 a| 
Nombre d'octets analysés (reçus) à partir des nœuds de stockage.

BYSC et BYPR sont susceptibles d'être différents si l'objet est compressé.  Si l'objet est compressé, BYSC aura le nombre d'octets compressés et BYPR sera le nombre d'octets après décompression.



 a| 
BYPR
 a| 
Octets traités
 a| 
Nombre d'octets traités.  Indique combien d'octets de « Octets analysés » ont été réellement traités ou traités par une tâche S3 Select.



 a| 
BYRT
 a| 
Octets renvoyés
 a| 
Nombre d'octets qu'une tâche S3 Select a renvoyé au client.



 a| 
REPR
 a| 
Enregistrements traités
 a| 
Nombre d'enregistrements ou de lignes qu'une tâche S3 Select a reçus des nœuds de stockage.



 a| 
RERT
 a| 
Dossiers retournés
 a| 
Nombre d'enregistrements ou de lignes qu'un travail S3 Select a renvoyé au client.



 a| 
JOFI
 a| 
Travail terminé
 a| 
Indique si le traitement du travail S3 Select est terminé ou non.  Si cela est faux, la tâche n'a pas pu se terminer et les champs d'erreur contiendront probablement des données.  Le client a peut-être reçu des résultats partiels, voire aucun résultat du tout.



 a| 
REID
 a| 
ID de la demande
 a| 
Identifiant de la demande S3 Select.



 a| 
EXTM
 a| 
Temps d'exécution
 a| 
Le temps, en secondes, qu'il a fallu pour terminer la tâche S3 Select.



 a| 
ERMG
 a| 
Message d'erreur
 a| 
Message d'erreur généré par la tâche S3 Select.



 a| 
ERTY
 a| 
Type d'erreur
 a| 
Type d'erreur généré par le travail S3 Select.



 a| 
ERST
 a| 
Trace de pile d'erreurs
 a| 
Erreur Stacktrace générée par le travail S3 Select.



 a| 
S3BK
 a| 
Godet S3
 a| 
Le nom du bucket S3.



 a| 
S3AK
 a| 
ID de clé d'accès S3 (expéditeur de la demande)
 a| 
L'ID de clé d'accès S3 pour l'utilisateur qui a envoyé la demande.



 a| 
S3AI
 a| 
ID de compte locataire S3 (expéditeur de la demande)
 a| 
L'ID du compte locataire de l'utilisateur qui a envoyé la demande.



 a| 
S3KY
 a| 
Touche S3
 a| 
Le nom de la clé S3, sans inclure le nom du bucket.

|===