---
permalink: audit/sget-s3-get.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, SGET, S3 GET 
summary: 'Lorsqu"un client S3 émet une transaction GET, une demande est effectuée pour récupérer un objet ou répertorier les objets dans un bucket.  Ce message est émis par le serveur si la transaction réussit.' 
---
= SGET : S3 OBTENIR
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsqu'un client S3 émet une transaction GET, une demande est effectuée pour récupérer un objet ou répertorier les objets dans un bucket, ou pour supprimer une sous-ressource bucket/objet.  Ce message est émis par le serveur si la transaction réussit.

[cols="1a,1a,4a"]
|===
| Code | Champ | Description 


 a| 
CBID
 a| 
Identifiant du bloc de contenu
 a| 
L'identifiant unique du bloc de contenu demandé.  Si le CBID est inconnu, ce champ est défini sur 0.  Les opérations sur les buckets n'incluent pas ce champ.



 a| 
CNCH
 a| 
En-tête de contrôle de cohérence
 a| 
La valeur de l'en-tête de requête HTTP Consistency-Control, si présent dans la requête.



 a| 
CNID
 a| 
Identifiant de connexion
 a| 
L'identifiant système unique pour la connexion TCP/IP.



 a| 
CSIZ
 a| 
Taille du contenu
 a| 
La taille de l'objet récupéré en octets.  Les opérations sur les buckets n'incluent pas ce champ.



 a| 
HTRH
 a| 
En-tête de requête HTTP
 a| 
Liste des noms et valeurs d'en-tête de requête HTTP enregistrés tels que sélectionnés lors de la configuration.

 `X-Forwarded-For`est automatiquement inclus s'il est présent dans la demande et si le `X-Forwarded-For` la valeur est différente de l'adresse IP de l'expéditeur de la demande (champ d'audit SAIP).



 a| 
LITÉ
 a| 
ListObjectsV2
 a| 
Une réponse au format _v2_ a été demandée.  Pour plus de détails, voir https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html["AWS ListObjectsV2"^] .  Pour les opérations de bucket GET uniquement.



 a| 
NCHD
 a| 
Nombre d'enfants
 a| 
Inclut les clés et les préfixes courants.  Pour les opérations de bucket GET uniquement.



 a| 
RANG
 a| 
Lecture de la portée
 a| 
Pour les opérations de lecture de plage uniquement.  Indique la plage d'octets lus par cette requête.  La valeur après la barre oblique (/) indique la taille de l'objet entier.



 a| 
RSLT
 a| 
Code de résultat
 a| 
Résultat de la transaction GET.  Le résultat est toujours :

SUCS : Réussi



 a| 
S3AI
 a| 
ID de compte locataire S3 (expéditeur de la demande)
 a| 
L'ID du compte locataire de l'utilisateur qui a envoyé la demande.  Une valeur vide indique un accès anonyme.



 a| 
S3AK
 a| 
ID de clé d'accès S3 (expéditeur de la demande)
 a| 
L'ID de clé d'accès S3 haché pour l'utilisateur qui a envoyé la demande.  Une valeur vide indique un accès anonyme.



 a| 
S3BK
 a| 
Godet S3
 a| 
Le nom du bucket S3.



 a| 
S3KY
 a| 
Touche S3
 a| 
Le nom de la clé S3, sans inclure le nom du bucket.  Les opérations sur les buckets n'incluent pas ce champ.



 a| 
S3SR
 a| 
Sous-ressource S3
 a| 
Le compartiment ou la sous-ressource d'objet sur lequel l'opération est effectuée, le cas échéant.



 a| 
SACC
 a| 
Nom du compte locataire S3 (expéditeur de la demande)
 a| 
Le nom du compte locataire de l'utilisateur qui a envoyé la demande.  Vide pour les demandes anonymes.



 a| 
SAIP
 a| 
Adresse IP (expéditeur de la requête)
 a| 
L'adresse IP de l'application cliente qui a effectué la demande.



 a| 
SBAC
 a| 
Nom du compte locataire S3 (propriétaire du bucket)
 a| 
Le nom du compte locataire pour le propriétaire du bucket.  Utilisé pour identifier l'accès inter-comptes ou anonyme.



 a| 
SBAI
 a| 
ID de compte locataire S3 (propriétaire du bucket)
 a| 
L'ID de compte locataire du propriétaire du bucket cible.  Utilisé pour identifier l'accès inter-comptes ou anonyme.



 a| 
SUSR
 a| 
URN utilisateur S3 (expéditeur de la requête)
 a| 
L'ID du compte locataire et le nom d'utilisateur de l'utilisateur effectuant la demande.  L'utilisateur peut être un utilisateur local ou un utilisateur LDAP. Par exemple :  `urn:sgws:identity::03393893651506583485:root`

Vide pour les demandes anonymes.



 a| 
TEMPS
 a| 
Durée
 a| 
Temps total de traitement de la demande en microsecondes.



 a| 
TLIP
 a| 
Adresse IP de l'équilibreur de charge approuvé
 a| 
Si la demande a été acheminée par un équilibreur de charge de couche 7 approuvé, l'adresse IP de l'équilibreur de charge.



 a| 
RTCN
 a| 
Tronqué ou non tronqué
 a| 
Définissez sur faux si tous les résultats ont été renvoyés.  Définissez sur vrai si davantage de résultats sont disponibles à renvoyer.  Pour les opérations de bucket GET uniquement.



 a| 
UUID
 a| 
Identifiant unique universel
 a| 
L'identifiant de l'objet dans le système StorageGRID .



 a| 
VSID
 a| 
ID de version
 a| 
L'ID de version de la version spécifique d'un objet qui a été demandé.  Les opérations sur les buckets et les objets dans les buckets non versionnés n'incluent pas ce champ.

|===