---
permalink: upgrade/checking-systems-condition-before-upgrading-software.html 
sidebar: sidebar 
keywords: upgrade, grid tasks, firewall, ports 
summary: Avant de mettre à niveau un système StorageGRID , vérifiez que le système est prêt à accueillir la mise à niveau.  Assurez-vous que le système fonctionne normalement et que tous les nœuds du réseau sont opérationnels. 
---
= Vérifiez l'état du système
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de mettre à niveau un système StorageGRID , vérifiez que le système est prêt à accueillir la mise à niveau.  Assurez-vous que le système fonctionne normalement et que tous les nœuds du réseau sont opérationnels.

.Étapes
. Sign in au Grid Manager à l'aide d'unlink:../admin/web-browser-requirements.html["navigateur Web pris en charge"] .
. Vérifiez et résolvez toutes les alertes actives.
. Confirmez qu’aucune tâche de grille conflictuelle n’est active ou en attente.
+
.. Sélectionnez *SUPPORT* > *Outils* > *Topologie de grille*.
.. Sélectionnez *_site_* > *_nœud d'administration principal_* > *CMN* > *Tâches de la grille* > *Configuration*.
+
Les tâches d'évaluation de la gestion du cycle de vie de l'information (ILME) sont les seules tâches de grille qui peuvent s'exécuter simultanément avec la mise à niveau du logiciel.

.. Si d'autres tâches de la grille sont actives ou en attente, attendez qu'elles se terminent ou libérez leur verrou.
+

NOTE: Contactez le support technique si une tâche ne se termine pas ou ne libère pas son verrou.



. Se référer àlink:../network/internal-grid-node-communications.html["Communications internes des nœuds de réseau"] etlink:../network/external-communications.html["Communications externes"] pour vous assurer que tous les ports requis pour StorageGRID 11.9 sont ouverts avant la mise à niveau.
+

NOTE: Aucun port supplémentaire n'est requis lors de la mise à niveau vers StorageGRID 11.9.

+
Le port requis suivant a été ajouté dans StorageGRID 11.7.  Assurez-vous qu'il est disponible avant de procéder à la mise à niveau vers StorageGRID 11.9.

+
[cols="1a,2a"]
|===
| Port | Description 


 a| 
18086
 a| 
Port TCP utilisé pour les requêtes S3 de l'équilibreur de charge StorageGRID vers LDR et le nouveau service LDR.

Avant la mise à niveau, vérifiez que ce port est ouvert depuis tous les nœuds de grille vers tous les nœuds de stockage.

Le blocage de ce port entraînera des interruptions de service S3 après la mise à niveau vers StorageGRID 11.9.

|===



CAUTION: Si vous avez ouvert des ports de pare-feu personnalisés, vous en êtes informé lors de la vérification préalable de la mise à niveau.  Vous devez contacter le support technique avant de procéder à la mise à niveau.
