---
permalink: ubuntu/configuring-docker-storage-volume.html 
sidebar: sidebar 
keywords: how to configure Docker storage volume 
summary: Avant d’installer Docker, vous devrez peut-être formater le volume de stockage Docker et le monter sur /var/lib/docker. 
---
= Configurer le volume de stockage du moteur de conteneur
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant d'installer le moteur de conteneur (Docker ou Podman), vous devrez peut-être formater le volume de stockage et le monter.


NOTE: La prise en charge de Docker comme moteur de conteneur pour les déploiements uniquement logiciels est obsolète. Docker sera remplacé par un autre moteur de conteneur dans une prochaine version.

.À propos de cette tâche
Vous pouvez ignorer ces étapes si vous prévoyez d'utiliser le stockage local pour le volume de stockage Docker et que vous disposez de suffisamment d'espace disponible sur la partition hôte contenant `/var/lib` .

.Étapes
. Créez un système de fichiers sur le volume de stockage Docker :
+
[listing]
----
sudo mkfs.ext4 docker-storage-volume-device
----
. Montez le volume de stockage Docker :
+
[listing]
----
sudo mkdir -p /var/lib/docker
sudo mount docker-storage-volume-device /var/lib/docker
----
. Ajoutez une entrée pour docker-storage-volume-device à /etc/fstab.
+
Cette étape garantit que le volume de stockage sera remonté automatiquement après le redémarrage de l’hôte.


