---
permalink: ubuntu/example-node-configuration-files.html 
sidebar: sidebar 
keywords: example node configuration files 
summary: Vous pouvez utiliser les exemples de fichiers de configuration de nœud pour vous aider à configurer les fichiers de configuration de nœud pour votre système StorageGRID .  Les exemples montrent des fichiers de configuration de nœuds pour tous les types de nœuds de grille. 
---
= Exemples de fichiers de configuration de nœuds
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser les exemples de fichiers de configuration de nœud pour vous aider à configurer les fichiers de configuration de nœud pour votre système StorageGRID .  Les exemples montrent des fichiers de configuration de nœuds pour tous les types de nœuds de grille.

Pour la plupart des nœuds, vous pouvez ajouter des informations d’adressage réseau administrateur et client (IP, masque, passerelle, etc.) lorsque vous configurez la grille à l’aide du gestionnaire de grille ou de l’API d’installation.  L’exception est le nœud d’administration principal.  Si vous souhaitez accéder à l'adresse IP du réseau d'administration du nœud d'administration principal pour terminer la configuration de la grille (parce que le réseau de grille n'est pas routé, par exemple), vous devez configurer la connexion au réseau d'administration pour le nœud d'administration principal dans son fichier de configuration de nœud.  Ceci est montré dans l'exemple.


NOTE: Dans les exemples, la cible Réseau client a été configurée comme une meilleure pratique, même si le réseau client est désactivé par défaut.



== Exemple pour le nœud d'administration principal

*Exemple de nom de fichier*: `/etc/storagegrid/nodes/dc1-adm1.conf`

*Exemple de contenu de fichier :*

[listing]
----
NODE_TYPE = VM_Admin_Node
ADMIN_ROLE = Primary
TEMPORARY_PASSWORD_TYPE = Use custom password
CUSTOM_TEMPORARY_PASSWORD = Passw0rd
BLOCK_DEVICE_VAR_LOCAL = /dev/mapper/dc1-adm1-var-local
BLOCK_DEVICE_AUDIT_LOGS = /dev/mapper/dc1-adm1-audit-logs
BLOCK_DEVICE_TABLES = /dev/mapper/dc1-adm1-tables
GRID_NETWORK_TARGET = bond0.1001
ADMIN_NETWORK_TARGET = bond0.1002
CLIENT_NETWORK_TARGET = bond0.1003

GRID_NETWORK_IP = 10.1.0.2
GRID_NETWORK_MASK = 255.255.255.0
GRID_NETWORK_GATEWAY = 10.1.0.1

ADMIN_NETWORK_CONFIG = STATIC
ADMIN_NETWORK_IP = 192.168.100.2
ADMIN_NETWORK_MASK = 255.255.248.0
ADMIN_NETWORK_GATEWAY = 192.168.100.1
ADMIN_NETWORK_ESL = 192.168.100.0/21,172.16.0.0/21,172.17.0.0/21
----


== Exemple de nœud de stockage

*Exemple de nom de fichier :* `/etc/storagegrid/nodes/dc1-sn1.conf`

*Exemple de contenu de fichier :*

[listing]
----
NODE_TYPE = VM_Storage_Node
ADMIN_IP = 10.1.0.2
BLOCK_DEVICE_VAR_LOCAL = /dev/mapper/dc1-sn1-var-local
BLOCK_DEVICE_RANGEDB_00 = /dev/mapper/dc1-sn1-rangedb-0
BLOCK_DEVICE_RANGEDB_01 = /dev/mapper/dc1-sn1-rangedb-1
BLOCK_DEVICE_RANGEDB_02 = /dev/mapper/dc1-sn1-rangedb-2
BLOCK_DEVICE_RANGEDB_03 = /dev/mapper/dc1-sn1-rangedb-3
GRID_NETWORK_TARGET = bond0.1001
ADMIN_NETWORK_TARGET = bond0.1002
CLIENT_NETWORK_TARGET = bond0.1003

GRID_NETWORK_IP = 10.1.0.3
GRID_NETWORK_MASK = 255.255.255.0
GRID_NETWORK_GATEWAY = 10.1.0.1
----


== Exemple de nœud de passerelle

*Exemple de nom de fichier :* `/etc/storagegrid/nodes/dc1-gw1.conf`

*Exemple de contenu de fichier :*

[listing]
----
NODE_TYPE = VM_API_Gateway
ADMIN_IP = 10.1.0.2
BLOCK_DEVICE_VAR_LOCAL = /dev/mapper/dc1-gw1-var-local
GRID_NETWORK_TARGET = bond0.1001
ADMIN_NETWORK_TARGET = bond0.1002
CLIENT_NETWORK_TARGET = bond0.1003
GRID_NETWORK_IP = 10.1.0.5
GRID_NETWORK_MASK = 255.255.255.0
GRID_NETWORK_GATEWAY = 10.1.0.1
----


== Exemple pour un nœud d'administration non principal

*Exemple de nom de fichier :* `/etc/storagegrid/nodes/dc1-adm2.conf`

*Exemple de contenu de fichier :*

[listing]
----
NODE_TYPE = VM_Admin_Node
ADMIN_ROLE = Non-Primary
ADMIN_IP = 10.1.0.2
BLOCK_DEVICE_VAR_LOCAL = /dev/mapper/dc1-adm2-var-local
BLOCK_DEVICE_AUDIT_LOGS = /dev/mapper/dc1-adm2-audit-logs
BLOCK_DEVICE_TABLES = /dev/mapper/dc1-adm2-tables
GRID_NETWORK_TARGET = bond0.1001
ADMIN_NETWORK_TARGET = bond0.1002
CLIENT_NETWORK_TARGET = bond0.1003

GRID_NETWORK_IP = 10.1.0.6
GRID_NETWORK_MASK = 255.255.255.0
GRID_NETWORK_GATEWAY = 10.1.0.1
----