---
permalink: ubuntu/software-requirements.html 
sidebar: sidebar 
keywords: software requirements 
summary: Vous pouvez utiliser une machine virtuelle pour héberger n’importe quel type de nœud StorageGRID .  Vous avez besoin d’une machine virtuelle pour chaque nœud de grille. 
---
= Configuration logicielle requise pour Ubuntu et Debian
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser une machine virtuelle pour héberger n’importe quel type de nœud StorageGRID .  Vous avez besoin d’une machine virtuelle pour chaque nœud de grille.

Pour installer StorageGRID sur Ubuntu ou Debian, vous devez installer certains packages logiciels tiers. Certaines distributions Linux prises en charge ne contiennent pas ces packages par défaut. Les versions de progiciels sur lesquelles les installations StorageGRID sont testées incluent celles répertoriées sur cette page.

Si vous sélectionnez une distribution Linux et une option d'installation d'exécution de conteneur qui nécessitent l'un de ces packages et qu'ils ne sont pas installés automatiquement par la distribution Linux, installez l'une des versions répertoriées ici si elles sont disponibles auprès de votre fournisseur ou du fournisseur de support de votre distribution Linux.  Sinon, utilisez les versions de package par défaut disponibles auprès de votre fournisseur.

Toutes les options d'installation nécessitent Podman ou Docker.  N'installez pas les deux packages.  Installez uniquement le package requis par votre option d’installation.


NOTE: La prise en charge de Docker comme moteur de conteneur pour les déploiements uniquement logiciels est obsolète. Docker sera remplacé par un autre moteur de conteneur dans une prochaine version.



== Versions Python testées

* 3.5.2-2
* 3.6.8-2
* 3.6.8-38
* 3.6.9-1
* 3.7.3-1
* 3.8.10-0
* 3.9.2-1
* 3.9.10-2
* 3.9.16-1
* 3.10.6-1
* 3.11.2-6




== Versions Podman testées

* 3.2.3-0
* 3.4.4+ds1
* 4.1.1-7
* 4.2.0-11
* 4.3.1+ds1-8+b1
* 4.4.1-8
* 4.4.1-12




== Versions de Docker testées


IMPORTANT: La prise en charge de Docker est obsolète et sera supprimée dans une prochaine version.

* Docker-CE 20.10.7
* Docker-CE 20.10.20-3
* Docker-CE 23.0.6-1
* Docker-CE 24.0.2-1
* Docker-CE 24.0.4-1
* Docker-CE 24.0.5-1
* Docker-CE 24.0.7-1
* 1,5-2

