---
permalink: ubuntu/understanding-apparmor-profile-installation.html 
sidebar: sidebar 
keywords: how to install AppArmor profile 
summary: 'Si vous travaillez dans un environnement Ubuntu auto-déployé et utilisez le système de contrôle d"accès obligatoire AppArmor, les profils AppArmor associés aux packages que vous installez sur le système de base peuvent être bloqués par les packages correspondants installés avec StorageGRID.' 
---
= Comprendre l'installation du profil AppArmor
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous travaillez dans un environnement Ubuntu auto-déployé et utilisez le système de contrôle d'accès obligatoire AppArmor, les profils AppArmor associés aux packages que vous installez sur le système de base peuvent être bloqués par les packages correspondants installés avec StorageGRID.

Par défaut, les profils AppArmor sont installés pour les packages que vous installez sur le système d'exploitation de base.  Lorsque vous exécutez ces packages à partir du conteneur système StorageGRID , les profils AppArmor sont bloqués.  Les packages de base DHCP, MySQL, NTP et tcdump sont en conflit avec AppArmor, et d'autres packages de base peuvent également être en conflit.

Vous avez deux choix pour gérer les profils AppArmor :

* Désactivez les profils individuels pour les packages installés sur le système de base qui chevauchent les packages du conteneur système StorageGRID .  Lorsque vous désactivez des profils individuels, une entrée apparaît dans les fichiers journaux StorageGRID indiquant qu'AppArmor est activé.
+
Utilisez les commandes suivantes :

+
[listing]
----
sudo ln -s /etc/apparmor.d/<profile.name> /etc/apparmor.d/disable/
sudo apparmor_parser -R /etc/apparmor.d/<profile.name>
----
+
*Exemple:*

+
[listing]
----
sudo ln -s /etc/apparmor.d/bin.ping /etc/apparmor.d/disable/
sudo apparmor_parser -R /etc/apparmor.d/bin.ping
----
* Désactivez complètement AppArmor.  Pour Ubuntu 9.10 ou version ultérieure, suivez les instructions de la communauté en ligne Ubuntu : https://help.ubuntu.com/community/AppArmor#Disable_AppArmor_framework["Désactiver AppArmor"^] .  La désactivation complète d'AppArmor peut ne pas être possible sur les versions plus récentes d'Ubuntu.
+
Une fois AppArmor désactivé, aucune entrée indiquant qu'AppArmor est activé n'apparaîtra dans les fichiers journaux StorageGRID .


