---
permalink: network/general-networking-requirements.html 
sidebar: sidebar 
keywords: networking requirements, storagegrid networks 
summary: Tous les déploiements StorageGRID doivent pouvoir prendre en charge les connexions suivantes. 
---
= Exigences générales de mise en réseau
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Tous les déploiements StorageGRID doivent pouvoir prendre en charge les connexions suivantes.

Ces connexions peuvent se produire via les réseaux Grid, Admin ou Client, ou les combinaisons de ces réseaux, comme illustré dans les exemples de topologie de réseau.

* *Connexions de gestion* : connexions entrantes d'un administrateur vers le nœud, généralement via SSH.  Accès par navigateur Web au Grid Manager, au Tenant Manager et au programme d'installation de l'appliance StorageGRID .
* *Connexions au serveur NTP* : connexion UDP sortante qui reçoit une réponse UDP entrante.
+
Au moins un serveur NTP doit être accessible par le nœud d’administration principal.

* *Connexions au serveur DNS* : connexion UDP sortante qui reçoit une réponse UDP entrante.
* *Connexions au serveur LDAP/Active Directory* : connexion TCP sortante depuis le service d'identité sur les nœuds de stockage.
* * AutoSupport*: Connexion TCP sortante des nœuds d'administration vers `support.netapp.com` ou un proxy configuré par le client.
* *Serveur de gestion de clés externe* : connexion TCP sortante depuis chaque nœud d'appliance avec chiffrement de nœud activé.
* Connexions TCP entrantes provenant de clients S3.
* Requêtes sortantes provenant des services de la plateforme StorageGRID tels que la réplication CloudMirror ou des pools de stockage Cloud.


Si StorageGRID ne parvient pas à contacter l'un des serveurs NTP ou DNS provisionnés à l'aide des règles de routage par défaut, il tentera automatiquement de contacter tous les réseaux (Grille, Admin et Client) tant que les adresses IP des serveurs DNS et NTP sont spécifiées.  Si les serveurs NTP ou DNS sont accessibles sur n'importe quel réseau, StorageGRID créera automatiquement des règles de routage supplémentaires pour garantir que le réseau est utilisé pour toutes les tentatives futures de connexion.


TIP: Bien que vous puissiez utiliser ces routes d'hôtes découvertes automatiquement, vous devez en général configurer manuellement les routes DNS et NTP pour garantir la connectivité en cas d'échec de la découverte automatique.

Si vous n'êtes pas prêt à configurer les réseaux administrateur et client facultatifs lors du déploiement, vous pouvez configurer ces réseaux lorsque vous approuvez les nœuds de grille pendant les étapes de configuration.  De plus, vous pouvez configurer ces réseaux une fois l'installation terminée en utilisant l'outil Modifier l'IP (voirlink:../maintain/configuring-ip-addresses.html["Configurer les adresses IP"] ).



== Connexions pour les nœuds d'administration et les nœuds de passerelle

Les nœuds d'administration doivent toujours être protégés contre les clients non fiables, tels que ceux présents sur Internet ouvert.  Vous devez vous assurer qu'aucun client non approuvé ne peut accéder à un nœud d'administration sur le réseau de grille, le réseau d'administration ou le réseau client.

Les nœuds d’administration et les nœuds de passerelle que vous prévoyez d’ajouter aux groupes de haute disponibilité doivent être configurés avec une adresse IP statique. Voir link:../admin/managing-high-availability-groups.html["Gérer les groupes de haute disponibilité"] .



== Utilisation de la traduction d'adresses réseau (NAT)

N'utilisez pas la traduction d'adresses réseau (NAT) sur le réseau Grid entre les nœuds de grille ou entre les sites StorageGRID .  Lorsque vous utilisez des adresses IPv4 privées pour le réseau Grid, ces adresses doivent être directement routables à partir de chaque nœud de grille sur chaque site.  Toutefois, si nécessaire, vous pouvez utiliser NAT entre les clients externes et les nœuds de grille, par exemple pour fournir une adresse IP publique pour un nœud de passerelle.  L'utilisation de NAT pour relier un segment de réseau public n'est prise en charge que lorsque vous utilisez une application de tunneling transparente pour tous les nœuds de la grille, ce qui signifie que les nœuds de la grille ne nécessitent aucune connaissance des adresses IP publiques.
