---
permalink: network/grid-network-requirements.html 
sidebar: sidebar 
keywords: grid network requirements 
summary: Suivez ces exigences et directives pour le réseau Grid. 
---
= Exigences du réseau de grille
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Suivez ces exigences et directives pour le réseau Grid.

* Au moment du déploiement, chaque nœud de grille doit être connecté au réseau de grille et doit pouvoir communiquer avec le nœud d'administration principal à l'aide de la configuration réseau que vous spécifiez lors du déploiement du nœud.
* Lors du fonctionnement normal du réseau, chaque nœud du réseau doit pouvoir communiquer avec tous les autres nœuds du réseau via le réseau.
+

NOTE: Le réseau Grid doit être directement routable entre chaque nœud.  La traduction d'adresses réseau (NAT) entre les nœuds n'est pas prise en charge.

* Si le réseau de grille est constitué de plusieurs sous-réseaux, ajoutez-les à la liste des sous-réseaux du réseau de grille (GNSL).  Des routes statiques sont créées sur tous les nœuds pour chaque sous-réseau du GNSL.

