---
permalink: network/internal-grid-node-communications.html 
sidebar: sidebar 
keywords: storagegrid, network port, internal communications, ports, TCP, UDP, grid communications, port 
summary: 'Le pare-feu interne StorageGRID autorise uniquement les connexions entrantes vers des ports spécifiques du réseau Grid, à l"exception des ports 22, 80, 123 et 443 (voir les informations sur les communications externes).  Les connexions sont également acceptées sur les ports définis par les points de terminaison de l"équilibreur de charge.' 
---
= Communications internes des nœuds de réseau
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le pare-feu interne StorageGRID autorise les connexions entrantes vers des ports spécifiques du réseau Grid.  Les connexions sont également acceptées sur les ports définis par les points de terminaison de l'équilibreur de charge.


NOTE: NetApp vous recommande d'activer le trafic ICMP (Internet Control Message Protocol) entre les nœuds de grille.  Autoriser le trafic ICMP peut améliorer les performances de basculement lorsqu'un nœud de grille n'est pas accessible.

En plus de l'ICMP et des ports répertoriés dans le tableau, StorageGRID utilise le protocole VRRP (Virtual Router Redundancy Protocol).  VRRP est un protocole Internet qui utilise le numéro de protocole IP 112.  StorageGRID utilise VRRP en mode monodiffusion uniquement.  VRRP n'est requis que silink:../admin/managing-high-availability-groups.html["groupes de haute disponibilité"] sont configurés.



== Directives pour les nœuds basés sur Linux

Si les stratégies de réseau d’entreprise restreignent l’accès à l’un de ces ports, vous pouvez remapper les ports au moment du déploiement à l’aide d’un paramètre de configuration de déploiement. Pour plus d'informations sur le remappage des ports et les paramètres de configuration de déploiement, consultez :

* link:../rhel/index.html["Installer StorageGRID sur Red Hat Enterprise Linux"]
* link:../ubuntu/index.html["Installer StorageGRID sur Ubuntu ou Debian"]




== Directives pour les nœuds basés sur VMware

Configurez les ports suivants uniquement si vous devez définir des restrictions de pare-feu externes au réseau VMware.

Si les stratégies de réseau d'entreprise restreignent l'accès à l'un de ces ports, vous pouvez remapper les ports lorsque vous déployez des nœuds à l'aide de VMware vSphere Web Client ou en utilisant un paramètre de fichier de configuration lors de l'automatisation du déploiement des nœuds de grille. Pour plus d'informations sur le remappage des ports et les paramètres de configuration de déploiement, consultezlink:../vmware/index.html["Installer StorageGRID sur VMware"] .



== Directives pour les nœuds d'appareils

Si les politiques de réseau d'entreprise restreignent l'accès à l'un de ces ports, vous pouvez remapper les ports à l'aide du programme d'installation de l'appliance StorageGRID . Voir https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/optional-remapping-network-ports-for-appliance.html["Facultatif : Remapper les ports réseau de l'appareil"^] .



== Ports internes StorageGRID

[cols="1a,1a,1a,1a,4a"]
|===
| Port | TCP ou UDP | Depuis | À | Détails 


 a| 
22
 a| 
TCP
 a| 
Nœud d'administration principal
 a| 
Tous les nœuds
 a| 
Pour les procédures de maintenance, le nœud d’administration principal doit pouvoir communiquer avec tous les autres nœuds à l’aide de SSH sur le port 22.  Autoriser le trafic SSH provenant d’autres nœuds est facultatif.



 a| 
80
 a| 
TCP
 a| 
appareils électroménagers
 a| 
Nœud d'administration principal
 a| 
Utilisé par les appliances StorageGRID pour communiquer avec le nœud d'administration principal pour démarrer l'installation.



 a| 
123
 a| 
UDP
 a| 
Tous les nœuds
 a| 
Tous les nœuds
 a| 
Service de protocole de temps réseau.  Chaque nœud synchronise son heure avec tous les autres nœuds à l'aide de NTP.



 a| 
443
 a| 
TCP
 a| 
Tous les nœuds
 a| 
Nœud d'administration principal
 a| 
Utilisé pour communiquer l'état au nœud d'administration principal pendant l'installation et d'autres procédures de maintenance.



 a| 
1055
 a| 
TCP
 a| 
Tous les nœuds
 a| 
Nœud d'administration principal
 a| 
Trafic interne pour les procédures d'installation, d'extension, de récupération et autres procédures de maintenance.



 a| 
1139
 a| 
TCP
 a| 
Nœuds de stockage
 a| 
Nœuds de stockage
 a| 
Trafic interne entre les nœuds de stockage.



 a| 
1501
 a| 
TCP
 a| 
Tous les nœuds
 a| 
Nœuds de stockage avec ADC
 a| 
Rapports, audits et configuration du trafic interne.



 a| 
1502
 a| 
TCP
 a| 
Tous les nœuds
 a| 
Nœuds de stockage
 a| 
Trafic interne lié à S3 et Swift.



 a| 
1504
 a| 
TCP
 a| 
Tous les nœuds
 a| 
Nœuds d'administration
 a| 
Rapport de service NMS et configuration du trafic interne.



 a| 
1505
 a| 
TCP
 a| 
Tous les nœuds
 a| 
Nœuds d'administration
 a| 
Trafic interne du service AMS.



 a| 
1506
 a| 
TCP
 a| 
Tous les nœuds
 a| 
Tous les nœuds
 a| 
État du serveur trafic interne.



 a| 
1507
 a| 
TCP
 a| 
Tous les nœuds
 a| 
Nœuds de passerelle
 a| 
Trafic interne de l'équilibreur de charge.



 a| 
1508
 a| 
TCP
 a| 
Tous les nœuds
 a| 
Nœud d'administration principal
 a| 
Gestion de la configuration du trafic interne.



 a| 
1511
 a| 
TCP
 a| 
Tous les nœuds
 a| 
Nœuds de stockage
 a| 
Trafic interne des métadonnées.



 a| 
7001
 a| 
TCP
 a| 
Nœuds de stockage
 a| 
Nœuds de stockage
 a| 
Communication inter-nœuds du cluster Cassandra TLS.



 a| 
7443
 a| 
TCP
 a| 
Tous les nœuds
 a| 
Nœud d'administration principal
 a| 
Trafic interne pour l'installation, l'extension, la récupération, d'autres procédures de maintenance et les rapports d'erreurs.



 a| 
8011
 a| 
TCP
 a| 
Tous les nœuds
 a| 
Nœud d'administration principal
 a| 
Trafic interne pour les procédures d'installation, d'extension, de récupération et autres procédures de maintenance.



 a| 
8443
 a| 
TCP
 a| 
Nœud d'administration principal
 a| 
Nœuds d'appareils
 a| 
Trafic interne lié à la procédure de mode maintenance.



 a| 
9042
 a| 
TCP
 a| 
Nœuds de stockage
 a| 
Nœuds de stockage
 a| 
Port client Cassandra.



 a| 
9999
 a| 
TCP
 a| 
Tous les nœuds
 a| 
Tous les nœuds
 a| 
Trafic interne pour plusieurs services.  Comprend les procédures de maintenance, les mesures et les mises à jour du réseau.



 a| 
10226
 a| 
TCP
 a| 
Nœuds de stockage
 a| 
Nœud d'administration principal
 a| 
Utilisé par les appliances StorageGRID pour transférer les packages AutoSupport du gestionnaire système SANtricity E-Series vers le nœud d'administration principal.



 a| 
10342
 a| 
TCP
 a| 
Tous les nœuds
 a| 
Nœud d'administration principal
 a| 
Trafic interne pour les procédures d'installation, d'extension, de récupération et autres procédures de maintenance.



 a| 
18000
 a| 
TCP
 a| 
Nœuds d'administration/de stockage
 a| 
Nœuds de stockage avec ADC
 a| 
Trafic interne du service de compte.



 a| 
18001
 a| 
TCP
 a| 
Nœuds d'administration/de stockage
 a| 
Nœuds de stockage avec ADC
 a| 
Trafic interne de la Fédération d'identité.



 a| 
18002
 a| 
TCP
 a| 
Nœuds d'administration/de stockage
 a| 
Nœuds de stockage
 a| 
Trafic API interne lié aux protocoles d'objet.



 a| 
18003
 a| 
TCP
 a| 
Nœuds d'administration/de stockage
 a| 
Nœuds de stockage avec ADC
 a| 
La plateforme gère le trafic interne.



 a| 
18017
 a| 
TCP
 a| 
Nœuds d'administration/de stockage
 a| 
Nœuds de stockage
 a| 
Trafic interne du service Data Mover pour les pools de stockage cloud.



 a| 
18019
 a| 
TCP
 a| 
Nœuds de stockage
 a| 
Nœuds de stockage
 a| 
Trafic interne du service Chunk pour le codage d'effacement.



 a| 
18082
 a| 
TCP
 a| 
Nœuds d'administration/de stockage
 a| 
Nœuds de stockage
 a| 
Trafic interne lié à S3.



 a| 
18083
 a| 
TCP
 a| 
Tous les nœuds
 a| 
Nœuds de stockage
 a| 
Trafic interne lié à Swift.



 a| 
18086
 a| 
TCP
 a| 
Tous les nœuds de la grille
 a| 
Tous les nœuds de stockage
 a| 
Trafic interne lié au service LDR.



 a| 
18200
 a| 
TCP
 a| 
Nœuds d'administration/de stockage
 a| 
Nœuds de stockage
 a| 
Statistiques supplémentaires sur les demandes des clients.



 a| 
19000
 a| 
TCP
 a| 
Nœuds d'administration/de stockage
 a| 
Nœuds de stockage avec ADC
 a| 
Trafic interne du service Keystone .

|===
.Informations connexes
link:external-communications.html["Communications externes"]
