---
permalink: network/linux-deployments.html 
sidebar: sidebar 
keywords: linux network, container engine, red hat enterprise linux rhel network, ubuntu network 
summary: 'Pour des raisons d’efficacité, de fiabilité et de sécurité, le système StorageGRID fonctionne sous Linux en tant qu’ensemble de moteurs de conteneurs.  La configuration réseau liée au moteur de conteneur n"est pas requise dans un système StorageGRID .' 
---
= Déploiements Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour des raisons d’efficacité, de fiabilité et de sécurité, le système StorageGRID fonctionne sous Linux en tant qu’ensemble de moteurs de conteneurs.  La configuration réseau liée au moteur de conteneur n'est pas requise dans un système StorageGRID .

Utilisez un périphérique non lié, tel qu’un VLAN ou une paire Ethernet virtuelle (veth), pour l’interface réseau du conteneur.  Spécifiez ce périphérique comme interface réseau dans le fichier de configuration du nœud.


CAUTION: N'utilisez pas de périphériques de liaison ou de pont directement comme interface réseau du conteneur.  Cela pourrait empêcher le démarrage du nœud en raison d’un problème de noyau avec l’utilisation de macvlan avec les périphériques bond et bridge dans l’espace de noms du conteneur.

Consultez les instructions d'installation pourlink:../rhel/index.html["Red Hat Enterprise Linux"] oulink:../ubuntu/index.html["Ubuntu ou Debian"] déploiements.



== Configuration du réseau hôte pour les déploiements de moteurs de conteneurs

Avant de démarrer votre déploiement StorageGRID sur une plateforme de moteur de conteneur, déterminez les réseaux (Grid, Admin, Client) que chaque nœud utilisera.  Vous devez vous assurer que l'interface réseau de chaque nœud est configurée sur l'interface hôte virtuelle ou physique correcte et que chaque réseau dispose d'une bande passante suffisante.



=== Hôtes physiques

Si vous utilisez des hôtes physiques pour prendre en charge les nœuds de grille :

* Assurez-vous que tous les hôtes utilisent la même interface hôte pour chaque interface de nœud.  Cette stratégie simplifie la configuration de l’hôte et permet la migration future des nœuds.
* Obtenez une adresse IP pour l’hôte physique lui-même.
+

NOTE: Une interface physique sur l'hôte peut être utilisée par l'hôte lui-même et un ou plusieurs nœuds exécutés sur l'hôte.  Toutes les adresses IP attribuées à l’hôte ou aux nœuds utilisant cette interface doivent être uniques.  L'hôte et le nœud ne peuvent pas partager d'adresses IP.

* Ouvrez les ports requis sur l’hôte.
* Si vous envisagez d'utiliser des interfaces VLAN dans StorageGRID, l'hôte doit disposer d'une ou plusieurs interfaces de jonction qui fournissent l'accès aux VLAN souhaités.  Ces interfaces peuvent être transmises au conteneur de nœuds sous la forme eth0, eth2 ou sous la forme d'interfaces supplémentaires.  Pour ajouter des interfaces de jonction ou d'accès, consultez les éléments suivants :
+
** *RHEL (avant l'installation du nœud)*:link:../rhel/creating-node-configuration-files.html["Créer des fichiers de configuration de nœud"]
** *Ubuntu ou Debian (avant d'installer le nœud)* :link:../ubuntu/creating-node-configuration-files.html["Créer des fichiers de configuration de nœud"]
** *RHEL, Ubuntu ou Debian (après l'installation du nœud)* :link:../maintain/linux-adding-trunk-or-access-interfaces-to-node.html["Linux : ajouter des interfaces trunk ou d'accès à un nœud"]






=== Recommandations de bande passante minimale

Le tableau suivant fournit les recommandations de bande passante LAN minimale pour chaque type de nœud StorageGRID et chaque type de réseau.  Vous devez provisionner chaque hôte physique ou virtuel avec une bande passante réseau suffisante pour répondre aux exigences de bande passante minimale globale pour le nombre total et le type de nœuds StorageGRID que vous prévoyez d'exécuter sur cet hôte.

[cols="1a,1a,1a,1a"]
|===
| Type de nœud 3+| Type de réseau 


 a| 
 a| 
Grille
 a| 
Administrateur
 a| 
Client



 a| 
 a| 
*Bande passante LAN minimale*



 a| 
Administrateur
 a| 
10 Gbit/s
 a| 
1 Gbit/s
 a| 
1 Gbit/s



 a| 
Porte
 a| 
10 Gbit/s
 a| 
1 Gbit/s
 a| 
10 Gbit/s



 a| 
Stockage
 a| 
10 Gbit/s
 a| 
1 Gbit/s
 a| 
10 Gbit/s



 a| 
Archive
 a| 
10 Gbit/s
 a| 
1 Gbit/s
 a| 
10 Gbit/s

|===

NOTE: Ce tableau n’inclut pas la bande passante SAN, qui est requise pour l’accès au stockage partagé.  Si vous utilisez un stockage partagé accessible via Ethernet (iSCSI ou FCoE), vous devez provisionner des interfaces physiques distinctes sur chaque hôte pour fournir une bande passante SAN suffisante.  Pour éviter d'introduire un goulot d'étranglement, la bande passante SAN pour un hôte donné doit correspondre approximativement à la bande passante réseau globale du nœud de stockage pour tous les nœuds de stockage exécutés sur cet hôte.

Utilisez le tableau pour déterminer le nombre minimum d’interfaces réseau à provisionner sur chaque hôte, en fonction du nombre et du type de nœuds StorageGRID que vous prévoyez d’exécuter sur cet hôte.

Par exemple, pour exécuter un nœud d’administration, un nœud de passerelle et un nœud de stockage sur un seul hôte :

* Connectez le réseau et les réseaux d'administration sur le nœud d'administration (nécessite 10 + 1 = 11 Gbit/s)
* Connectez le réseau et les réseaux clients sur le nœud de passerelle (nécessite 10 + 10 = 20 Gbit/s)
* Connectez le réseau Grid sur le nœud de stockage (nécessite 10 Gbit/s)


Dans ce scénario, vous devez fournir un minimum de 11 + 20 + 10 = 41 Gbit/s de bande passante réseau, qui pourrait être satisfaite par deux interfaces de 40 Gbit/s ou cinq interfaces de 10 Gbit/s, potentiellement agrégées en trunks puis partagées par les trois VLAN ou plus transportant les sous-réseaux Grid, Admin et Client locaux au centre de données physique contenant l'hôte.

Pour connaître certaines méthodes recommandées de configuration des ressources physiques et réseau sur les hôtes de votre cluster StorageGRID afin de préparer votre déploiement StorageGRID , consultez les éléments suivants :

* link:../rhel/configuring-host-network.html["Configurer le réseau hôte (Red Hat Enterprise Linux)"]
* link:../ubuntu/configuring-host-network.html["Configurer le réseau hôte (Ubuntu ou Debian)"]

