---
permalink: network/network-specific-requirements.html 
sidebar: sidebar 
keywords: network-specific requirements, network specific requirements, network requirements 
summary: Suivez les exigences pour chaque type de réseau StorageGRID . 
---
= Exigences spécifiques au réseau
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Suivez les exigences pour chaque type de réseau StorageGRID .



== Passerelles et routeurs réseau

* Si cette option est définie, la passerelle d'un réseau donné doit se trouver dans le sous-réseau du réseau spécifique.
* Si vous configurez une interface à l’aide d’un adressage statique, vous devez spécifier une adresse de passerelle autre que 0.0.0.0.
* Si vous n’avez pas de passerelle, la meilleure pratique consiste à définir l’adresse de la passerelle comme étant l’adresse IP de l’interface réseau.




== Sous-réseaux


NOTE: Chaque réseau doit être connecté à son propre sous-réseau qui ne chevauche aucun autre réseau sur le nœud.

Les restrictions suivantes sont appliquées par le gestionnaire de grille lors du déploiement.  Ils sont fournis ici pour aider à la planification du réseau avant le déploiement.

* Le masque de sous-réseau pour toute adresse IP réseau ne peut pas être 255.255.255.254 ou 255.255.255.255 (/31 ou /32 en notation CIDR).
* Le sous-réseau défini par une adresse IP d'interface réseau et un masque de sous-réseau (CIDR) ne peut pas chevaucher le sous-réseau d'une autre interface configurée sur le même nœud.
* N'utilisez pas de sous-réseaux contenant les adresses IPv4 suivantes pour le réseau de grille, le réseau d'administration ou le réseau client d'un nœud :
+
** 192 168 130 101
** 192 168 131 101
** 192 168 130 102
** 192 168 131 102
** 198.51.100.2
** 198.51.100.4


+
Par exemple, n'utilisez pas les plages de sous-réseaux suivantes pour le réseau de grille, le réseau d'administration ou le réseau client d'un nœud :

+
** 192.168.130.0/24 car cette plage de sous-réseaux contient les adresses IP 192.168.130.101 et 192.168.130.102
** 192.168.131.0/24 car cette plage de sous-réseaux contient les adresses IP 192.168.131.101 et 192.168.131.102
** 198.51.100.0/24 car cette plage de sous-réseaux contient les adresses IP 198.51.100.2 et 198.51.100.4


* Le sous-réseau Grid Network de chaque nœud doit être inclus dans le GNSL.
* Le sous-réseau du réseau d'administration ne peut pas chevaucher le sous-réseau du réseau de grille, le sous-réseau du réseau client ou tout autre sous-réseau du GNSL.
* Les sous-réseaux de l'AESL ne peuvent chevaucher aucun sous-réseau du GNSL.
* Le sous-réseau du réseau client ne peut pas chevaucher le sous-réseau du réseau de grille, le sous-réseau du réseau d'administration, aucun sous-réseau du GNSL ou aucun sous-réseau de l'AESL.




== Réseau de grille

* Au moment du déploiement, chaque nœud de grille doit être connecté au réseau de grille et doit pouvoir communiquer avec le nœud d'administration principal à l'aide de la configuration réseau que vous spécifiez lors du déploiement du nœud.
* Lors du fonctionnement normal du réseau, chaque nœud du réseau doit pouvoir communiquer avec tous les autres nœuds du réseau via le réseau.
+

NOTE: Le réseau Grid doit être directement routable entre chaque nœud.  La traduction d'adresses réseau (NAT) entre les nœuds n'est pas prise en charge.

* Si le réseau de grille est constitué de plusieurs sous-réseaux, ajoutez-les à la liste des sous-réseaux du réseau de grille (GNSL).  Des routes statiques sont créées sur tous les nœuds pour chaque sous-réseau du GNSL.
* Si l'interface Grid Network est configurée en tant que trunk pour prendre en charge les interfaces VLAN, le VLAN natif du trunk doit être le VLAN utilisé pour le trafic Grid Network.  Tous les nœuds de grille doivent être accessibles via le VLAN natif du tronc.




== Réseau d'administration

Le réseau d'administration est facultatif.  Si vous envisagez de configurer un réseau d’administration, suivez ces exigences et directives.

Les utilisations typiques du réseau d'administration incluent les connexions de gestion, AutoSupport, KMS et les connexions aux serveurs critiques tels que NTP, DNS et LDAP si ces connexions ne sont pas fournies via le réseau Grid ou le réseau client.


NOTE: Le réseau d'administration et l'AESL peuvent être uniques à chaque nœud, à condition que les services réseau et les clients souhaités soient accessibles.


NOTE: Vous devez définir au moins un sous-réseau sur le réseau d'administration pour activer les connexions entrantes à partir de sous-réseaux externes.  Les routes statiques sont générées automatiquement sur chaque nœud pour chaque sous-réseau de l'AESL.



== Réseau de clients

Le réseau client est facultatif.  Si vous envisagez de configurer un réseau client, tenez compte des considérations suivantes.

* Le réseau client est conçu pour prendre en charge le trafic des clients S3.  Si elle est configurée, la passerelle réseau client devient la passerelle par défaut du nœud.
* Si vous utilisez un réseau client, vous pouvez contribuer à sécuriser StorageGRID contre les attaques hostiles en acceptant le trafic client entrant uniquement sur les points de terminaison d'équilibrage de charge explicitement configurés. Voir link:../admin/configuring-load-balancer-endpoints.html["Configurer les points de terminaison de l'équilibreur de charge"] .
* Si l'interface réseau client est configurée en tant que jonction pour prendre en charge les interfaces VLAN, déterminez si la configuration de l'interface réseau client (eth2) est nécessaire.  Si configuré, le trafic réseau client circulera sur le VLAN natif du trunk, tel que configuré dans le commutateur.


.Informations connexes
link:../maintain/changing-nodes-network-configuration.html["Modifier la configuration du réseau de nœuds"]
