---
permalink: network/subnet-requirements.html 
sidebar: sidebar 
keywords: network subnets 
summary: Suivez ces exigences et directives pour les sous-réseaux réseau. 
---
= Exigences de sous-réseau
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Suivez ces exigences et directives pour les sous-réseaux réseau.


NOTE: Chaque réseau doit être connecté à son propre sous-réseau qui ne chevauche aucun autre réseau sur le nœud.

Les restrictions suivantes sont appliquées par le gestionnaire de grille lors du déploiement.  Ils sont fournis ici pour aider à la planification du réseau avant le déploiement.

* Le masque de sous-réseau pour toute adresse IP réseau ne peut pas être 255.255.255.254 ou 255.255.255.255 (/31 ou /32 en notation CIDR).
* Le sous-réseau défini par une adresse IP d'interface réseau et un masque de sous-réseau (CIDR) ne peut pas chevaucher le sous-réseau d'une autre interface configurée sur le même nœud.
* N'utilisez pas de sous-réseaux contenant les adresses IPv4 suivantes pour le réseau de grille, le réseau d'administration ou le réseau client d'un nœud :
+
** 192 168 130 101
** 192 168 131 101
** 192 168 130 102
** 192 168 131 102
** 198.51.100.2
** 198.51.100.4


+
Par exemple, n'utilisez pas les plages de sous-réseaux suivantes pour le réseau de grille, le réseau d'administration ou le réseau client d'un nœud :

+
** 192.168.130.0/24 car cette plage de sous-réseaux contient les adresses IP 192.168.130.101 et 192.168.130.102
** 192.168.131.0/24 car cette plage de sous-réseaux contient les adresses IP 192.168.131.101 et 192.168.131.102
** 198.51.100.0/24 car cette plage de sous-réseaux contient les adresses IP 198.51.100.2 et 198.51.100.4


* Le sous-réseau Grid Network de chaque nœud doit être inclus dans le GNSL.
* Le sous-réseau du réseau d'administration ne peut pas chevaucher le sous-réseau du réseau de grille, le sous-réseau du réseau client ou tout autre sous-réseau du GNSL.
* Les sous-réseaux de l'AESL ne peuvent chevaucher aucun sous-réseau du GNSL.
* Le sous-réseau du réseau client ne peut pas chevaucher le sous-réseau du réseau de grille, le sous-réseau du réseau d'administration, aucun sous-réseau du GNSL ou aucun sous-réseau de l'AESL.

