---
permalink: tenant/configuring-cloudmirror-replication.html 
sidebar: sidebar 
keywords: how to configure CloudMirror replication, replication xml 
summary: Vous activez la réplication CloudMirror pour un bucket en créant un XML de configuration de réplication de bucket et en utilisant Tenant Manager pour appliquer le XML au bucket. 
---
= Configurer la réplication CloudMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour activer la réplication CloudMirror pour un bucket, vous créez et appliquez un XML de configuration de réplication de bucket valide.

.Avant de commencer
* Les services de plateforme ont été activés pour votre compte locataire par un administrateur StorageGRID .
* Vous avez déjà créé un bucket pour servir de source de réplication.
* Le point de terminaison que vous souhaitez utiliser comme destination pour la réplication CloudMirror existe déjà et vous disposez de son URN.
* Vous appartenez à un groupe d'utilisateurs qui possède lelink:tenant-management-permissions.html["Gérer tous les buckets ou l'autorisation d'accès root"] .  Ces autorisations remplacent les paramètres d’autorisation dans les stratégies de groupe ou de compartiment lors de la configuration du compartiment à l’aide du gestionnaire de locataires.


.À propos de cette tâche
La réplication CloudMirror copie les objets d’un bucket source vers un bucket de destination spécifié dans un point de terminaison.

Pour obtenir des informations générales sur la réplication de bucket et comment la configurer, consultez https://docs.aws.amazon.com/AmazonS3/latest/userguide/replication.html["Documentation Amazon Simple Storage Service (S3) : Réplication d'objets"^] .  Pour plus d'informations sur la manière dont StorageGRID implémente GetBucketReplication, DeleteBucketReplication et PutBucketReplication, consultez lelink:../s3/operations-on-buckets.html["Opérations sur les godets"] .


NOTE: La réplication CloudMirror présente des similitudes et des différences importantes avec la fonctionnalité de réplication inter-grille.  Pour en savoir plus, voirlink:../admin/grid-federation-compare-cgr-to-cloudmirror.html["Comparer la réplication inter-grille et la réplication CloudMirror"] .

Notez les exigences et caractéristiques suivantes lors de la configuration de la réplication CloudMirror :

* Lorsque vous créez et appliquez un XML de configuration de réplication de compartiment valide, il doit utiliser l'URN d'un point de terminaison de compartiment S3 pour chaque destination.
* La réplication n'est pas prise en charge pour les buckets source ou de destination avec le verrouillage d'objet S3 activé.
* Si vous activez la réplication CloudMirror sur un bucket contenant des objets, les nouveaux objets ajoutés au bucket sont répliqués, mais les objets existants dans le bucket ne sont pas répliqués.  Vous devez mettre à jour les objets existants pour déclencher la réplication.
* Si vous spécifiez une classe de stockage dans le XML de configuration de réplication, StorageGRID utilise cette classe lors de l'exécution d'opérations sur le point de terminaison S3 de destination.  Le point de terminaison de destination doit également prendre en charge la classe de stockage spécifiée.  Assurez-vous de suivre toutes les recommandations fournies par le fournisseur du système de destination.


.Étapes
. Activer la réplication pour votre bucket source :
+
** Utilisez un éditeur de texte pour créer le XML de configuration de réplication requis pour activer la réplication, comme spécifié dans l'API de réplication S3.
** Lors de la configuration du XML :
+
*** Notez que StorageGRID ne prend en charge que la version V1 de la configuration de réplication.  Cela signifie que StorageGRID ne prend pas en charge l'utilisation du `Filter` élément pour les règles et suit les conventions V1 pour la suppression des versions d'objet.  Consultez la documentation Amazon sur la configuration de la réplication pour plus de détails.
*** Utilisez l’URN d’un point de terminaison de compartiment S3 comme destination.
*** Ajoutez éventuellement le `<StorageClass>` élément et spécifiez l'un des éléments suivants :
+
****  `STANDARD`: La classe de stockage par défaut.  Si vous ne spécifiez pas de classe de stockage lorsque vous téléchargez un objet, le `STANDARD` la classe de stockage est utilisée.
**** `STANDARD_IA`: (Standard - accès peu fréquent.)  Utilisez cette classe de stockage pour les données auxquelles on accède moins fréquemment, mais qui nécessitent néanmoins un accès rapide en cas de besoin.
**** `REDUCED_REDUNDANCY`:Utilisez cette classe de stockage pour les données non critiques et reproductibles qui peuvent être stockées avec moins de redondance que les `STANDARD` classe de stockage.


*** Si vous spécifiez un `Role` dans la configuration XML, il sera ignoré.  Cette valeur n'est pas utilisée par StorageGRID.
+
[listing]
----
<ReplicationConfiguration>
    <Role></Role>
    <Rule>
        <Status>Enabled</Status>
        <Prefix>2020</Prefix>
        <Destination>
           <Bucket>urn:sgws:s3:::2017-records</Bucket>
           <StorageClass>STANDARD</StorageClass>
         </Destination>
     </Rule>
</ReplicationConfiguration>
----




. Sélectionnez *Afficher les buckets* dans le tableau de bord ou sélectionnez *STOCKAGE (S3)* > *Buckets*.
. Sélectionnez le nom du bucket source.
+
La page des détails du bucket apparaît.

. Sélectionnez *Services de plateforme* > *Réplication*.
. Cochez la case *Activer la réplication*.
. Collez le XML de configuration de réplication dans la zone de texte et sélectionnez *Enregistrer les modifications*.
+

NOTE: Les services de plateforme doivent être activés pour chaque compte de locataire par un administrateur StorageGRID à l'aide de Grid Manager ou de l'API Grid Management.  Contactez votre administrateur StorageGRID si une erreur se produit lorsque vous enregistrez le XML de configuration.

. Vérifiez que la réplication est correctement configurée :
+
.. Ajoutez un objet au bucket source qui répond aux exigences de réplication telles que spécifiées dans la configuration de réplication.
+
Dans l'exemple présenté précédemment, les objets correspondant au préfixe « 2020 » sont répliqués.

.. Confirmez que l’objet a été répliqué dans le bucket de destination.
+
Pour les petits objets, la réplication se produit rapidement.





.Informations connexes
link:creating-platform-services-endpoint.html["Créer un point de terminaison des services de plateforme"]
