---
permalink: tenant/configuring-platform-services-endpoints.html 
sidebar: sidebar 
keywords: how to configure platform services endpoint 
summary: Avant de pouvoir configurer un service de plateforme pour un bucket, vous devez configurer au moins un point de terminaison comme destination du service de plateforme. 
---
= Configurer les points de terminaison des services de la plateforme
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de pouvoir configurer un service de plateforme pour un bucket, vous devez configurer au moins un point de terminaison comme destination du service de plateforme.

L'accès aux services de la plateforme est activé pour chaque locataire par un administrateur StorageGRID .  Pour créer ou utiliser un point de terminaison de services de plateforme, vous devez être un utilisateur locataire avec l'autorisation d'accès Gérer les points de terminaison ou Racine, dans une grille dont la mise en réseau a été configurée pour permettre aux nœuds de stockage d'accéder aux ressources de point de terminaison externes.  Pour un seul locataire, vous pouvez configurer un maximum de 500 points de terminaison de services de plateforme.  Contactez votre administrateur StorageGRID pour plus d'informations.



== Qu'est-ce qu'un point de terminaison de services de plateforme ?

Un point de terminaison de services de plateforme spécifie les informations dont StorageGRID a besoin pour accéder à la destination externe.

Par exemple, si vous souhaitez répliquer des objets d'un compartiment StorageGRID vers un compartiment Amazon S3, vous créez un point de terminaison de services de plateforme qui inclut les informations et les informations d'identification dont StorageGRID a besoin pour accéder au compartiment de destination sur Amazon.

Chaque type de service de plateforme nécessite son propre point de terminaison. Vous devez donc configurer au moins un point de terminaison pour chaque service de plateforme que vous prévoyez d'utiliser.  Après avoir défini un point de terminaison de services de plateforme, vous utilisez l'URN du point de terminaison comme destination dans le XML de configuration utilisé pour activer le service.

Vous pouvez utiliser le même point de terminaison comme destination pour plusieurs buckets sources.  Par exemple, vous pouvez configurer plusieurs buckets sources pour envoyer des métadonnées d'objet au même point de terminaison d'intégration de recherche afin de pouvoir effectuer des recherches dans plusieurs buckets.  Vous pouvez également configurer un bucket source pour utiliser plusieurs points de terminaison comme cible, ce qui vous permet d'effectuer des opérations telles que l'envoi de notifications sur la création d'objets à une rubrique Amazon Simple Notification Service (Amazon SNS) et de notifications sur la suppression d'objets à une deuxième rubrique Amazon SNS.



== Points de terminaison pour la réplication CloudMirror

StorageGRID prend en charge les points de terminaison de réplication qui représentent des buckets S3.  Ces buckets peuvent être hébergés sur Amazon Web Services, le même déploiement StorageGRID ou un déploiement distant, ou un autre service.



== Points de terminaison pour les notifications

StorageGRID prend en charge les points de terminaison Amazon SNS et Kafka. Les points de terminaison Simple Queue Service (SQS) ou AWS Lambda ne sont pas pris en charge.

Pour les points de terminaison Kafka, le protocole TLS mutuel n'est pas pris en charge. Par conséquent, si vous avez `ssl.client.auth` réglé sur `required` dans la configuration de votre courtier Kafka, cela peut entraîner des problèmes de configuration du point de terminaison Kafka.



== Points de terminaison pour le service d'intégration de recherche

StorageGRID prend en charge les points de terminaison d’intégration de recherche qui représentent les clusters Elasticsearch.  Ces clusters Elasticsearch peuvent être situés dans un centre de données local ou hébergés dans un cloud AWS ou ailleurs.

Le point de terminaison d'intégration de recherche fait référence à un index et un type Elasticsearch spécifiques.  Vous devez créer l'index dans Elasticsearch avant de créer le point de terminaison dans StorageGRID, sinon la création du point de terminaison échouera.  Vous n’avez pas besoin de créer le type avant de créer le point de terminaison.  StorageGRID créera le type si nécessaire lorsqu'il envoie les métadonnées de l'objet au point de terminaison.

.Informations connexes
link:../admin/index.html["Administrer StorageGRID"]
