---
permalink: tenant/creating-your-own-s3-access-keys.html 
sidebar: sidebar 
keywords: how to create your own S3 access key 
summary: 'Si vous utilisez un locataire S3 et que vous disposez de l’autorisation appropriée, vous pouvez créer vos propres clés d’accès S3.  Vous devez disposer d"une clé d"accès pour accéder à vos buckets et objets.' 
---
= Créez vos propres clés d'accès S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous utilisez un locataire S3 et que vous disposez de l’autorisation appropriée, vous pouvez créer vos propres clés d’accès S3.  Vous devez disposer d'une clé d'accès pour accéder à vos buckets et objets.

.Avant de commencer
* Vous êtes connecté au Tenant Manager à l'aide d'unlink:../admin/web-browser-requirements.html["navigateur Web pris en charge"] .
* Vous appartenez à un groupe d'utilisateurs qui possède lelink:tenant-management-permissions.html["Gérez vos propres informations d'identification S3 ou autorisation d'accès root"] .


.À propos de cette tâche
Vous pouvez créer une ou plusieurs clés d’accès S3 qui vous permettent de créer et de gérer des buckets pour votre compte locataire.  Après avoir créé une nouvelle clé d’accès, mettez à jour l’application avec votre nouvel ID de clé d’accès et votre clé d’accès secrète.  Pour des raisons de sécurité, ne créez pas plus de clés que nécessaire et supprimez les clés que vous n'utilisez pas.  Si vous n'avez qu'une seule clé et qu'elle est sur le point d'expirer, créez une nouvelle clé avant l'expiration de l'ancienne, puis supprimez l'ancienne.

Chaque clé peut avoir une date d'expiration spécifique ou aucune date d'expiration.  Suivez ces directives concernant le délai d’expiration :

* Définissez une heure d'expiration pour vos clés afin de limiter votre accès à une certaine période.  La définition d’un délai d’expiration court peut vous aider à réduire vos risques si votre ID de clé d’accès et votre clé d’accès secrète sont accidentellement exposés.  Les clés expirées sont supprimées automatiquement.
* Si le risque de sécurité dans votre environnement est faible et que vous n’avez pas besoin de créer périodiquement de nouvelles clés, vous n’avez pas besoin de définir un délai d’expiration pour vos clés.  Si vous décidez ultérieurement de créer de nouvelles clés, supprimez les anciennes clés manuellement.



CAUTION: Les compartiments et objets S3 appartenant à votre compte sont accessibles à l'aide de l'ID de clé d'accès et de la clé d'accès secrète affichées pour votre compte dans le gestionnaire de locataires.  Pour cette raison, protégez les clés d’accès comme vous le feriez avec un mot de passe.  Faites tourner régulièrement les clés d’accès, supprimez toutes les clés inutilisées de votre compte et ne les partagez jamais avec d’autres utilisateurs.

.Étapes
. Sélectionnez *STOCKAGE (S3)* > *Mes clés d'accès*.
+
La page Mes clés d’accès apparaît et répertorie toutes les clés d’accès existantes.

. Sélectionnez *Créer une clé*.
. Effectuez l’une des opérations suivantes :
+
** Sélectionnez *Ne pas définir de délai d’expiration* pour créer une clé qui n’expirera pas.  (Défaut)
** Sélectionnez *Définir une heure d’expiration* et définissez la date et l’heure d’expiration.
+

NOTE: La date d’expiration peut être au maximum de cinq ans à compter de la date actuelle.  Le délai d'expiration peut être d'au moins une minute à partir de l'heure actuelle.



. Sélectionnez *Créer une clé d'accès*.
+
La boîte de dialogue Télécharger la clé d'accès s'affiche, répertoriant votre ID de clé d'accès et votre clé d'accès secrète.

. Copiez l'ID de clé d'accès et la clé d'accès secrète dans un emplacement sûr ou sélectionnez *Télécharger .csv* pour enregistrer un fichier de feuille de calcul contenant l'ID de clé d'accès et la clé d'accès secrète.
+

CAUTION: Ne fermez pas cette boîte de dialogue tant que vous n'avez pas copié ou téléchargé ces informations.  Vous ne pouvez pas copier ou télécharger des clés une fois la boîte de dialogue fermée.

. Sélectionnez *Terminer*.
+
La nouvelle clé est répertoriée sur la page Mes clés d’accès.

. Si votre compte de locataire dispose de l'autorisation *Utiliser la connexion à la fédération de grille*, utilisez éventuellement l'API de gestion des locataires pour cloner manuellement les clés d'accès S3 du locataire sur la grille source vers le locataire sur la grille de destination. Voir link:grid-federation-clone-keys-with-api.html["Cloner les clés d'accès S3 à l'aide de l'API"] .

