---
permalink: tenant/deleting-your-own-s3-access-keys.html 
sidebar: sidebar 
keywords: how to delete S3 access key 
summary: 'Si vous utilisez un locataire S3 et que vous disposez de l’autorisation appropriée, vous pouvez supprimer vos propres clés d’accès S3.  Une fois qu"une clé d"accès est supprimée, elle ne peut plus être utilisée pour accéder aux objets et aux buckets du compte locataire.' 
---
= Supprimez vos propres clés d’accès S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous utilisez un locataire S3 et que vous disposez de l’autorisation appropriée, vous pouvez supprimer vos propres clés d’accès S3.  Une fois qu'une clé d'accès est supprimée, elle ne peut plus être utilisée pour accéder aux objets et aux buckets du compte locataire.

.Avant de commencer
* Vous êtes connecté au Tenant Manager à l'aide d'unlink:../admin/web-browser-requirements.html["navigateur Web pris en charge"] .
* Vous avez lelink:tenant-management-permissions.html["Gérez vos propres autorisations d'informations d'identification S3"] .



CAUTION: Les compartiments et objets S3 appartenant à votre compte sont accessibles à l'aide de l'ID de clé d'accès et de la clé d'accès secrète affichées pour votre compte dans le gestionnaire de locataires.  Pour cette raison, protégez les clés d’accès comme vous le feriez avec un mot de passe.  Faites tourner régulièrement les clés d’accès, supprimez toutes les clés inutilisées de votre compte et ne les partagez jamais avec d’autres utilisateurs.

.Étapes
. Sélectionnez *STOCKAGE (S3)* > *Mes clés d'accès*.
. Sur la page Mes clés d’accès, cochez la case correspondant à chaque clé d’accès que vous souhaitez supprimer.
. Sélectionnez *Touche Suppr*.
. Dans la boîte de dialogue de confirmation, sélectionnez *Touche Supprimer*.
+
Un message de confirmation apparaît dans le coin supérieur droit de la page.


