---
permalink: tenant/deleting-another-users-s3-access-keys.html 
sidebar: sidebar 
keywords: how to delete access key for other user 
summary: 'Si vous utilisez un locataire S3 et que vous disposez des autorisations appropriées, vous pouvez supprimer les clés d’accès S3 d’un autre utilisateur.  Une fois qu"une clé d"accès est supprimée, elle ne peut plus être utilisée pour accéder aux objets et aux buckets du compte locataire.' 
---
= Supprimer les clés d'accès S3 d'un autre utilisateur
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous utilisez un locataire S3 et que vous disposez des autorisations appropriées, vous pouvez supprimer les clés d’accès S3 d’un autre utilisateur.  Une fois qu'une clé d'accès est supprimée, elle ne peut plus être utilisée pour accéder aux objets et aux buckets du compte locataire.

.Avant de commencer
* Vous êtes connecté au Tenant Manager à l'aide d'unlink:../admin/web-browser-requirements.html["navigateur Web pris en charge"] .
* Vous avez lelink:tenant-management-permissions.html["Autorisation d'accès root"] .



CAUTION: Les compartiments et objets S3 appartenant à un utilisateur sont accessibles à l'aide de l'ID de clé d'accès et de la clé d'accès secrète affichées pour cet utilisateur dans le gestionnaire de locataires.  Pour cette raison, protégez les clés d’accès comme vous le feriez avec un mot de passe.  Faites tourner régulièrement les clés d’accès, supprimez toutes les clés inutilisées du compte et ne les partagez jamais avec d’autres utilisateurs.

.Étapes
. Sélectionnez *GESTION DES ACCÈS* > *Utilisateurs*.
. Depuis la page Utilisateurs, sélectionnez l’utilisateur dont vous souhaitez gérer les clés d’accès S3.
. Sur la page Détails de l’utilisateur, sélectionnez *Clés d’accès*, puis cochez la case correspondant à chaque clé d’accès que vous souhaitez supprimer.
. Sélectionnez *Actions* > *Supprimer la clé sélectionnée*.
. Dans la boîte de dialogue de confirmation, sélectionnez *Touche Supprimer*.
+
Un message de confirmation apparaît dans le coin supérieur droit de la page.


