---
permalink: tenant/tenant-management-api-versioning.html 
sidebar: sidebar 
keywords: tenant management api version 
summary: 'L"API de gestion des locataires utilise le contrôle de version pour prendre en charge les mises à niveau sans interruption.' 
---
= Gestion des versions de l'API de gestion des locataires
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'API de gestion des locataires utilise le contrôle de version pour prendre en charge les mises à niveau sans interruption.

Par exemple, cette URL de demande spécifie la version 4 de l'API.

`https://_hostname_or_ip_address_/api/v4/authorize`

La version principale de l'API est mise à jour lorsque des modifications sont apportées qui ne sont pas compatibles avec les versions plus anciennes.  La version mineure de l'API est mise à jour lorsque des modifications sont apportées qui sont _compatibles_ avec les versions plus anciennes.  Les modifications compatibles incluent l’ajout de nouveaux points de terminaison ou de nouvelles propriétés.

L'exemple suivant illustre comment la version de l'API est augmentée en fonction du type de modifications apportées.

[cols="1a,1a,1a"]
|===
| Type de modification de l'API | Ancienne version | Nouvelle version 


 a| 
Compatible avec les anciennes versions
 a| 
2,1
 a| 
2,2



 a| 
Non compatible avec les anciennes versions
 a| 
2,1
 a| 
3,0



 a| 
3,0
 a| 
4,0

|===
Lorsque vous installez le logiciel StorageGRID pour la première fois, seule la version la plus récente de l'API est activée.  Cependant, lorsque vous effectuez une mise à niveau vers une nouvelle version de fonctionnalité de StorageGRID, vous continuez à avoir accès à l'ancienne version de l'API pour au moins une version de fonctionnalité de StorageGRID .


NOTE: Vous pouvez configurer les versions prises en charge.  Consultez la section *config* de la documentation de l'API Swagger pour lelink:../admin/using-grid-management-api.html["API de gestion de grille"] pour plus d'informations.  Vous devez désactiver la prise en charge de l'ancienne version après avoir mis à jour tous les clients API pour utiliser la version la plus récente.

Les demandes obsolètes sont marquées comme obsolètes des manières suivantes :

* L'en-tête de réponse est « Obsolète : vrai »
* Le corps de la réponse JSON inclut « obsolète » : vrai
* Un avertissement obsolète est ajouté à nms.log. Par exemple:
+
[listing]
----
Received call to deprecated v2 API at POST "/api/v2/authorize"
----




== Déterminer quelles versions d'API sont prises en charge dans la version actuelle

Utilisez le `GET /versions` Requête d'API pour renvoyer une liste des versions majeures d'API prises en charge.  Cette demande se trouve dans la section *config* de la documentation de l'API Swagger.

[listing]
----
GET https://{{IP-Address}}/api/versions
{
  "responseTime": "2023-06-27T22:13:50.750Z",
  "status": "success",
  "apiVersion": "4.0",
  "data": [
    2,
    3,
    4
  ]
}
----


== Spécifier une version d'API pour une requête

Vous pouvez spécifier la version de l'API à l'aide d'un paramètre de chemin(`/api/v4` ) ou un en-tête(`Api-Version: 4` ).  Si vous fournissez les deux valeurs, la valeur de l'en-tête remplace la valeur du chemin.

[listing]
----
curl https://[IP-Address]/api/v4/grid/accounts

curl -H "Api-Version: 4" https://[IP-Address]/api/grid/accounts
----