---
permalink: tenant/update-default-retention-settings.html 
sidebar: sidebar 
keywords: update default retention for s3 object lock bucket, default retention mode, default retention period, compliance, governance 
summary: 'Si vous avez activé le verrouillage d"objet S3 lors de la création du bucket, vous pouvez modifier le bucket pour modifier les paramètres de rétention par défaut.  Vous pouvez activer (ou désactiver) la conservation par défaut et définir un mode de conservation par défaut et une période de conservation.' 
---
= Mettre à jour la conservation par défaut du verrouillage des objets S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous avez activé le verrouillage d'objet S3 lors de la création du bucket, vous pouvez modifier le bucket pour modifier les paramètres de rétention par défaut.  Vous pouvez activer (ou désactiver) la conservation par défaut et définir un mode de conservation par défaut et une période de conservation.

.Avant de commencer
* Vous êtes connecté au Tenant Manager à l'aide d'unlink:../admin/web-browser-requirements.html["navigateur Web pris en charge"] .
* Vous appartenez à un groupe d'utilisateurs qui possède lelink:tenant-management-permissions.html["Gérer tous les buckets ou l'autorisation d'accès root"] . Ces autorisations remplacent les paramètres d’autorisations dans les stratégies de groupe ou de compartiment.
* Le verrouillage des objets S3 est activé globalement pour votre système StorageGRID et vous avez activé le verrouillage des objets S3 lorsque vous avez créé le bucket. Voir link:using-s3-object-lock.html["Utilisez S3 Object Lock pour conserver les objets"] .


.Étapes
. Sélectionnez *Afficher les buckets* dans le tableau de bord ou sélectionnez *STOCKAGE (S3)* > *Buckets*.
. Sélectionnez le nom du bucket dans le tableau.
+
La page des détails du bucket apparaît.

. Dans l'onglet *Options du bucket*, sélectionnez l'accordéon *Verrouillage d'objet S3*.
. En option, activez ou désactivez la *Rétention par défaut* pour ce bucket.
+
Les modifications apportées à ce paramètre ne s'appliquent pas aux objets déjà présents dans le bucket ni aux objets susceptibles d'avoir leurs propres périodes de conservation.

. Si la *Rétention par défaut* est activée, spécifiez un *Mode de rétention par défaut* pour le bucket.
+
[cols="1a,2a"]
|===
| Mode de rétention par défaut | Description 


 a| 
Gouvernance
 a| 
** Les utilisateurs avec le `s3:BypassGovernanceRetention` l'autorisation peut utiliser le `x-amz-bypass-governance-retention: true` en-tête de demande pour contourner les paramètres de conservation.
** Ces utilisateurs peuvent supprimer une version d'objet avant que sa date de conservation ne soit atteinte.
** Ces utilisateurs peuvent augmenter, diminuer ou supprimer la date de conservation d'un objet.




 a| 
Conformité
 a| 
** L'objet ne peut pas être supprimé tant que sa date de conservation n'est pas atteinte.
** La date de conservation de l'objet peut être augmentée, mais elle ne peut pas être diminuée.
** La date de conservation de l'objet ne peut pas être supprimée tant que cette date n'est pas atteinte.


*Remarque* : votre administrateur de réseau doit vous autoriser à utiliser le mode de conformité.

|===
. Si la *Conservation par défaut* est activée, spécifiez la *Période de conservation par défaut* pour le bucket.
+
La *Période de conservation par défaut* indique la durée pendant laquelle les nouveaux objets ajoutés à ce bucket doivent être conservés, à compter du moment où ils sont ingérés. Spécifiez une valeur inférieure ou égale à la période de conservation maximale du locataire, telle que définie par l'administrateur de la grille.

+
Une période de conservation _maximale_, qui peut être une valeur comprise entre 1 jour et 100 ans, est définie lorsque l'administrateur de la grille crée le locataire.  Lorsque vous définissez une période de conservation par défaut, elle ne peut pas dépasser la valeur définie pour la période de conservation maximale.  Si nécessaire, demandez à votre administrateur de réseau d’augmenter ou de diminuer la période de conservation maximale.

. Sélectionnez *Enregistrer les modifications*.

