---
permalink: tenant/viewing-another-users-s3-access-keys.html 
sidebar: sidebar 
keywords: how to view other user access key 
summary: 'Si vous utilisez un locataire S3 et que vous disposez des autorisations appropriées, vous pouvez afficher les clés d’accès S3 d’un autre utilisateur.  Vous pouvez trier la liste par heure d"expiration afin de déterminer quelles clés expireront bientôt.  Selon vos besoins, vous pouvez créer de nouvelles clés et supprimer des clés qui ne sont plus utilisées.' 
---
= Afficher les clés d'accès S3 d'un autre utilisateur
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous utilisez un locataire S3 et que vous disposez des autorisations appropriées, vous pouvez afficher les clés d’accès S3 d’un autre utilisateur.  Vous pouvez trier la liste par heure d'expiration afin de déterminer quelles clés expireront bientôt.  Selon vos besoins, vous pouvez créer de nouvelles clés et supprimer des clés qui ne sont plus utilisées.

.Avant de commencer
* Vous êtes connecté au Tenant Manager à l'aide d'unlink:../admin/web-browser-requirements.html["navigateur Web pris en charge"] .
* Vous avez lelink:tenant-management-permissions.html["Autorisation d'accès root"] .



CAUTION: Les compartiments et objets S3 appartenant à un utilisateur sont accessibles à l'aide de l'ID de clé d'accès et de la clé d'accès secrète affichées pour cet utilisateur dans le gestionnaire de locataires.  Pour cette raison, protégez les clés d’accès comme vous le feriez avec un mot de passe.  Faites tourner régulièrement les clés d’accès, supprimez toutes les clés inutilisées du compte et ne les partagez jamais avec d’autres utilisateurs.

.Étapes
. Sélectionnez *GESTION DES ACCÈS* > *Utilisateurs*.
. Depuis la page Utilisateurs, sélectionnez l’utilisateur dont vous souhaitez afficher les clés d’accès S3.
. Depuis la page Détails de l'utilisateur, sélectionnez *Clés d'accès*.
. Trier les clés par *Délai d'expiration* ou *ID de clé d'accès*.
. Selon les besoins, créez de nouvelles clés et supprimez manuellement les clés qui ne sont plus utilisées.
+
Si vous créez de nouvelles clés avant l’expiration des clés existantes, l’utilisateur peut commencer à utiliser les nouvelles clés sans perdre temporairement l’accès aux objets du compte.

+
Les clés expirées sont supprimées automatiquement.



.Informations connexes
* link:creating-another-users-s3-access-keys.html["Créer les clés d'accès S3 d'un autre utilisateur"]
* link:deleting-another-users-s3-access-keys.html["Supprimer les clés d'accès S3 d'un autre utilisateur"]

