---
permalink: vmware/deploying-storagegrid-node-as-virtual-machine.html 
sidebar: sidebar 
keywords: how to deploy grid nodes in vsphere or vsphere web client, port, remap, port remap 
summary: Vous utilisez VMware vSphere Web Client pour déployer chaque nœud de grille en tant que machine virtuelle.  Lors du déploiement, chaque nœud de grille est créé et connecté à un ou plusieurs réseaux StorageGRID . 
---
= Déployer un nœud StorageGRID en tant que machine virtuelle
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous utilisez VMware vSphere Web Client pour déployer chaque nœud de grille en tant que machine virtuelle.  Lors du déploiement, chaque nœud de grille est créé et connecté à un ou plusieurs réseaux StorageGRID .

Si vous devez déployer des nœuds de stockage d'appliance StorageGRID , consultez https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/deploying-appliance-storage-node.html["Déployer le nœud de stockage de l'appliance"^] .

En option, vous pouvez remapper les ports du nœud ou augmenter les paramètres du processeur ou de la mémoire du nœud avant de le mettre sous tension.

.Avant de commencer
* Vous avez examiné comment fairelink:index.html["planifier et préparer l'installation"] , et vous comprenez les exigences en matière de logiciels, de processeur et de RAM, ainsi que de stockage et de performances.
* Vous connaissez VMware vSphere Hypervisor et avez de l’expérience dans le déploiement de machines virtuelles dans cet environnement.
+

NOTE: Le `open-vm-tools` package, une implémentation open source similaire à VMware Tools, est inclus avec la machine virtuelle StorageGRID .  Vous n’avez pas besoin d’installer VMware Tools manuellement.

* Vous avez téléchargé et extrait la version correcte de l'archive d'installation de StorageGRID pour VMware.
+

CAUTION: Si vous déployez le nouveau nœud dans le cadre d’une opération d’extension ou de récupération, vous devez utiliser la version de StorageGRID actuellement en cours d’exécution sur la grille.

* Vous disposez du disque de machine virtuelle StorageGRID(`.vmdk` ) déposer:


[listing, subs="specialcharacters,quotes"]
----
NetApp-_SG-version_-SHA.vmdk
----
* Vous avez le `.ovf` et `.mf` fichiers pour chaque type de nœud de grille que vous déployez :
+
[cols="1a,1a"]
|===
| Nom de fichier | Description 


| vsphere-primary-admin.ovf vsphere-primary-admin.mf  a| 
Le fichier modèle et le fichier manifeste pour le nœud d'administration principal.



| vsphere-non-primary-admin.ovf vsphere-non-primary-admin.mf  a| 
Le fichier modèle et le fichier manifeste pour un nœud d'administration non principal.



| vsphere-storage.ovf vsphere-storage.mf  a| 
Le fichier modèle et le fichier manifeste pour un nœud de stockage.



| passerelle vsphere.ovf passerelle vsphere.mf  a| 
Le fichier modèle et le fichier manifeste pour un nœud de passerelle.

|===
* Le `.vdmk` , `.ovf` , et `.mf` les fichiers sont tous dans le même répertoire.
* Vous avez un plan pour minimiser les domaines de défaillance.  Par exemple, vous ne devez pas déployer tous les nœuds de passerelle sur un seul hôte vSphere ESXi.
+

CAUTION: Dans un déploiement de production, n’exécutez pas plus d’un nœud de stockage sur une seule machine virtuelle.  N'exécutez pas plusieurs machines virtuelles sur le même hôte ESXi si cela risque de créer un problème de domaine de défaillance inacceptable.

* Si vous déployez un nœud dans le cadre d’une opération d’extension ou de récupération, vous disposez deslink:../expand/index.html["instructions pour étendre un système StorageGRID"] ou lelink:../maintain/index.html["instructions de récupération et d'entretien"] .
* Si vous déployez un nœud StorageGRID en tant que machine virtuelle avec un stockage attribué à partir d'un système NetApp ONTAP , vous avez confirmé qu'aucune stratégie de hiérarchisation FabricPool n'est activée sur le volume.  Par exemple, si un nœud StorageGRID s'exécute en tant que machine virtuelle sur un hôte VMware, assurez-vous que le volume qui sauvegarde la banque de données du nœud n'a pas de stratégie de hiérarchisation FabricPool activée.  La désactivation de la hiérarchisation FabricPool pour les volumes utilisés avec les nœuds StorageGRID simplifie le dépannage et les opérations de stockage.
+

NOTE: N'utilisez jamais FabricPool pour hiérarchiser les données liées à StorageGRID vers StorageGRID lui-même.  La hiérarchisation des données StorageGRID vers StorageGRID augmente le dépannage et la complexité opérationnelle.



.À propos de cette tâche
Suivez ces instructions pour déployer initialement des nœuds VMware, ajouter un nouveau nœud VMware dans une extension ou remplacer un nœud VMware dans le cadre d’une opération de récupération.  Sauf indication contraire dans les étapes, la procédure de déploiement de nœud est la même pour tous les types de nœuds, y compris les nœuds d'administration, les nœuds de stockage et les nœuds de passerelle.

Si vous installez un nouveau système StorageGRID :

* Vous pouvez déployer des nœuds dans n’importe quel ordre.
* Vous devez vous assurer que chaque machine virtuelle peut se connecter au nœud d’administration principal via le réseau de grille.
* Vous devez déployer tous les nœuds de grille avant de configurer la grille.


Si vous effectuez une opération d’extension ou de récupération :

* Vous devez vous assurer que la nouvelle machine virtuelle peut se connecter à tous les autres nœuds via le réseau Grid.


Si vous devez remapper l'un des ports du nœud, ne mettez pas le nouveau nœud sous tension tant que la configuration de remappage des ports n'est pas terminée.

.Étapes
. À l’aide de VCenter, déployez un modèle OVF.
+
Si vous spécifiez une URL, pointez vers un dossier contenant les fichiers suivants.  Sinon, sélectionnez chacun de ces fichiers dans un répertoire local.

+
[listing, subs="specialcharacters,quotes"]
----
NetApp-_SG-version_-SHA.vmdk
vsphere-_node_.ovf
vsphere-_node_.mf
----
+
Par exemple, s'il s'agit du premier nœud que vous déployez, utilisez ces fichiers pour déployer le nœud d'administration principal de votre système StorageGRID :

+
[listing, subs="specialcharacters,quotes"]
----
NetApp-_SG-version_-SHA.vmdk
vsphere-primary-admin.ovf
vsphere-primary-admin.mf
----
. Donnez un nom à la machine virtuelle.
+
La pratique courante consiste à utiliser le même nom pour la machine virtuelle et le nœud de grille.

. Placez la machine virtuelle dans le vApp ou le pool de ressources approprié.
. Si vous déployez le nœud d’administration principal, lisez et acceptez le contrat de licence utilisateur final.
+
Selon votre version de vCenter, l'ordre des étapes varie pour accepter le contrat de licence utilisateur final, spécifier le nom de la machine virtuelle et sélectionner une banque de données.

. Sélectionnez le stockage pour la machine virtuelle.
+
Si vous déployez un nœud dans le cadre d'une opération de récupération, suivez les instructions de la<<step_recovery_storage,étape de récupération du stockage>> pour ajouter de nouveaux disques virtuels, rattacher les disques durs virtuels du nœud de grille défaillant, ou les deux.

+
Lors du déploiement d'un nœud de stockage, utilisez 3 volumes de stockage ou plus, chaque volume de stockage étant de 4 To ou plus.  Vous devez attribuer au moins 4 To au volume 0.

+

NOTE: Le fichier .ovf du nœud de stockage définit plusieurs VMDK pour le stockage.  À moins que ces VMDK ne répondent à vos besoins de stockage, vous devez les supprimer et attribuer les VMDK ou RDM appropriés pour le stockage avant de mettre le nœud sous tension.  Les VMDK sont plus couramment utilisés dans les environnements VMware et sont plus faciles à gérer, tandis que les RDM peuvent offrir de meilleures performances pour les charges de travail qui utilisent des tailles d’objet plus grandes (par exemple, supérieures à 100 Mo).

+

NOTE: Certaines installations StorageGRID peuvent utiliser des volumes de stockage plus importants et plus actifs que les charges de travail virtualisées classiques.  Vous devrez peut-être ajuster certains paramètres de l'hyperviseur, tels que `MaxAddressableSpaceTB` , pour atteindre des performances optimales.  Si vous rencontrez des performances médiocres, contactez votre ressource de support de virtualisation pour déterminer si votre environnement pourrait bénéficier d'un réglage de configuration spécifique à la charge de travail.

. Sélectionnez les réseaux.
+
Déterminez les réseaux StorageGRID que le nœud utilisera en sélectionnant un réseau de destination pour chaque réseau source.

+
** Le réseau Grid est requis.  Vous devez sélectionner un réseau de destination dans l’environnement vSphere.  + Le réseau Grid est utilisé pour tout le trafic interne StorageGRID .  Il fournit une connectivité entre tous les nœuds du réseau, sur tous les sites et sous-réseaux.  Tous les nœuds du réseau Grid doivent pouvoir communiquer avec tous les autres nœuds.
** Si vous utilisez le réseau d’administration, sélectionnez un autre réseau de destination dans l’environnement vSphere.  Si vous n'utilisez pas le réseau d'administration, sélectionnez la même destination que celle que vous avez sélectionnée pour le réseau de grille.
** Si vous utilisez le réseau client, sélectionnez un autre réseau de destination dans l’environnement vSphere.  Si vous n'utilisez pas le réseau client, sélectionnez la même destination que celle que vous avez sélectionnée pour le réseau de grille.
** Si vous utilisez un réseau administrateur ou client, les nœuds ne doivent pas nécessairement se trouver sur les mêmes réseaux administrateur ou client.


. Pour *Personnaliser le modèle*, configurez les propriétés de nœud StorageGRID requises.
+
.. Entrez le *Nom du nœud*.
+

NOTE: Si vous récupérez un nœud de grille, vous devez saisir le nom du nœud que vous récupérez.

.. Utilisez la liste déroulante *Mot de passe d'installation temporaire* pour spécifier un mot de passe d'installation temporaire, afin de pouvoir accéder à la console de la machine virtuelle ou à l'API d'installation StorageGRID , ou utiliser SSH, avant que le nouveau nœud ne rejoigne la grille.
+

NOTE: Le mot de passe d'installation temporaire n'est utilisé que pendant l'installation du nœud.  Une fois qu'un nœud a été ajouté à la grille, vous pouvez y accéder en utilisant lelink:../admin/change-node-console-password.html["mot de passe de la console du nœud"] , qui est répertorié dans le `Passwords.txt` fichier dans le package de récupération.

+
*** *Utiliser le nom du nœud* : la valeur que vous avez fournie pour le champ *Nom du nœud* est utilisée comme mot de passe d'installation temporaire.
*** *Utiliser un mot de passe personnalisé* : un mot de passe personnalisé est utilisé comme mot de passe d'installation temporaire.
*** *Désactiver le mot de passe* : Aucun mot de passe d'installation temporaire ne sera utilisé.  Si vous devez accéder à la machine virtuelle pour déboguer les problèmes d'installation, consultezlink:troubleshooting-installation-issues.html["Résoudre les problèmes d'installation"] .


.. Si vous avez sélectionné *Utiliser un mot de passe personnalisé*, spécifiez le mot de passe d'installation temporaire que vous souhaitez utiliser dans le champ *Mot de passe personnalisé*.
.. Dans la section *Réseau de grille (eth0)*, sélectionnez STATIQUE ou DHCP pour la *Configuration IP du réseau de grille*.
+
*** Si vous sélectionnez STATIQUE, entrez l'*IP du réseau grille*, le *Masque du réseau grille*, la *Passerelle du réseau grille* et le *MTU du réseau grille*.
*** Si vous sélectionnez DHCP, l'*IP du réseau grille*, le *masque du réseau grille* et la *passerelle du réseau grille* sont automatiquement attribués.


.. Dans le champ *IP d'administration principale*, saisissez l'adresse IP du nœud d'administration principal du réseau de grille.
+

NOTE: Cette étape ne s’applique pas si le nœud que vous déployez est le nœud d’administration principal.

+
Si vous omettez l'adresse IP du nœud d'administration principal, l'adresse IP sera automatiquement détectée si le nœud d'administration principal, ou au moins un autre nœud de grille avec ADMIN_IP configuré, est présent sur le même sous-réseau.  Cependant, il est recommandé de définir ici l'adresse IP du nœud d'administration principal.

.. Dans la section *Réseau administrateur (eth1)*, sélectionnez STATIQUE, DHCP ou DÉSACTIVÉ pour la *Configuration IP du réseau administrateur*.
+
*** Si vous ne souhaitez pas utiliser le réseau d'administration, sélectionnez DÉSACTIVÉ et entrez *0.0.0.0* pour l'adresse IP du réseau d'administration.  Vous pouvez laisser les autres champs vides.
*** Si vous sélectionnez STATIQUE, entrez l'*IP du réseau administrateur*, le *Masque de réseau administrateur*, la *Passerelle du réseau administrateur* et le *MTU du réseau administrateur*.
*** Si vous sélectionnez STATIQUE, entrez la *Liste des sous-réseaux externes du réseau administrateur*.  Vous devez également configurer une passerelle.
*** Si vous sélectionnez DHCP, l'*IP du réseau administrateur*, le *masque de réseau administrateur* et la *passerelle du réseau administrateur* sont automatiquement attribués.


.. Dans la section *Réseau client (eth2)*, sélectionnez STATIQUE, DHCP ou DÉSACTIVÉ pour la *Configuration IP du réseau client*.
+
*** Si vous ne souhaitez pas utiliser le réseau client, sélectionnez DÉSACTIVÉ et entrez *0.0.0.0* pour l'adresse IP du réseau client.  Vous pouvez laisser les autres champs vides.
*** Si vous sélectionnez STATIQUE, entrez l'*IP du réseau client*, le *Masque de réseau client*, la *Passerelle réseau client* et le *MTU du réseau client*.
*** Si vous sélectionnez DHCP, l'*IP du réseau client*, le *masque de réseau client* et la *passerelle du réseau client* sont automatiquement attribués.




. Vérifiez la configuration de la machine virtuelle et apportez les modifications nécessaires.
. Lorsque vous êtes prêt à terminer, sélectionnez *Terminer* pour démarrer le téléchargement de la machine virtuelle.
. [[step_recovery_storage]]Si vous avez déployé ce nœud dans le cadre d'une opération de récupération et qu'il ne s'agit pas d'une récupération complète du nœud, effectuez ces étapes une fois le déploiement terminé :
+
.. Cliquez avec le bouton droit sur la machine virtuelle et sélectionnez *Modifier les paramètres*.
.. Sélectionnez chaque disque dur virtuel par défaut qui a été désigné pour le stockage et sélectionnez *Supprimer*.
.. En fonction des circonstances de récupération de vos données, ajoutez de nouveaux disques virtuels en fonction de vos besoins de stockage, rattachez tous les disques durs virtuels conservés à partir du nœud de grille défaillant précédemment supprimé, ou les deux.
+
Veuillez noter les consignes importantes suivantes :

+
*** Si vous ajoutez de nouveaux disques, vous devez utiliser le même type de périphérique de stockage que celui utilisé avant la récupération du nœud.
*** Le fichier .ovf du nœud de stockage définit plusieurs VMDK pour le stockage.  À moins que ces VMDK ne répondent à vos besoins de stockage, vous devez les supprimer et attribuer les VMDK ou RDM appropriés pour le stockage avant de mettre le nœud sous tension.  Les VMDK sont plus couramment utilisés dans les environnements VMware et sont plus faciles à gérer, tandis que les RDM peuvent offrir de meilleures performances pour les charges de travail qui utilisent des tailles d’objet plus grandes (par exemple, supérieures à 100 Mo).




. [[vmware-remap-ports]]Si vous devez remapper les ports utilisés par ce nœud, procédez comme suit.
+
Vous devrez peut-être remapper un port si les politiques de réseau de votre entreprise restreignent l'accès à un ou plusieurs ports utilisés par StorageGRID.  Voir lelink:../network/index.html["directives de mise en réseau"] pour les ports utilisés par StorageGRID.

+

NOTE: Ne remappez pas les ports utilisés dans les points de terminaison de l'équilibreur de charge.

+
.. Sélectionnez la nouvelle VM.
.. Dans l’onglet Configurer, sélectionnez *Paramètres* > *Options vApp*.  L'emplacement des *Options vApp* dépend de la version de vCenter.
.. Dans la table *Propriétés*, recherchez PORT_REMAP_INBOUND et PORT_REMAP.
.. Pour mapper symétriquement les communications entrantes et sortantes d'un port, sélectionnez *PORT_REMAP*.
+

NOTE: Si seul PORT_REMAP est défini, le mappage que vous spécifiez s'applique aux communications entrantes et sortantes.  Si PORT_REMAP_INBOUND est également spécifié, PORT_REMAP s'applique uniquement aux communications sortantes.

+
... Sélectionnez *Définir la valeur*.
... Entrez le mappage des ports :
+
`<network type>/<protocol>/<default port used by grid node>/<new port>`

+
`<network type>`est une grille, un administrateur ou un client, et `<protocol>` est tcp ou udp.

+
Par exemple, pour remapper le trafic SSH du port 22 vers le port 3022, entrez :

+
`client/tcp/22/3022`

+
Vous pouvez remapper plusieurs ports à l'aide d'une liste séparée par des virgules.

+
Par exemple:

+
`client/tcp/18082/443, client/tcp/18083/80`

... Sélectionnez *OK*.


.. Pour spécifier le port utilisé pour les communications entrantes vers le nœud, sélectionnez *PORT_REMAP_INBOUND*.
+

NOTE: Si vous spécifiez PORT_REMAP_INBOUND et ne spécifiez pas de valeur pour PORT_REMAP, les communications sortantes pour le port restent inchangées.

+
... Sélectionnez *Définir la valeur*.
... Entrez le mappage des ports :
+
`<network type>/<protocol>/<remapped inbound port>/<default inbound port used by grid node>`

+
`<network type>`est une grille, un administrateur ou un client, et `<protocol>` est tcp ou udp.

+
Par exemple, pour remapper le trafic SSH entrant envoyé au port 3022 afin qu'il soit reçu au port 22 par le nœud de grille, entrez ce qui suit :

+
`client/tcp/3022/22`

+
Vous pouvez remapper plusieurs ports entrants à l'aide d'une liste séparée par des virgules.

+
Par exemple:

+
`grid/tcp/3022/22, admin/tcp/3022/22`

... Sélectionnez *OK*




. Si vous souhaitez augmenter le CPU ou la mémoire du nœud à partir des paramètres par défaut :
+
.. Cliquez avec le bouton droit sur la machine virtuelle et sélectionnez *Modifier les paramètres*.
.. Modifiez le nombre de processeurs ou la quantité de mémoire selon vos besoins.
+
Définissez la *Réservation de mémoire* sur la même taille que la *Mémoire* allouée à la machine virtuelle.

.. Sélectionnez *OK*.


. Allumez la machine virtuelle.


.Après avoir terminé
Si vous avez déployé ce nœud dans le cadre d’une procédure d’extension ou de récupération, revenez à ces instructions pour terminer la procédure.
