---
permalink: vmware/post-installation-guidelines.html 
sidebar: sidebar 
keywords: after installation guidelines vmware 
summary: Une fois le déploiement et la configuration du nœud de grille terminés, suivez ces instructions pour l’adressage DHCP et les modifications de configuration réseau. 
---
= Consignes post-installation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Une fois le déploiement et la configuration du nœud de grille terminés, suivez ces instructions pour l’adressage DHCP et les modifications de configuration réseau.

* Si DHCP a été utilisé pour attribuer des adresses IP, configurez une réservation DHCP pour chaque adresse IP sur les réseaux utilisés.
+
Vous ne pouvez configurer DHCP que pendant la phase de déploiement.  Vous ne pouvez pas configurer DHCP pendant la configuration.

+

NOTE: Les nœuds redémarrent lorsque la configuration du réseau de grille est modifiée par DHCP, ce qui peut provoquer des pannes si une modification DHCP affecte plusieurs nœuds en même temps.

* Vous devez utiliser les procédures de modification d'IP si vous souhaitez modifier les adresses IP, les masques de sous-réseau et les passerelles par défaut d'un nœud de grille. Voir link:../maintain/configuring-ip-addresses.html["Configurer les adresses IP"] .
* Si vous apportez des modifications à la configuration du réseau, notamment au routage et à la passerelle, la connectivité client au nœud d'administration principal et aux autres nœuds de grille peut être perdue.  En fonction des modifications réseau appliquées, vous devrez peut-être rétablir ces connexions.

