---
permalink: vmware/software-requirements.html 
sidebar: sidebar 
keywords: software requirements 
summary: Vous pouvez utiliser une machine virtuelle pour héberger n’importe quel type de nœud StorageGRID .  Vous avez besoin d’une machine virtuelle pour chaque nœud de grille. 
---
= Configuration logicielle requise pour VMware
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser une machine virtuelle pour héberger n’importe quel type de nœud StorageGRID .  Vous avez besoin d’une machine virtuelle pour chaque nœud de grille.



== Hyperviseur VMware vSphere

Vous devez installer VMware vSphere Hypervisor sur un serveur physique préparé.  Le matériel doit être configuré correctement (y compris les versions du micrologiciel et les paramètres du BIOS) avant d'installer le logiciel VMware.

* Configurez la mise en réseau dans l'hyperviseur selon les besoins pour prendre en charge la mise en réseau du système StorageGRID que vous installez.
+
link:../network/index.html["Directives de mise en réseau"]

* Assurez-vous que le magasin de données est suffisamment grand pour les machines virtuelles et les disques virtuels nécessaires pour héberger les nœuds de grille.
* Si vous créez plusieurs banques de données, nommez chaque banque de données afin de pouvoir facilement identifier la banque de données à utiliser pour chaque nœud de grille lorsque vous créez des machines virtuelles.




== Exigences de configuration de l'hôte ESX


CAUTION: Vous devez configurer correctement le protocole de temps réseau (NTP) sur chaque hôte ESX.  Si l'heure de l'hôte est incorrecte, des effets négatifs, notamment une perte de données, peuvent se produire.



== Configuration requise pour VMware

Vous devez installer et configurer VMware vSphere et vCenter avant de déployer les nœuds StorageGRID .

Pour connaître les versions prises en charge des logiciels VMware vSphere Hypervisor et VMware vCenter Server, consultez le https://imt.netapp.com/matrix/#welcome["Outil de matrice d'interopérabilité NetApp"^] .

Pour connaître les étapes requises pour installer ces produits VMware, consultez la documentation VMware.
