---
permalink: vmware/troubleshooting-installation-issues.html 
sidebar: sidebar 
keywords: how to troubleshoot installation issues 
summary: 'Si des problèmes surviennent lors de l"installation de votre système StorageGRID , vous pouvez accéder aux fichiers journaux d"installation.' 
---
= Résoudre les problèmes d'installation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si des problèmes surviennent lors de l'installation de votre système StorageGRID , vous pouvez accéder aux fichiers journaux d'installation.

Voici les principaux fichiers journaux d'installation dont le support technique peut avoir besoin pour résoudre les problèmes.

* `/var/local/log/install.log`(trouvé sur tous les nœuds de la grille)
* `/var/local/log/gdu-server.log`(trouvé sur le nœud d'administration principal)


.Informations connexes
Pour savoir comment accéder aux fichiers journaux, consultezlink:../monitor/logs-files-reference.html["Référence des fichiers journaux"] .

Si vous avez besoin d'aide supplémentaire, contactez https://mysupport.netapp.com/site/global/dashboard["Assistance NetApp"^] .



== La réservation des ressources de la machine virtuelle nécessite un ajustement

Les fichiers OVF incluent une réservation de ressources conçue pour garantir que chaque nœud de grille dispose de suffisamment de RAM et de CPU pour fonctionner efficacement.  Si vous créez des machines virtuelles en déployant ces fichiers OVF sur VMware et que le nombre prédéfini de ressources n'est pas disponible, les machines virtuelles ne démarreront pas.

.À propos de cette tâche
Si vous êtes certain que l’hôte de la machine virtuelle dispose de ressources suffisantes pour chaque nœud de grille, ajustez manuellement les ressources allouées à chaque machine virtuelle, puis essayez de démarrer les machines virtuelles.

.Étapes
. Dans l’arborescence client VMware vSphere Hypervisor, sélectionnez la machine virtuelle qui n’est pas démarrée.
. Cliquez avec le bouton droit sur la machine virtuelle et sélectionnez *Modifier les paramètres*.
. Dans la fenêtre Propriétés des machines virtuelles, sélectionnez l’onglet *Ressources*.
. Ajuster les ressources allouées à la machine virtuelle :
+
.. Sélectionnez *CPU*, puis utilisez le curseur Réservation pour ajuster le MHz réservé à cette machine virtuelle.
.. Sélectionnez *Mémoire*, puis utilisez le curseur Réservation pour ajuster les Mo réservés à cette machine virtuelle.


. Cliquez sur *OK*.
. Répétez si nécessaire pour les autres machines virtuelles hébergées sur le même hôte VM.




== Le mot de passe d'installation temporaire a été désactivé

Lorsque vous déployez un nœud VMware, vous pouvez éventuellement spécifier un mot de passe d’installation temporaire.  Vous devez disposer de ce mot de passe pour accéder à la console VM ou utiliser SSH avant que le nouveau nœud ne rejoigne la grille.

Si vous avez choisi de désactiver le mot de passe d’installation temporaire, vous devez effectuer des étapes supplémentaires pour déboguer les problèmes d’installation.

Vous pouvez effectuer l’une des opérations suivantes :

* Redéployez la machine virtuelle, mais spécifiez un mot de passe d’installation temporaire afin de pouvoir accéder à la console ou utiliser SSH pour déboguer les problèmes d’installation.
* Utilisez vCenter pour définir le mot de passe :
+
.. Éteignez la VM.
.. Accédez à *VM*, sélectionnez l’onglet *Configurer* et sélectionnez *Options vApp*.
.. Spécifiez le type de mot de passe d'installation temporaire à définir :
+
*** Sélectionnez *CUSTOM_TEMPORARY_PASSWORD* pour définir un mot de passe temporaire personnalisé.
*** Sélectionnez *TEMPORARY_PASSWORD_TYPE* pour utiliser le nom du nœud comme mot de passe temporaire.


.. Sélectionnez *Définir la valeur*.
.. Définir le mot de passe temporaire :
+
*** Remplacez *CUSTOM_TEMPORARY_PASSWORD* par une valeur de mot de passe personnalisée.
*** Mettez à jour *TEMPORARY_PASSWORD_TYPE* avec la valeur *Utiliser le nom du nœud*.


.. Redémarrez la VM pour appliquer le nouveau mot de passe.



