---
permalink: rhel/creating-node-configuration-files.html 
sidebar: sidebar 
keywords: how to create red hat linux node configuration files, port, remap, port remap 
summary: 'Les fichiers de configuration de nœud sont de petits fichiers texte qui fournissent les informations dont le service hôte StorageGRID a besoin pour démarrer un nœud et le connecter au réseau approprié et aux ressources de stockage en bloc.  Les fichiers de configuration de nœud sont utilisés pour les nœuds virtuels et ne sont pas utilisés pour les nœuds d"appliance.' 
---
= Créer des fichiers de configuration de nœud pour les déploiements Red Hat Enterprise Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les fichiers de configuration de nœud sont de petits fichiers texte qui fournissent les informations dont le service hôte StorageGRID a besoin pour démarrer un nœud et le connecter au réseau approprié et aux ressources de stockage en bloc.  Les fichiers de configuration de nœud sont utilisés pour les nœuds virtuels et ne sont pas utilisés pour les nœuds d'appliance.



== Emplacement des fichiers de configuration des nœuds

Placez le fichier de configuration pour chaque nœud StorageGRID dans le `/etc/storagegrid/nodes` répertoire sur l'hôte où le nœud s'exécutera.  Par exemple, si vous prévoyez d'exécuter un nœud d'administration, un nœud de passerelle et un nœud de stockage sur HostA, vous devez placer trois fichiers de configuration de nœud dans `/etc/storagegrid/nodes` sur HostA.

Vous pouvez créer les fichiers de configuration directement sur chaque hôte à l'aide d'un éditeur de texte, tel que vim ou nano, ou vous pouvez les créer ailleurs et les déplacer vers chaque hôte.



== Nommage des fichiers de configuration des nœuds

Les noms des fichiers de configuration sont significatifs.  Le format est `node-name.conf` , où `node-name` est un nom que vous attribuez au nœud.  Ce nom apparaît dans le programme d'installation de StorageGRID et est utilisé pour les opérations de maintenance des nœuds, telles que la migration des nœuds.

Les noms de nœuds doivent suivre ces règles :

* Doit être unique
* Doit commencer par une lettre
* Peut contenir les caractères A à Z et a à z
* Peut contenir les chiffres de 0 à 9
* Peut contenir un ou plusieurs tirets (-)
* Ne doit pas dépasser 32 caractères, sans compter le `.conf` extension


Tous les fichiers dans `/etc/storagegrid/nodes` qui ne suivent pas ces conventions de nommage ne seront pas analysés par le service hôte.

Si vous avez prévu une topologie multi-sites pour votre réseau, un schéma de dénomination de nœud typique pourrait être :

`site-nodetype-nodenumber.conf`

Par exemple, vous pouvez utiliser `dc1-adm1.conf` pour le premier nœud d'administration du centre de données 1, et `dc2-sn3.conf` pour le troisième nœud de stockage du centre de données 2.  Cependant, vous pouvez utiliser le schéma de votre choix, à condition que tous les noms de nœuds respectent les règles de dénomination.



== Contenu d'un fichier de configuration de nœud

Un fichier de configuration contient des paires clé/valeur, avec une clé et une valeur par ligne.  Pour chaque paire clé/valeur, suivez ces règles :

* La clé et la valeur doivent être séparées par un signe égal(`=` ) et des espaces facultatifs.
* Les clés ne peuvent contenir aucun espace.
* Les valeurs peuvent contenir des espaces intégrés.
* Tout espace blanc de début ou de fin est ignoré.


Le tableau suivant définit les valeurs de toutes les clés prises en charge.  Chaque clé possède l’une des désignations suivantes :

* *Obligatoire* : Obligatoire pour chaque nœud ou pour les types de nœuds spécifiés
* *Meilleure pratique* : Facultatif, mais recommandé
* *Facultatif* : Facultatif pour tous les nœuds




=== Clés du réseau d'administration



==== ADMIN_IP

[cols="4a,2a"]
|===
| Valeur | Désignation 


 a| 
Adresse IPv4 du réseau de grille du nœud d'administration principal de la grille à laquelle appartient ce nœud.  Utilisez la même valeur que celle que vous avez spécifiée pour GRID_NETWORK_IP pour le nœud de grille avec NODE_TYPE = VM_Admin_Node et ADMIN_ROLE = Primary. Si vous omettez ce paramètre, le nœud tente de découvrir un nœud d’administration principal à l’aide de mDNS.

link:how-grid-nodes-discover-primary-admin-node.html["Comment les nœuds de grille découvrent le nœud d'administration principal"]

*Remarque* : cette valeur est ignorée et peut être interdite sur le nœud d’administration principal.
 a| 
Meilleures pratiques

|===


==== CONFIG_RÉSEAU_ADMIN

[cols="4a,2a"]
|===
| Valeur | Désignation 


 a| 
DHCP, STATIQUE ou DÉSACTIVÉ
 a| 
Facultatif

|===


==== ADMIN_RESEAU_ESL

[cols="4a,2a"]
|===
| Valeur | Désignation 


 a| 
Liste séparée par des virgules des sous-réseaux en notation CIDR avec lesquels ce nœud doit communiquer à l'aide de la passerelle réseau d'administration.

Exemple: `172.16.0.0/21,172.17.0.0/21`
 a| 
Facultatif

|===


==== PASSERELLE_RÉSEAU_ADMIN

[cols="4a,2a"]
|===
| Valeur | Désignation 


 a| 
Adresse IPv4 de la passerelle du réseau d'administration local pour ce nœud.  Doit être sur le sous-réseau défini par ADMIN_NETWORK_IP et ADMIN_NETWORK_MASK.  Cette valeur est ignorée pour les réseaux configurés par DHCP.

Exemples:

`1.1.1.1`

`10.224.4.81`
 a| 
Obligatoire si `ADMIN_NETWORK_ESL` est spécifié.  Facultatif sinon.

|===


==== ADMIN_RESEAU_IP

[cols="4a,2a"]
|===
| Valeur | Désignation 


 a| 
Adresse IPv4 de ce nœud sur le réseau d'administration.  Cette clé n'est requise que lorsque ADMIN_NETWORK_CONFIG = STATIC ; ne la spécifiez pas pour d'autres valeurs.

Exemples:

`1.1.1.1`

`10.224.4.81`
 a| 
Obligatoire lorsque ADMIN_NETWORK_CONFIG = STATIC.

Facultatif sinon.

|===


==== ADMIN_RESEAU_MAC

[cols="4a,2a"]
|===
| Valeur | Désignation 


 a| 
L'adresse MAC de l'interface réseau d'administration dans le conteneur.

Ce champ est facultatif.  Si elle est omise, une adresse MAC sera générée automatiquement.

Doit être composé de 6 paires de chiffres hexadécimaux séparés par des deux points.

Exemple: `b2:9c:02:c2:27:10`
 a| 
Facultatif

|===


==== MASQUE_RÉSEAU_ADMIN

[cols="4a,2a"]
|===
| Valeur | Désignation 


 a| 
Masque de réseau IPv4 pour ce nœud, sur le réseau d'administration.  Spécifiez cette clé lorsque ADMIN_NETWORK_CONFIG = STATIC ; ne la spécifiez pas pour d'autres valeurs.

Exemples:

`255.255.255.0`

`255.255.248.0`
 a| 
Obligatoire si ADMIN_NETWORK_IP est spécifié et ADMIN_NETWORK_CONFIG = STATIC.

Facultatif sinon.

|===


==== ADMIN_RESEAU_MTU

[cols="4a,2a"]
|===
| Valeur | Désignation 


 a| 
L'unité de transmission maximale (MTU) pour ce nœud sur le réseau d'administration.  Ne spécifiez pas si ADMIN_NETWORK_CONFIG = DHCP.  Si spécifié, la valeur doit être comprise entre 1280 et 9216.  Si omis, 1500 est utilisé.

Si vous souhaitez utiliser des trames jumbo, définissez le MTU sur une valeur adaptée aux trames jumbo, telle que 9 000.  Sinon, conservez la valeur par défaut.

*IMPORTANT* : La valeur MTU du réseau doit correspondre à la valeur configurée sur le port du commutateur auquel le nœud est connecté.  Dans le cas contraire, des problèmes de performances du réseau ou une perte de paquets pourraient survenir.

Exemples:

`1500`

`8192`
 a| 
Facultatif

|===


==== ADMIN_RÉSEAU_CIBLE

[cols="4a,2a"]
|===
| Valeur | Désignation 


 a| 
Nom du périphérique hôte que vous utiliserez pour l'accès au réseau d'administration par le nœud StorageGRID .  Seuls les noms d'interface réseau sont pris en charge.  En règle générale, vous utilisez un nom d'interface différent de celui spécifié pour GRID_NETWORK_TARGET ou CLIENT_NETWORK_TARGET.

*Remarque* : n'utilisez pas de périphériques de liaison ou de pont comme cible réseau.  Configurez un VLAN (ou une autre interface virtuelle) sur le périphérique de liaison ou utilisez un pont et une paire Ethernet virtuelle (veth).

*Meilleure pratique* : spécifiez une valeur même si ce nœud n’aura pas initialement d’adresse IP de réseau d’administration.  Vous pouvez ensuite ajouter une adresse IP de réseau d’administration ultérieurement, sans avoir à reconfigurer le nœud sur l’hôte.

Exemples:

`bond0.1002`

`ens256`
 a| 
Meilleures pratiques

|===


==== TYPE_CIBLE_RÉSEAU_ADMIN

[cols="4a,2a"]
|===
| Valeur | Désignation 


 a| 
Interface (c'est la seule valeur prise en charge.)
 a| 
Facultatif

|===


==== ADMIN_RÉSEAU_TYPE_CIBLE_INTERFACE_CLONE_MAC

[cols="4a,2a"]
|===
| Valeur | Désignation 


 a| 
Vrai ou faux

Définissez la clé sur « true » pour que le conteneur StorageGRID utilise l'adresse MAC de l'interface cible de l'hôte sur le réseau d'administration.

*Meilleure pratique :* dans les réseaux où le mode promiscuité est requis, utilisez plutôt la clé ADMIN_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC.

Pour plus de détails sur le clonage MAC :

* link:../rhel/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["Considérations et recommandations pour le clonage d'adresses MAC (Red Hat Enterprise Linux)"]
* link:../ubuntu/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["Considérations et recommandations pour le clonage d'adresses MAC (Ubuntu ou Debian)"]

 a| 
Meilleures pratiques

|===


==== RÔLE_ADMIN

[cols="4a,2a"]
|===
| Valeur | Désignation 


 a| 
Primaire ou non primaire

Cette clé n'est requise que lorsque NODE_TYPE = VM_Admin_Node ; ne la spécifiez pas pour d'autres types de nœuds.
 a| 
Obligatoire lorsque NODE_TYPE = VM_Admin_Node

Facultatif sinon.

|===


=== Bloquer les clés de l'appareil



==== BLOQUER_LES_JOURNAUX_D'AUDIT_DE_L'APPAREIL

[cols="4a,2a"]
|===
| Valeur | Désignation 


 a| 
Chemin et nom du fichier spécial du périphérique de bloc que ce nœud utilisera pour le stockage persistant des journaux d'audit.

Exemples:

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-adm1-audit-logs`
 a| 
Obligatoire pour les nœuds avec NODE_TYPE = VM_Admin_Node.  Ne le spécifiez pas pour d’autres types de nœuds.

|===


==== BLOCK_DEVICE_RANGEDB_nnn

[cols="4a,2a"]
|===
| Valeur | Désignation 


 a| 
Chemin et nom du fichier spécial du périphérique de bloc que ce nœud utilisera pour le stockage d'objets persistants.  Cette clé n'est requise que pour les nœuds avec NODE_TYPE = VM_Storage_Node ; ne la spécifiez pas pour les autres types de nœuds.

Seul BLOCK_DEVICE_RANGEDB_000 est requis ; les autres sont facultatifs.  Le périphérique de bloc spécifié pour BLOCK_DEVICE_RANGEDB_000 doit être d'au moins 4 To ; les autres peuvent être plus petits.

Ne laissez pas de trous.  Si vous spécifiez BLOCK_DEVICE_RANGEDB_005, vous devez également spécifier BLOCK_DEVICE_RANGEDB_004.

*Remarque* : pour des raisons de compatibilité avec les déploiements existants, les clés à deux chiffres sont prises en charge pour les nœuds mis à niveau.

Exemples:

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-sn1-rangedb-000`
 a| 
Requis:

BLOCK_DEVICE_RANGEDB_000

Facultatif:

BLOCK_DEVICE_RANGEDB_001

BLOCK_DEVICE_RANGEDB_002

BLOCK_DEVICE_RANGEDB_003

BLOCK_DEVICE_RANGEDB_004

BLOCK_DEVICE_RANGEDB_005

BLOCK_DEVICE_RANGEDB_006

BLOCK_DEVICE_RANGEDB_007

BLOCK_DEVICE_RANGEDB_008

BLOCK_DEVICE_RANGEDB_009

BLOCK_DEVICE_RANGEDB_010

BLOCK_DEVICE_RANGEDB_011

BLOCK_DEVICE_RANGEDB_012

BLOCK_DEVICE_RANGEDB_013

BLOCK_DEVICE_RANGEDB_014

BLOCK_DEVICE_RANGEDB_015

|===


==== BLOCK_DEVICE_TABLES

[cols="4a,2a"]
|===
| Valeur | Désignation 


 a| 
Chemin et nom du fichier spécial du périphérique de bloc que ce nœud utilisera pour le stockage persistant des tables de base de données.  Cette clé n'est requise que pour les nœuds avec NODE_TYPE = VM_Admin_Node ; ne la spécifiez pas pour les autres types de nœuds.

Exemples:

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-adm1-tables`
 a| 
Obligatoire

|===


==== BLOC_DEVICE_VAR_LOCAL

[cols="4a,2a"]
|===
| Valeur | Désignation 


 a| 
Chemin et nom du fichier spécial du périphérique de bloc que ce nœud utilisera pour son `/var/local` stockage persistant.

Exemples:

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-sn1-var-local`
 a| 
Obligatoire

|===


=== Clés du réseau client



==== CONFIG_RÉSEAU_CLIENT

[cols="4a,2a"]
|===
| Valeur | Désignation 


 a| 
DHCP, STATIQUE ou DÉSACTIVÉ
 a| 
Facultatif

|===


==== PASSERELLE_RÉSEAU_CLIENT

[cols="4a,2a"]
|===


 a| 
Valeur
 a| 
Désignation



 a| 
Adresse IPv4 de la passerelle réseau client locale pour ce nœud, qui doit se trouver sur le sous-réseau défini par CLIENT_NETWORK_IP et CLIENT_NETWORK_MASK.  Cette valeur est ignorée pour les réseaux configurés par DHCP.

Exemples:

`1.1.1.1`

`10.224.4.81`
 a| 
Facultatif

|===


==== IP_RÉSEAU_CLIENT

[cols="4a,2a"]
|===
| Valeur | Désignation 


 a| 
Adresse IPv4 de ce nœud sur le réseau client.

Cette clé n'est requise que lorsque CLIENT_NETWORK_CONFIG = STATIC ; ne la spécifiez pas pour d'autres valeurs.

Exemples:

`1.1.1.1`

`10.224.4.81`
 a| 
Obligatoire lorsque CLIENT_NETWORK_CONFIG = STATIC

Facultatif sinon.

|===


==== CLIENT_RÉSEAU_MAC

[cols="4a,2a"]
|===
| Valeur | Désignation 


 a| 
L'adresse MAC de l'interface réseau client dans le conteneur.

Ce champ est facultatif.  Si elle est omise, une adresse MAC sera générée automatiquement.

Doit être composé de 6 paires de chiffres hexadécimaux séparés par des deux points.

Exemple: `b2:9c:02:c2:27:20`
 a| 
Facultatif

|===


==== MASQUE_RÉSEAU_CLIENT

[cols="4a,2a"]
|===
| Valeur | Désignation 


 a| 
Masque de réseau IPv4 pour ce nœud sur le réseau client.

Spécifiez cette clé lorsque CLIENT_NETWORK_CONFIG = STATIC ; ne la spécifiez pas pour d'autres valeurs.

Exemples:

`255.255.255.0`

`255.255.248.0`
 a| 
Obligatoire si CLIENT_NETWORK_IP est spécifié et CLIENT_NETWORK_CONFIG = STATIC

Facultatif sinon.

|===


==== CLIENT_RESEAU_MTU

[cols="4a,2a"]
|===
| Valeur | Désignation 


 a| 
L'unité de transmission maximale (MTU) pour ce nœud sur le réseau client.  Ne spécifiez pas si CLIENT_NETWORK_CONFIG = DHCP.  Si spécifié, la valeur doit être comprise entre 1280 et 9216.  Si omis, 1500 est utilisé.

Si vous souhaitez utiliser des trames jumbo, définissez le MTU sur une valeur adaptée aux trames jumbo, telle que 9 000.  Sinon, conservez la valeur par défaut.

*IMPORTANT* : La valeur MTU du réseau doit correspondre à la valeur configurée sur le port du commutateur auquel le nœud est connecté.  Dans le cas contraire, des problèmes de performances du réseau ou une perte de paquets pourraient survenir.

Exemples:

`1500`

`8192`
 a| 
Facultatif

|===


==== CLIENT_RÉSEAU_CIBLE

[cols="4a,2a"]
|===
| Valeur | Désignation 


 a| 
Nom du périphérique hôte que vous utiliserez pour l'accès au réseau client par le nœud StorageGRID .  Seuls les noms d'interface réseau sont pris en charge.  En règle générale, vous utilisez un nom d’interface différent de celui spécifié pour GRID_NETWORK_TARGET ou ADMIN_NETWORK_TARGET.

*Remarque* : n'utilisez pas de périphériques de liaison ou de pont comme cible réseau.  Configurez un VLAN (ou une autre interface virtuelle) sur le périphérique de liaison ou utilisez un pont et une paire Ethernet virtuelle (veth).

*Meilleure pratique :* spécifiez une valeur même si ce nœud n’aura pas initialement d’adresse IP de réseau client.  Vous pouvez ensuite ajouter une adresse IP de réseau client ultérieurement, sans avoir à reconfigurer le nœud sur l'hôte.

Exemples:

`bond0.1003`

`ens423`
 a| 
Meilleures pratiques

|===


==== TYPE_CIBLE_RÉSEAU_CLIENT

[cols="4a,2a"]
|===
| Valeur | Désignation 


 a| 
Interface (il s'agit de la seule valeur prise en charge.)
 a| 
Facultatif

|===


==== CLIENT_RÉSEAU_TYPE_CIBLE_INTERFACE_CLONE_MAC

[cols="4a,2a"]
|===
| Valeur | Désignation 


 a| 
Vrai ou faux

Définissez la clé sur « true » pour que le conteneur StorageGRID utilise l’adresse MAC de l’interface cible de l’hôte sur le réseau client.

*Meilleure pratique :* dans les réseaux où le mode promiscuité est requis, utilisez plutôt la clé CLIENT_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC.

Pour plus de détails sur le clonage MAC :

* link:../rhel/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["Considérations et recommandations pour le clonage d'adresses MAC (Red Hat Enterprise Linux)"]
* link:../ubuntu/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["Considérations et recommandations pour le clonage d'adresses MAC (Ubuntu ou Debian)"]

 a| 
Meilleures pratiques

|===


=== Clés du réseau Grid



==== CONFIG_RÉSEAU_GRILLE

[cols="4a,2a"]
|===
| Valeur | Désignation 


 a| 
STATIQUE ou DHCP

La valeur par défaut est STATIC si elle n'est pas spécifiée.
 a| 
Meilleures pratiques

|===


==== PASSERELLE_RÉSEAU_GRILLE

[cols="4a,2a"]
|===
| Valeur | Désignation 


 a| 
Adresse IPv4 de la passerelle du réseau Grid local pour ce nœud, qui doit se trouver sur le sous-réseau défini par GRID_NETWORK_IP et GRID_NETWORK_MASK.  Cette valeur est ignorée pour les réseaux configurés par DHCP.

Si le réseau Grid est un sous-réseau unique sans passerelle, utilisez soit l'adresse de passerelle standard pour le sous-réseau (XYZ1), soit la valeur GRID_NETWORK_IP de ce nœud ; l'une ou l'autre valeur simplifiera les futures extensions potentielles du réseau Grid.
 a| 
Obligatoire

|===


==== IP_RÉSEAU_GRILLE

[cols="4a,2a"]
|===
| Valeur | Désignation 


 a| 
Adresse IPv4 de ce nœud sur le réseau Grid.  Cette clé n'est requise que lorsque GRID_NETWORK_CONFIG = STATIC ; ne la spécifiez pas pour d'autres valeurs.

Exemples:

`1.1.1.1`

`10.224.4.81`
 a| 
Obligatoire lorsque GRID_NETWORK_CONFIG = STATIC

Facultatif sinon.

|===


==== GRILLE_RÉSEAU_MAC

[cols="4a,2a"]
|===
| Valeur | Désignation 


 a| 
L'adresse MAC de l'interface Grid Network dans le conteneur.

Doit être composé de 6 paires de chiffres hexadécimaux séparés par des deux points.

Exemple: `b2:9c:02:c2:27:30`
 a| 
Facultatif

Si elle est omise, une adresse MAC sera générée automatiquement.

|===


==== MASQUE_RÉSEAU_GRILLE

[cols="4a,2a"]
|===
| Valeur | Désignation 


 a| 
Masque de réseau IPv4 pour ce nœud sur le réseau Grid.  Spécifiez cette clé lorsque GRID_NETWORK_CONFIG = STATIC ; ne la spécifiez pas pour d'autres valeurs.

Exemples:

`255.255.255.0`

`255.255.248.0`
 a| 
Obligatoire lorsque GRID_NETWORK_IP est spécifié et GRID_NETWORK_CONFIG = STATIC.

Facultatif sinon.

|===


==== RÉSEAU_GRILLE_MTU

[cols="4a,2a"]
|===
| Valeur | Désignation 


 a| 
L'unité de transmission maximale (MTU) pour ce nœud sur le réseau Grid.  Ne spécifiez pas si GRID_NETWORK_CONFIG = DHCP.  Si spécifié, la valeur doit être comprise entre 1280 et 9216.  Si omis, 1500 est utilisé.

Si vous souhaitez utiliser des trames jumbo, définissez le MTU sur une valeur adaptée aux trames jumbo, telle que 9 000.  Sinon, conservez la valeur par défaut.

*IMPORTANT* : La valeur MTU du réseau doit correspondre à la valeur configurée sur le port du commutateur auquel le nœud est connecté.  Dans le cas contraire, des problèmes de performances du réseau ou une perte de paquets pourraient survenir.

*IMPORTANT* : pour des performances réseau optimales, tous les nœuds doivent être configurés avec des valeurs MTU similaires sur leurs interfaces Grid Network.  L'alerte *Incompatibilité MTU du réseau de grille* est déclenchée s'il existe une différence significative dans les paramètres MTU du réseau de grille sur des nœuds individuels.  Les valeurs MTU ne doivent pas nécessairement être les mêmes pour tous les types de réseaux.

Exemples:

`1500`

`8192`
 a| 
Facultatif

|===


==== GRILLE_RÉSEAU_CIBLE

[cols="4a,2a"]
|===
| Valeur | Désignation 


 a| 
Nom du périphérique hôte que vous utiliserez pour l'accès au réseau Grid par le nœud StorageGRID .  Seuls les noms d'interface réseau sont pris en charge.  En règle générale, vous utilisez un nom d'interface différent de celui spécifié pour ADMIN_NETWORK_TARGET ou CLIENT_NETWORK_TARGET.

*Remarque* : n'utilisez pas de périphériques de liaison ou de pont comme cible réseau.  Configurez un VLAN (ou une autre interface virtuelle) sur le périphérique de liaison ou utilisez un pont et une paire Ethernet virtuelle (veth).

Exemples:

`bond0.1001`

`ens192`
 a| 
Obligatoire

|===


==== TYPE_CIBLE_RÉSEAU_GRILLE

[cols="4a,2a"]
|===
| Valeur | Désignation 


 a| 
Interface (c'est la seule valeur prise en charge.)
 a| 
Facultatif

|===


==== GRID_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC

[cols="4a,2a"]
|===
| Valeur | Désignation 


 a| 
Vrai ou faux

Définissez la valeur de la clé sur « true » pour que le conteneur StorageGRID utilise l’adresse MAC de l’interface cible de l’hôte sur le réseau Grid.

*Meilleure pratique :* dans les réseaux où le mode promiscuité est requis, utilisez plutôt la clé GRID_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC.

Pour plus de détails sur le clonage MAC :

* link:../rhel/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["Considérations et recommandations pour le clonage d'adresses MAC (Red Hat Enterprise Linux)"]
* link:../ubuntu/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["Considérations et recommandations pour le clonage d'adresses MAC (Ubuntu ou Debian)"]

 a| 
Meilleures pratiques

|===


=== Clé de mot de passe d'installation (temporaire)



==== HACHAGE_DE_MOT_DE_PASSE_TEMPORAIRE_PERSONNALISÉ

[cols="4a,2a"]
|===
| Valeur | Désignation 


 a| 
Pour le nœud d’administration principal, définissez un mot de passe temporaire par défaut pour l’API d’installation StorageGRID pendant l’installation.

*Remarque* : définissez un mot de passe d’installation sur le nœud d’administration principal uniquement.  Si vous tentez de définir un mot de passe sur un autre type de nœud, la validation du fichier de configuration du nœud échouera.

La définition de cette valeur n'a aucun effet une fois l'installation terminée.

Si cette clé est omise, aucun mot de passe temporaire n'est défini par défaut.  Vous pouvez également définir un mot de passe temporaire à l’aide de l’API d’installation StorageGRID .

Doit être un `crypt()` Hachage de mot de passe SHA-512 avec format `$6$<salt>$<password hash>` pour un mot de passe d'au moins 8 et d'au plus 32 caractères.

Ce hachage peut être généré à l’aide d’outils CLI, tels que `openssl passwd` commande en mode SHA-512.
 a| 
Meilleures pratiques

|===


=== Clé des interfaces



==== INTERFACE_CIBLE_nnnn

[cols="4a,2a"]
|===
| Valeur | Désignation 


 a| 
Nom et description facultative d'une interface supplémentaire que vous souhaitez ajouter à ce nœud.  Vous pouvez ajouter plusieurs interfaces supplémentaires à chaque nœud.

Pour _nnnn_, spécifiez un numéro unique pour chaque entrée INTERFACE_TARGET que vous ajoutez.

Pour la valeur, spécifiez le nom de l’interface physique sur l’hôte bare-metal.  Ensuite, si vous le souhaitez, ajoutez une virgule et fournissez une description de l’interface, qui s’affiche sur la page Interfaces VLAN et sur la page Groupes HA.

Exemple: `INTERFACE_TARGET_0001=ens256, Trunk`

Si vous ajoutez une interface de jonction, vous devez configurer une interface VLAN dans StorageGRID.  Si vous ajoutez une interface d’accès, vous pouvez ajouter l’interface directement à un groupe HA ; vous n’avez pas besoin de configurer une interface VLAN.
 a| 
Facultatif

|===


=== Clé RAM maximale



==== RAM MAXIMALE

[cols="4a,2a"]
|===
| Valeur | Désignation 


 a| 
La quantité maximale de RAM que ce nœud est autorisé à consommer.  Si cette clé est omise, le nœud n’a aucune restriction de mémoire.  Lorsque vous définissez ce champ pour un nœud de niveau production, spécifiez une valeur d'au moins 24 Go et de 16 à 32 Go inférieure à la RAM totale du système.

*Remarque* : la valeur RAM affecte l'espace réservé réel aux métadonnées d'un nœud. Voir lelink:../admin/managing-object-metadata-storage.html["description de ce qu'est l'espace réservé aux métadonnées"] .

Le format de ce champ est `_numberunit_` , où `_unit_` peut être `b` , `k` , `m` , ou `g` .

Exemples:

`24g`

`38654705664b`

*Remarque* : si vous souhaitez utiliser cette option, vous devez activer la prise en charge du noyau pour les groupes de mémoire.
 a| 
Facultatif

|===


=== Clés de type de nœud



==== TYPE_NOEUD

[cols="4a,2a"]
|===
| Valeur | Désignation 


 a| 
Type de nœud :

* Nœud_Admin_VM
* Nœud de stockage VM
* Nœud d'archive VM
* Passerelle VM_API

 a| 
Obligatoire

|===


==== TYPE_DE_STOCKAGE

[cols="4a,2a"]
|===
| Valeur | Désignation 


 a| 
Définit le type d’objets qu’un nœud de stockage contient. Pour plus d'informations, consultez la section link:../primer/what-storage-node-is.html#types-of-storage-nodes["Types de nœuds de stockage"] .  Cette clé n'est requise que pour les nœuds avec NODE_TYPE = VM_Storage_Node ; ne la spécifiez pas pour les autres types de nœuds.  Types de stockage :

* combiné
* données
* métadonnées


*Remarque* : si le STORAGE_TYPE n'est pas spécifié, le type de nœud de stockage est défini sur combiné (données et métadonnées) par défaut.
 a| 
Facultatif

|===


=== Clés de remappage des ports



==== PORT_REMAP

[cols="4a,2a"]
|===
| Valeur | Désignation 


 a| 
Remappe tout port utilisé par un nœud pour les communications internes du nœud de grille ou les communications externes.  Le remappage des ports est nécessaire si les politiques de réseau d'entreprise restreignent un ou plusieurs ports utilisés par StorageGRID, comme décrit danslink:../network/internal-grid-node-communications.html["Communications internes des nœuds de réseau"] oulink:../network/external-communications.html["Communications externes"] .

*IMPORTANT* : Ne remappez pas les ports que vous prévoyez d’utiliser pour configurer les points de terminaison de l’équilibreur de charge.

*Remarque* : si seul PORT_REMAP est défini, le mappage que vous spécifiez est utilisé pour les communications entrantes et sortantes.  Si PORT_REMAP_INBOUND est également spécifié, PORT_REMAP s'applique uniquement aux communications sortantes.

Le format utilisé est : `_network type_/_protocol_/_default port used by grid node_/_new port_` , où `_network type_` est une grille, un administrateur ou un client, et `_protocol_` est tcp ou udp.

Exemple: `PORT_REMAP = client/tcp/18082/443`

Vous pouvez également remapper plusieurs ports à l’aide d’une liste séparée par des virgules.

Exemple: `PORT_REMAP = client/tcp/18082/443, client/tcp/18083/80`
 a| 
Facultatif

|===


==== PORT_REMAP_ENTRANT

[cols="4a,2a"]
|===
| Valeur | Désignation 


 a| 
Remappe les communications entrantes vers le port spécifié.  Si vous spécifiez PORT_REMAP_INBOUND mais ne spécifiez pas de valeur pour PORT_REMAP, les communications sortantes pour le port restent inchangées.

*IMPORTANT* : Ne remappez pas les ports que vous prévoyez d’utiliser pour configurer les points de terminaison de l’équilibreur de charge.

Le format utilisé est : `_network type_/_protocol_/_remapped port_/_default port used by grid node_` , où `_network type_` est une grille, un administrateur ou un client, et `_protocol_` est tcp ou udp.

Exemple: `PORT_REMAP_INBOUND = grid/tcp/3022/22`

Vous pouvez également remapper plusieurs ports entrants à l’aide d’une liste séparée par des virgules.

Exemple: `PORT_REMAP_INBOUND = grid/tcp/3022/22, admin/tcp/3022/22`
 a| 
Facultatif

|===