---
permalink: admin/administering-storagegrid-system.html 
sidebar: sidebar 
keywords: administration overview 
summary: Utilisez ces instructions pour configurer et administrer un système StorageGRID . 
---
= Administrer un système StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilisez ces instructions pour configurer et administrer un système StorageGRID .

Ces instructions décrivent comment utiliser Grid Manager pour configurer des groupes et des utilisateurs, créer des comptes de locataire pour permettre aux applications clientes S3 de stocker et de récupérer des objets, configurer et gérer les réseaux StorageGRID , configurer AutoSupport, gérer les paramètres des nœuds, etc.

Ces instructions sont destinées au personnel technique qui configurera, administrera et prendra en charge un système StorageGRID après son installation.

.Avant de commencer
* Vous avez une compréhension générale du système StorageGRID .
* Vous avez une connaissance assez détaillée des shells de commande Linux, de la mise en réseau et de la configuration du matériel du serveur.

