---
permalink: admin/admin-group-permissions.html 
sidebar: sidebar 
keywords: admin group permissions 
summary: 'Lors de la création de groupes d"utilisateurs administrateurs, vous sélectionnez une ou plusieurs autorisations pour contrôler l"accès à des fonctionnalités spécifiques du gestionnaire de grille.  Vous pouvez ensuite affecter chaque utilisateur à un ou plusieurs de ces groupes d’administrateurs pour déterminer les tâches que cet utilisateur peut effectuer.' 
---
= Autorisations du groupe d'administrateurs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lors de la création de groupes d'utilisateurs administrateurs, vous sélectionnez une ou plusieurs autorisations pour contrôler l'accès à des fonctionnalités spécifiques du gestionnaire de grille.  Vous pouvez ensuite affecter chaque utilisateur à un ou plusieurs de ces groupes d’administrateurs pour déterminer les tâches que cet utilisateur peut effectuer.

Vous devez attribuer au moins une autorisation à chaque groupe ; sinon, les utilisateurs appartenant à ce groupe ne pourront pas se connecter au gestionnaire de grille ou à l’API de gestion de grille.

Par défaut, tout utilisateur appartenant à un groupe disposant d’au moins une autorisation peut effectuer les tâches suivantes :

* Sign in au gestionnaire de grille
* Afficher le tableau de bord
* Afficher les pages Nœuds
* Afficher les alertes actuelles et résolues
* Modifier leur propre mot de passe (utilisateurs locaux uniquement)
* Consultez certaines informations fournies sur les pages Configuration et Maintenance




== Interaction entre les autorisations et le mode d'accès

Pour toutes les autorisations, le paramètre *Mode d'accès* du groupe détermine si les utilisateurs peuvent modifier les paramètres et effectuer des opérations ou s'ils peuvent uniquement afficher les paramètres et fonctionnalités associés.  Si un utilisateur appartient à plusieurs groupes et qu'un groupe est défini sur *Lecture seule*, l'utilisateur aura un accès en lecture seule à tous les paramètres et fonctionnalités sélectionnés.

Les sections suivantes décrivent les autorisations que vous pouvez attribuer lors de la création ou de la modification d’un groupe d’administrateurs.  Toute fonctionnalité non explicitement mentionnée nécessite l'autorisation *Accès root*.



== Accès root

Cette autorisation donne accès à toutes les fonctionnalités d’administration du réseau.



== Modifier le mot de passe root du locataire

Cette autorisation donne accès à l'option *Modifier le mot de passe root* sur la page Locataires, vous permettant de contrôler qui peut modifier le mot de passe de l'utilisateur root local du locataire.  Cette autorisation est également utilisée pour migrer les clés S3 lorsque la fonctionnalité d’importation de clés S3 est activée.  Les utilisateurs qui ne disposent pas de cette autorisation ne peuvent pas voir l'option *Modifier le mot de passe root*.


NOTE: Pour accorder l'accès à la page Locataires, qui contient l'option *Modifier le mot de passe root*, attribuez également l'autorisation *Comptes locataires*.



== Configuration de la page de topologie de grille

Cette autorisation donne accès aux onglets de configuration sur la page *SUPPORT* > *Outils* > *Topologie de grille*.


NOTE: La page Topologie de grille est obsolète et sera supprimée dans une prochaine version.



== ILM

Cette autorisation donne accès aux options de menu *ILM* suivantes :

* Règles
* Politiques
* Balises de politique
* Piscines de stockage
* Niveaux de stockage
* Régions
* Recherche de métadonnées d'objet



NOTE: Les utilisateurs doivent disposer des autorisations *Autre configuration de grille* et *Configuration de la page de topologie de grille* pour gérer les niveaux de stockage.



== Entretien

Les utilisateurs doivent disposer de l'autorisation Maintenance pour utiliser ces options :

* *CONFIGURATION* > *Contrôle d'accès*:
+
** Mots de passe de la grille


* *CONFIGURATION* > *Réseau*:
+
** Noms de domaine de point de terminaison S3


* *ENTRETIEN* > *Tâches*:
+
** Déclassement
** Expansion
** Vérification de l'existence de l'objet
** Récupération


* *ENTRETIEN* > *Système* :
+
** Paquet de relance
** Mise à jour du logiciel


* *SUPPORT* > *Outils*:
+
** Journaux




Les utilisateurs qui ne disposent pas de l'autorisation Maintenance peuvent afficher, mais pas modifier, ces pages :

* *ENTRETIEN* > *Réseau* :
+
** serveurs DNS
** Réseau de grille
** Serveurs NTP


* *ENTRETIEN* > *Système* :
+
** Licence


* *CONFIGURATION* > *Réseau*:
+
** Noms de domaine de point de terminaison S3


* *CONFIGURATION* > *Sécurité*:
+
** Certificats


* *CONFIGURATION* > *Surveillance*:
+
** Serveur d'audit et syslog






== Gérer les alertes

Cette autorisation donne accès aux options de gestion des alertes.  Les utilisateurs doivent disposer de cette autorisation pour gérer les silences, les notifications d’alerte et les règles d’alerte.



== Requête de métriques

Cette autorisation donne accès à :

* *SUPPORT* > *Outils* > Page *Métriques*
* Requêtes de métriques Prometheus personnalisées à l'aide de la section *Metrics* de l'API Grid Management
* Cartes de tableau de bord Grid Manager contenant des métriques




== Recherche de métadonnées d'objet

Cette autorisation donne accès à la page *ILM* > *Recherche de métadonnées d'objet*.



== Autre configuration de grille

Cette autorisation donne accès à des options de configuration de grille supplémentaires.


TIP: Pour voir ces options supplémentaires, les utilisateurs doivent également disposer de l'autorisation *Configuration de la page de topologie de grille*.

* *ILM*:
+
** Niveaux de stockage


* *CONFIGURATION* > *Système*:
* *SOUTIEN* > *Autre* :
+
** Coût du lien






== Administrateur d'appareils de stockage

Cette autorisation prévoit :

* Accès au gestionnaire de système SANtricity E-Series sur les appliances de stockage via Grid Manager.
* La possibilité d’effectuer des tâches de dépannage et de maintenance sur l’onglet Gérer les lecteurs pour les appareils qui prennent en charge ces opérations.




== Comptes locataires

Cette autorisation donne la possibilité de :

* Accédez à la page Locataires, où vous pouvez créer, modifier et supprimer des comptes locataires
* Afficher les politiques de classification du trafic existantes
* Afficher les cartes du tableau de bord Grid Manager qui contiennent les détails du locataire

