---
permalink: admin/change-ssh-access-passwords.html 
sidebar: sidebar 
keywords: ssh access keys, change ssh access keys 
summary: La modification des mots de passe d’accès SSH pour les nœuds d’administration met également à jour les ensembles uniques de clés SSH internes pour chaque nœud de la grille.  Le nœud d’administration principal utilise ces clés SSH pour accéder aux nœuds à l’aide d’une authentification sécurisée et sans mot de passe. 
---
= Modifier les mots de passe d'accès SSH pour les nœuds d'administration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La modification des mots de passe d’accès SSH pour les nœuds d’administration met également à jour les ensembles uniques de clés SSH internes pour chaque nœud de la grille.  Le nœud d’administration principal utilise ces clés SSH pour accéder aux nœuds à l’aide d’une authentification sécurisée et sans mot de passe.

Utilisez une clé SSH pour vous connecter à un nœud en tant que `admin` ou à l'utilisateur root sur une connexion VM ou console physique.

.Avant de commencer
* Vous êtes connecté au Grid Manager à l'aide d'unlink:../admin/web-browser-requirements.html["navigateur Web pris en charge"] .
* Vous avez lelink:admin-group-permissions.html["Autorisation d'accès de maintenance ou root"] .
* Vous disposez de la phrase secrète de provisionnement actuelle.


.À propos de cette tâche
Les nouveaux mots de passe d'accès pour les nœuds d'administration et les nouvelles clés internes pour chaque nœud sont stockés dans le `Passwords.txt` fichier dans le package de récupération. Les clés sont répertoriées dans la colonne Mot de passe de ce fichier.

Il existe des mots de passe d'accès SSH distincts pour les clés SSH utilisées pour la communication entre les nœuds.  Ceux-ci ne sont pas modifiés par cette procédure.



== Accéder à l'assistant

.Étapes
. Sélectionnez *CONFIGURATION* > *Contrôle d'accès* > *Mots de passe de la grille*.
. Sous *Modifier les clés SSH*, sélectionnez *Effectuer une modification*.




== [[download-current]]Télécharger le package de récupération actuel

Avant de modifier les clés d’accès SSH, téléchargez le package de récupération actuel. Vous pouvez utiliser les clés de ce fichier si le processus de changement de clé échoue pour un nœud.

.Étapes
. Saisissez la phrase secrète de provisionnement de votre grille.
. Sélectionnez *Télécharger le package de récupération*.
. Copier le fichier du package de récupération(`.zip` ) vers deux endroits sûrs, sécurisés et séparés.
+

CAUTION: Le fichier du package de récupération doit être sécurisé car il contient des clés de chiffrement et des mots de passe qui peuvent être utilisés pour obtenir des données à partir du système StorageGRID .

. Sélectionnez *Continuer*.
. Lorsque la boîte de dialogue de confirmation apparaît, sélectionnez *Oui* si vous êtes prêt à commencer à modifier les clés d'accès SSH.
+

CAUTION: Vous ne pouvez pas annuler ce processus une fois qu'il a commencé.





== Modifier les clés d'accès SSH

Lorsque le processus de modification des clés d’accès SSH démarre, un nouveau package de récupération est généré qui inclut les nouvelles clés. Ensuite, les clés sont mises à jour sur chaque nœud.

.Étapes
. Attendez que le nouveau package de récupération soit généré, ce qui peut prendre quelques minutes.
. Lorsque le bouton Télécharger un nouveau package de récupération est activé, sélectionnez *Télécharger un nouveau package de récupération* et enregistrez le nouveau fichier de package de récupération(`.zip` ) vers deux endroits sûrs, sécurisés et séparés.
. Une fois le téléchargement terminé :
+
.. Ouvrez le `.zip` déposer.
.. Confirmez que vous pouvez accéder au contenu, y compris le `Passwords.txt` fichier, qui contient les nouvelles clés d'accès SSH.
.. Copiez le nouveau fichier du package de récupération(`.zip` ) vers deux endroits sûrs, sécurisés et séparés.
+

CAUTION: N'écrasez pas l'ancien package de récupération.

+
Le fichier du package de récupération doit être sécurisé car il contient des clés de chiffrement et des mots de passe qui peuvent être utilisés pour obtenir des données à partir du système StorageGRID .



. Attendez que les clés soient mises à jour sur chaque nœud, ce qui peut prendre quelques minutes.
+
Si les clés sont modifiées pour tous les nœuds, une bannière de réussite verte apparaît.

+
En cas d'erreur lors du processus de mise à jour, un message de bannière répertorie le nombre de nœuds dont les clés n'ont pas pu être modifiées.  Le système réessaiera automatiquement le processus sur tout nœud dont la clé n'a pas été modifiée.  Si le processus se termine avec certains nœuds n'ayant toujours pas de clé modifiée, le bouton *Réessayer* apparaît.

+
Si la mise à jour de la clé a échoué pour un ou plusieurs nœuds :

+
.. Consultez les messages d’erreur répertoriés dans le tableau.
.. Résoudre les problèmes.
.. Sélectionnez *Réessayer*.
+
La nouvelle tentative modifie uniquement les clés d'accès SSH sur les nœuds qui ont échoué lors des tentatives de modification de clé précédentes.



. Une fois les clés d'accès SSH modifiées pour tous les nœuds, supprimez le<<download-current,premier package de récupération que vous avez téléchargé>> .
. Vous pouvez également sélectionner *MAINTENANCE* > *Système* > *Pack de récupération* pour télécharger une copie supplémentaire du nouveau package de récupération.

