---
permalink: admin/changing-your-password.html 
sidebar: sidebar 
keywords: change password, grid manager password 
summary: Si vous êtes un utilisateur local du Grid Manager, vous pouvez modifier votre propre mot de passe. 
---
= Changez votre mot de passe
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous êtes un utilisateur local du Grid Manager, vous pouvez modifier votre propre mot de passe.

.Avant de commencer
Vous êtes connecté au Grid Manager à l'aide d'unlink:../admin/web-browser-requirements.html["navigateur Web pris en charge"] .

.À propos de cette tâche
Si vous vous connectez à StorageGRID en tant qu'utilisateur fédéré ou si l'authentification unique (SSO) est activée, vous ne pouvez pas modifier votre mot de passe dans Grid Manager.  Au lieu de cela, vous devez modifier votre mot de passe dans la source d’identité externe, par exemple, Active Directory ou OpenLDAP.

.Étapes
. Dans l'en-tête du Gestionnaire de grille, sélectionnez *_votre nom_* > *Modifier le mot de passe*.
. Entrez votre mot de passe actuel.
. Tapez un nouveau mot de passe.
+
Votre mot de passe doit contenir au moins 8 et pas plus de 32 caractères.  Les mots de passe sont sensibles à la casse.

. Entrez à nouveau le nouveau mot de passe.
. Sélectionnez *Enregistrer*.

