---
permalink: admin/change-node-console-password.html 
sidebar: sidebar 
keywords: node console password, console password, change password, password 
summary: Chaque nœud de votre grille possède un mot de passe de console de nœud unique, dont vous avez besoin pour vous connecter au nœud.  Suivez ces étapes pour modifier le mot de passe de la console de nœud pour chaque nœud de votre grille.  Les mots de passe sont stockés dans le package de récupération. 
---
= Modifier les mots de passe de la console du nœud
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Chaque nœud de votre grille possède un mot de passe de console de nœud unique, dont vous avez besoin pour vous connecter au nœud.  Suivez ces étapes pour modifier chaque mot de passe de console de nœud unique pour chaque nœud de votre grille.

.Avant de commencer
* Vous êtes connecté au Grid Manager à l'aide d'unlink:../admin/web-browser-requirements.html["navigateur Web pris en charge"] .
* Vous avez lelink:admin-group-permissions.html["Autorisation d'accès de maintenance ou root"] .
* Vous disposez de la phrase secrète de provisionnement actuelle.


.À propos de cette tâche
Utilisez le mot de passe de la console du nœud pour vous connecter à un nœud en tant qu'« administrateur » à l'aide de SSH ou en tant qu'utilisateur root sur une connexion VM/console physique.  Le processus de changement de mot de passe de la console du nœud crée de nouveaux mots de passe pour chaque nœud de votre grille et stocke les mots de passe dans un fichier mis à jour. `Passwords.txt` fichier dans le package de récupération.  Les mots de passe sont répertoriés dans la colonne Mot de passe du fichier Passwords.txt.


NOTE: Il existe des mots de passe d'accès SSH distincts pour les clés SSH utilisées pour la communication entre les nœuds.  Les mots de passe d'accès SSH ne sont pas modifiés par cette procédure.



== Accéder à l'assistant

.Étapes
. Sélectionnez *CONFIGURATION* > *Contrôle d'accès* > *Mots de passe de la grille*.
. Sous *Modifier les mots de passe de la console du nœud*, sélectionnez *Effectuer une modification*.




== Saisissez la phrase secrète de provisionnement

.Étapes
. Saisissez la phrase secrète de provisionnement de votre grille.
. Sélectionnez *Continuer*.




== [[download-current]]Télécharger le package de récupération actuel

Avant de modifier les mots de passe de la console du nœud, téléchargez le package de récupération actuel. Vous pouvez utiliser les mots de passe de ce fichier si le processus de changement de mot de passe échoue pour un nœud.

.Étapes
. Sélectionnez *Télécharger le package de récupération*.
. Copier le fichier du package de récupération(`.zip` ) vers deux endroits sûrs, sécurisés et séparés.
+

CAUTION: Le fichier du package de récupération doit être sécurisé car il contient des clés de chiffrement et des mots de passe qui peuvent être utilisés pour obtenir des données à partir du système StorageGRID .

. Sélectionnez *Continuer*.
. Lorsque la boîte de dialogue de confirmation s'affiche, sélectionnez *Oui* si vous êtes prêt à commencer à modifier les mots de passe de la console du nœud.
+
Vous ne pouvez pas annuler ce processus une fois qu'il a commencé.





== Modifier les mots de passe de la console du nœud

Lorsque le processus de mot de passe de la console du nœud démarre, un nouveau package de récupération est généré qui inclut les nouveaux mots de passe.  Ensuite, les mots de passe sont mis à jour sur chaque nœud.

.Étapes
. Attendez que le nouveau package de récupération soit généré, ce qui peut prendre quelques minutes.
. Sélectionnez *Télécharger un nouveau package de récupération*.
. Une fois le téléchargement terminé :
+
.. Ouvrez le `.zip` déposer.
.. Confirmez que vous pouvez accéder au contenu, y compris le `Passwords.txt` fichier, qui contient les nouveaux mots de passe de la console du nœud.
.. Copiez le nouveau fichier du package de récupération(`.zip` ) vers deux endroits sûrs, sécurisés et séparés.
+

CAUTION: N'écrasez pas l'ancien package de récupération.

+
Le fichier du package de récupération doit être sécurisé car il contient des clés de chiffrement et des mots de passe qui peuvent être utilisés pour obtenir des données à partir du système StorageGRID .



. Cochez la case pour indiquer que vous avez téléchargé le nouveau package de récupération et vérifié le contenu.
. Sélectionnez *Modifier les mots de passe de la console du nœud* et attendez que tous les nœuds soient mis à jour avec les nouveaux mots de passe.  Cela peut prendre quelques minutes.
+
Si les mots de passe sont modifiés pour tous les nœuds, une bannière de réussite verte apparaît.  Passez à l'étape suivante.

+
S'il y a une erreur pendant le processus de mise à jour, un message de bannière répertorie le nombre de nœuds dont le mot de passe n'a pas pu être modifié. Le système réessaiera automatiquement le processus sur tout nœud dont le mot de passe n'a pas été modifié. Si le processus se termine et que certains nœuds n'ont toujours pas de mot de passe modifié, le bouton *Réessayer* apparaît.

+
Si la mise à jour du mot de passe a échoué pour un ou plusieurs nœuds :

+
.. Consultez les messages d’erreur répertoriés dans le tableau.
.. Résoudre les problèmes.
.. Sélectionnez *Réessayer*.
+

NOTE: La nouvelle tentative modifie uniquement les mots de passe de la console du nœud sur les nœuds qui ont échoué lors des tentatives de modification de mot de passe précédentes.



. Une fois les mots de passe de la console de nœud modifiés pour tous les nœuds, supprimez le<<download-current,premier package de récupération que vous avez téléchargé>> .
. Vous pouvez également utiliser le lien *Pack de récupération* pour télécharger une copie supplémentaire du nouveau package de récupération.

