---
permalink: admin/copying-storagegrid-system-ca-certificate.html 
sidebar: sidebar 
keywords: grid ca certificate, copy certificate 
summary: 'StorageGRID utilise une autorité de certification interne (CA) pour sécuriser le trafic interne.  Ce certificat ne change pas si vous téléchargez vos propres certificats.' 
---
= Copier le certificat Grid CA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID utilise une autorité de certification interne (CA) pour sécuriser le trafic interne.  Ce certificat ne change pas si vous téléchargez vos propres certificats.

.Avant de commencer
* Vous êtes connecté au Grid Manager à l'aide d'unlink:../admin/web-browser-requirements.html["navigateur Web pris en charge"] .
* Tu aslink:admin-group-permissions.html["autorisations d'accès spécifiques"] .


.À propos de cette tâche
Si un certificat de serveur personnalisé a été configuré, les applications clientes doivent vérifier le serveur à l'aide du certificat de serveur personnalisé.  Ils ne doivent pas copier le certificat CA du système StorageGRID .

.Étapes
. Sélectionnez *CONFIGURATION* > *Sécurité* > *Certificats* puis sélectionnez l'onglet *Grid CA*.
. Dans la section *Certificat PEM*, téléchargez ou copiez le certificat.
+
[role="tabbed-block"]
====
.Télécharger le fichier de certificat
--
Télécharger le certificat `.pem` déposer.

.. Sélectionnez *Télécharger le certificat*.
.. Spécifiez le nom du fichier de certificat et l’emplacement de téléchargement.  Enregistrez le fichier avec l'extension `.pem` .
+
Par exemple :  `storagegrid_certificate.pem`



--
.Copie du certificat PEM
--
Copiez le texte du certificat pour le coller ailleurs.

.. Sélectionnez *Copier le certificat PEM*.
.. Collez le certificat copié dans un éditeur de texte.
.. Enregistrez le fichier texte avec l'extension `.pem` .
+
Par exemple :  `storagegrid_certificate.pem`



--
====

