---
permalink: admin/index.html 
sidebar: sidebar 
keywords: how to administer storagegrid 
summary: Utilisez ces instructions pour configurer et administrer un système StorageGRID . 
---
= Administrer StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilisez ces instructions pour configurer et administrer un système StorageGRID .



== À propos de ces instructions

Les principales tâches de configuration et d’administration de StorageGRID vous permettent de :

* Utilisez le gestionnaire de grille pour configurer des groupes et des utilisateurs
* Créer des comptes locataires pour permettre aux applications clientes S3 de stocker et de récupérer des objets
* Configurer et gérer les réseaux StorageGRID
* Configurer AutoSupport
* Gérer les paramètres des nœuds




== Avant de commencer

* Vous avez une compréhension générale du système StorageGRID .
* Vous avez une connaissance assez détaillée des shells de commande Linux, de la mise en réseau et de la configuration du matériel du serveur.

