---
permalink: admin/managing-tenants.html 
sidebar: sidebar 
keywords: manage tenants, tenant account, what is a tenant 
summary: 'Un compte locataire vous permet d"utiliser l"API REST Simple Storage Service (S3) pour stocker et récupérer des objets dans un système StorageGRID .' 
---
= Que sont les comptes locataires ?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un compte locataire vous permet d'utiliser l'API REST Simple Storage Service (S3) pour stocker et récupérer des objets dans un système StorageGRID .


TIP: Les détails Swift ont été supprimés de cette version du site de documentation. Voir https://docs.netapp.com/us-en/storagegrid-118/admin/managing-tenants.html["StorageGRID 11.8 : Gérer les locataires"^] .

En tant qu'administrateur de grille, vous créez et gérez les comptes locataires que les clients S3 utilisent pour stocker et récupérer des objets.

Chaque compte locataire dispose de groupes fédérés ou locaux, d'utilisateurs, de compartiments S3 et d'objets.

Les comptes locataires peuvent être utilisés pour séparer les objets stockés par différentes entités.  Par exemple, plusieurs comptes locataires peuvent être utilisés pour l’un ou l’autre de ces cas d’utilisation :

* *Cas d'utilisation d'entreprise :* si vous administrez un système StorageGRID dans une application d'entreprise, vous souhaiterez peut-être séparer le stockage d'objets de la grille par les différents services de votre organisation.  Dans ce cas, vous pouvez créer des comptes locataires pour le service marketing, le service d'assistance client, le service des ressources humaines, etc.
+

NOTE: Si vous utilisez le protocole client S3, vous pouvez utiliser des buckets S3 et des stratégies de bucket pour séparer les objets entre les services d'une entreprise. Vous n’avez pas besoin d’utiliser des comptes locataires. Voir les instructions de mise en œuvrelink:../s3/bucket-and-group-access-policies.html["Buckets S3 et politiques de buckets"] pour plus d'informations.

* *Cas d'utilisation du fournisseur de services :* si vous administrez un système StorageGRID en tant que fournisseur de services, vous pouvez séparer le stockage d'objets de la grille par les différentes entités qui loueront le stockage sur votre grille.  Dans ce cas, vous créeriez des comptes locataires pour la société A, la société B, la société C, etc.


Pour plus d'informations, consultez la section link:../tenant/index.html["Utiliser un compte locataire"] .



== Comment créer un compte locataire ?

Utilisez le gestionnaire de grille pour créer un compte locataire.  Lorsque vous créez un compte locataire, vous spécifiez les informations suivantes :

* Informations de base, notamment le nom du locataire, le type de client (S3) et le quota de stockage facultatif.
* Autorisations pour le compte locataire, par exemple si le compte locataire peut utiliser les services de la plateforme S3, configurer sa propre source d'identité, utiliser S3 Select ou utiliser une connexion de fédération de grille.
* L'accès root initial pour le locataire, selon que le système StorageGRID utilise des groupes et des utilisateurs locaux, une fédération d'identité ou une authentification unique (SSO).


De plus, vous pouvez activer le paramètre de verrouillage d'objet S3 pour le système StorageGRID si les comptes de locataire S3 doivent se conformer aux exigences réglementaires.  Lorsque le verrouillage d'objet S3 est activé, tous les comptes de locataire S3 peuvent créer et gérer des compartiments conformes.



== À quoi sert Tenant Manager ?

Après avoir créé le compte locataire, les utilisateurs locataires peuvent se connecter au gestionnaire de locataires pour effectuer des tâches telles que les suivantes :

* Configurer la fédération d'identité (sauf si la source d'identité est partagée avec la grille)
* Gérer les groupes et les utilisateurs
* Utiliser la fédération de grille pour le clonage de compte et la réplication inter-grille
* Gérer les clés d'accès S3
* Créer et gérer des buckets S3
* Utiliser les services de la plateforme S3
* Utiliser S3 Select
* Surveiller l'utilisation du stockage



TIP: Bien que les utilisateurs de locataires S3 puissent créer et gérer des clés d’accès et des compartiments S3 avec Tenant Manager, ils doivent utiliser une application cliente S3 pour ingérer et gérer des objets. Voirlink:../s3/index.html["Utiliser l'API REST S3"] pour plus de détails.
