---
permalink: admin/managing-full-storage-nodes.html 
sidebar: sidebar 
keywords: storage node is full 
summary: 'À mesure que les nœuds de stockage atteignent leur capacité, vous devez étendre le système StorageGRID en ajoutant un nouveau stockage.  Trois options sont disponibles : l’ajout de volumes de stockage, l’ajout d’étagères d’extension de stockage et l’ajout de nœuds de stockage.' 
---
= Gérer des nœuds de stockage complets
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
À mesure que les nœuds de stockage atteignent leur capacité, vous devez étendre le système StorageGRID en ajoutant un nouveau stockage.  Trois options sont disponibles : l’ajout de volumes de stockage, l’ajout d’étagères d’extension de stockage et l’ajout de nœuds de stockage.



== Ajouter des volumes de stockage

Chaque nœud de stockage prend en charge un nombre maximal de volumes de stockage.  Le maximum défini varie selon la plateforme.  Si un nœud de stockage contient moins de volumes de stockage que le nombre maximal, vous pouvez ajouter des volumes pour augmenter sa capacité. Voir les instructions pourlink:../expand/index.html["extension d'un système StorageGRID"] .



== Ajouter des étagères d'extension de stockage

Certains nœuds de stockage d'appliance StorageGRID , tels que le SG6060 ou le SG6160, peuvent prendre en charge des étagères de stockage supplémentaires.  Si vous disposez d'appliances StorageGRID avec des capacités d'extension qui n'ont pas déjà été étendues à leur capacité maximale, vous pouvez ajouter des étagères de stockage pour augmenter la capacité. Voir les instructions pourlink:../expand/index.html["extension d'un système StorageGRID"] .



== Ajouter des nœuds de stockage

Vous pouvez augmenter la capacité de stockage en ajoutant des nœuds de stockage.  Une attention particulière doit être portée aux règles ILM actuellement actives et aux exigences de capacité lors de l'ajout de stockage. Voir les instructions pourlink:../expand/index.html["extension d'un système StorageGRID"] .
