---
permalink: admin/summary-ip-addresses-and-ports-for-client-connections.html 
sidebar: sidebar 
keywords: ip addresses for client, how to connect to storagegrid, ports, vip 
summary: 'Pour stocker ou récupérer des objets, les applications clientes S3 se connectent au service Load Balancer, inclus sur tous les nœuds d"administration et les nœuds de passerelle, ou au service Local Distribution Router (LDR), inclus sur tous les nœuds de stockage.' 
---
= Résumé : Adresses IP et ports pour les connexions client
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour stocker ou récupérer des objets, les applications clientes S3 se connectent au service Load Balancer, inclus sur tous les nœuds d'administration et les nœuds de passerelle, ou au service Local Distribution Router (LDR), inclus sur tous les nœuds de stockage.

Les applications clientes peuvent se connecter à StorageGRID à l’aide de l’adresse IP d’un nœud de grille et du numéro de port du service sur ce nœud.  En option, vous pouvez créer des groupes haute disponibilité (HA) de nœuds d'équilibrage de charge pour fournir des connexions hautement disponibles qui utilisent des adresses IP virtuelles (VIP).  Si vous souhaitez vous connecter à StorageGRID à l'aide d'un nom de domaine complet (FQDN) au lieu d'une adresse IP ou VIP, vous pouvez configurer des entrées DNS.

Ce tableau résume les différentes manières dont les clients peuvent se connecter à StorageGRID ainsi que les adresses IP et les ports utilisés pour chaque type de connexion.  Si vous avez déjà créé des points de terminaison d'équilibrage de charge et des groupes de haute disponibilité (HA), consultez<<Où trouver les adresses IP>> pour localiser ces valeurs dans le gestionnaire de grille.

[cols="1a,1a,1a,1a"]
|===
| Où la connexion est établie | Service auquel le client se connecte | adresse IP | Port 


 a| 
groupe HA
 a| 
Équilibreur de charge
 a| 
Adresse IP virtuelle d'un groupe HA
 a| 
Port attribué au point de terminaison de l'équilibreur de charge



 a| 
Nœud d'administration
 a| 
Équilibreur de charge
 a| 
Adresse IP du nœud d'administration
 a| 
Port attribué au point de terminaison de l'équilibreur de charge



 a| 
Nœud de passerelle
 a| 
Équilibreur de charge
 a| 
Adresse IP du nœud de passerelle
 a| 
Port attribué au point de terminaison de l'équilibreur de charge



 a| 
Nœud de stockage
 a| 
LDR
 a| 
Adresse IP du nœud de stockage
 a| 
Ports S3 par défaut :

* HTTPS : 18082
* HTTP : 18084


|===


== Exemples d'URL

Pour connecter une application cliente au point de terminaison de l'équilibreur de charge d'un groupe HA de nœuds de passerelle, utilisez une URL structurée comme indiqué ci-dessous :

`https://_VIP-of-HA-group:LB-endpoint-port_`

Par exemple, si l'adresse IP virtuelle du groupe HA est 192.0.2.5 et que le numéro de port du point de terminaison de l'équilibreur de charge est 10443, une application peut utiliser l'URL suivante pour se connecter à StorageGRID:

`\https://192.0.2.5:10443`



== Où trouver les adresses IP

. Sign in au Grid Manager à l'aide d'unlink:../admin/web-browser-requirements.html["navigateur Web pris en charge"] .
. Pour trouver l’adresse IP d’un nœud de grille :
+
.. Sélectionnez *NODES*.
.. Sélectionnez le nœud d’administration, le nœud de passerelle ou le nœud de stockage auquel vous souhaitez vous connecter.
.. Sélectionnez l’onglet *Aperçu*.
.. Dans la section Informations sur le nœud, notez les adresses IP du nœud.
.. Sélectionnez *Afficher plus* pour afficher les adresses IPv6 et les mappages d’interface.
+
Vous pouvez établir des connexions à partir d'applications clientes vers n'importe laquelle des adresses IP de la liste :

+
*** *eth0:* Réseau de grille
*** *eth1:* Réseau administrateur (facultatif)
*** *eth2:* Réseau client (facultatif)
+

NOTE: Si vous visualisez un nœud d’administration ou un nœud de passerelle et qu’il s’agit du nœud actif dans un groupe haute disponibilité, l’adresse IP virtuelle du groupe HA est affichée sur eth2.





. Pour trouver l’adresse IP virtuelle d’un groupe de haute disponibilité :
+
.. Sélectionnez *CONFIGURATION* > *Réseau* > *Groupes de haute disponibilité*.
.. Dans le tableau, notez l’adresse IP virtuelle du groupe HA.


. Pour trouver le numéro de port d’un point de terminaison d’équilibreur de charge :
+
.. Sélectionnez *CONFIGURATION* > *Réseau* > *Points de terminaison de l'équilibreur de charge*.
.. Notez le numéro de port du point de terminaison que vous souhaitez utiliser.
+

NOTE: Si le numéro de port est 80 ou 443, le point de terminaison est configuré uniquement sur les nœuds de passerelle, car ces ports sont réservés sur les nœuds d'administration.  Tous les autres ports sont configurés sur les nœuds de passerelle et les nœuds d’administration.

.. Sélectionnez le nom du point de terminaison dans le tableau.
.. Confirmez que le *Type de client* (S3) correspond à l’application cliente qui utilisera le point de terminaison.



