---
permalink: s3/changes-to-s3-rest-api-support.html 
sidebar: sidebar 
keywords: s3 rest api support changes 
summary: 'Vous devez être conscient des modifications apportées à la prise en charge de l"API REST S3 par le système StorageGRID .' 
---
= Modifications apportées à la prise en charge de l'API REST S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez être conscient des modifications apportées à la prise en charge de l'API REST S3 par le système StorageGRID .

[cols="1a,4a"]
|===
| Libérer | Commentaires 


 a| 
11,8
 a| 
* Prise en charge ajoutée pour `ExpiredObjectDeleteMarker` dans une opération PutBucketLifecycleConfiguration, qui supprime les marqueurs de suppression d'objets expirés.
* Ajout du support pour le `s3:ExistingObjectTag/<tag-key>` clé de condition de politique, qui exige que les objets existants aient la clé et la valeur de balise spécifiques.
* Ajout du support pour le `s3:RequestObjectTag/<tag-key>` clé de condition de politique, qui nécessite une balise et une valeur de clé spécifiques lorsque la demande d'objet inclut le balisage.




 a| 
11,7
 a| 
* Ajout de la prise en charge de l'utilisation du mode GOUVERNANCE avec S3 Object Lock.
* Ajout de la prise en charge spécifique à StorageGRID `x-ntap-sg-cgr-replication-status` en-tête de réponse pour les requêtes GetObject et HeadObject.  Cet en-tête fournit l'état de réplication d'un objet pour la réplication inter-grille.
* Les requêtes SelectObjectContent prennent désormais en charge les objets Parquet.




 a| 
11,6
 a| 
* Ajout de la prise en charge de l'utilisation du `partNumber` paramètre de requête dans les requêtes GetObject et HeadObject.
* Ajout de la prise en charge d'un mode de conservation par défaut et d'une période de conservation par défaut au niveau du bucket pour S3 Object Lock.
* Ajout du support pour le `s3:object-lock-remaining-retention-days` clé de condition de politique pour définir la plage de périodes de conservation autorisées pour vos objets.
* La taille maximale _recommandée_ pour une seule opération PutObject a été modifiée à 5 Gio (5 368 709 120 octets).  Si vous avez des objets dont la taille est supérieure à 5 Gio, utilisez plutôt le téléchargement en plusieurs parties.




 a| 
11,5
 a| 
* Prise en charge ajoutée pour la gestion du chiffrement du bucket.
* Ajout de la prise en charge du verrouillage d'objet S3 et des demandes de conformité héritées obsolètes.
* Ajout de la prise en charge de l'utilisation de DeleteObjects sur les buckets versionnés.
* Le `Content-MD5` l'en-tête de requête est désormais correctement pris en charge.




 a| 
11,4
 a| 
* Prise en charge ajoutée pour DeleteBucketTagging, GetBucketTagging et PutBucketTagging.  Les balises d'allocation des coûts ne sont pas prises en charge.
* Pour les buckets créés dans StorageGRID 11.4, la restriction des noms de clés d'objet pour respecter les meilleures pratiques en matière de performances n'est plus nécessaire.
* Ajout de la prise en charge des notifications de bucket sur le `s3:ObjectRestore:Post` type d'événement.
* Les limites de taille AWS pour les pièces en plusieurs parties sont désormais appliquées.  Chaque partie d'un téléchargement en plusieurs parties doit être comprise entre 5 Mio et 5 Gio.  La dernière partie peut être inférieure à 5 Mio.
* Ajout de la prise en charge de TLS 1.3




 a| 
11,3
 a| 
* Ajout de la prise en charge du chiffrement côté serveur des données d'objet avec des clés fournies par le client (SSE-C).
* Ajout de la prise en charge des opérations DeleteBucketLifecycle, GetBucketLifecycleConfiguration et PutBucketLifecycleConfiguration (action d'expiration uniquement) et de la `x-amz-expiration` en-tête de réponse.
* Mise à jour de PutObject, CopyObject et MultipartUpload pour décrire l’impact des règles ILM qui utilisent le placement synchrone lors de l’ingestion.
* Les chiffrements TLS 1.1 ne sont plus pris en charge.




 a| 
11,2
 a| 
Prise en charge ajoutée pour RestoreObject pour une utilisation avec les pools de stockage cloud.  Ajout de la prise en charge de l'utilisation de la syntaxe AWS pour l'ARN, les clés de condition de stratégie et les variables de stratégie dans les stratégies de groupe et de compartiment.  Les stratégies de groupe et de compartiment existantes qui utilisent la syntaxe StorageGRID continueront d'être prises en charge.

*Remarque :* les utilisations d’ARN/URN dans d’autres configurations JSON/XML, y compris celles utilisées dans les fonctionnalités StorageGRID personnalisées, n’ont pas changé.



 a| 
11,1
 a| 
Ajout de la prise en charge du partage de ressources inter-origines (CORS), du HTTP pour les connexions client S3 aux nœuds de grille et des paramètres de conformité sur les buckets.



 a| 
11,0
 a| 
Prise en charge ajoutée pour la configuration des services de plateforme (réplication CloudMirror, notifications et intégration de recherche Elasticsearch) pour les buckets.  La prise en charge des contraintes d'emplacement de balisage d'objets pour les buckets et la cohérence disponible ont également été ajoutées.



 a| 
10,4
 a| 
Ajout de la prise en charge des modifications d'analyse ILM apportées au contrôle de version, aux mises à jour de la page Noms de domaine de point de terminaison, aux conditions et variables dans les politiques, aux exemples de politiques et à l'autorisation PutOverwriteObject.



 a| 
10,3
 a| 
Prise en charge ajoutée pour le contrôle de version.



 a| 
10,2
 a| 
Ajout de la prise en charge des stratégies d'accès aux groupes et aux buckets, ainsi que de la copie en plusieurs parties (UploadPartCopy).



 a| 
10,1
 a| 
Prise en charge ajoutée pour le téléchargement en plusieurs parties, les demandes de type hébergé virtuellement et l'authentification v4.



 a| 
10,0
 a| 
Prise en charge initiale de l'API REST S3 par le système StorageGRID . La version actuellement prise en charge de la _Référence API du service de stockage simple_ est le 01/03/2006.

|===