---
permalink: s3/error-responses.html 
sidebar: sidebar 
keywords: error, error responses 
summary: Le système StorageGRID prend en charge toutes les réponses d’erreur standard de l’API REST S3 qui s’appliquent.  De plus, l’implémentation StorageGRID ajoute plusieurs réponses personnalisées. 
---
= Réponses d'erreur
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le système StorageGRID prend en charge toutes les réponses d’erreur standard de l’API REST S3 qui s’appliquent.  De plus, l’implémentation StorageGRID ajoute plusieurs réponses personnalisées.



== Codes d'erreur de l'API S3 pris en charge

[cols="1a,1a"]
|===
| Nom | Statut HTTP 


 a| 
Accès refusé
 a| 
403 Interdit



 a| 
BadDigest
 a| 
400 Mauvaise requête



 a| 
BucketExisteDéjà
 a| 
409 Conflit



 a| 
Seau non vide
 a| 
409 Conflit



 a| 
Corps incomplet
 a| 
400 Mauvaise requête



 a| 
Erreur interne
 a| 
Erreur interne du serveur 500



 a| 
ID de clé d'accès non valide
 a| 
403 Interdit



 a| 
Argument invalide
 a| 
400 Mauvaise requête



 a| 
Nom de bucket invalide
 a| 
400 Mauvaise requête



 a| 
État du bucket invalide
 a| 
409 Conflit



 a| 
InvalidDigest
 a| 
400 Mauvaise requête



 a| 
Erreur d'algorithme de chiffrement invalide
 a| 
400 Mauvaise requête



 a| 
Partie invalide
 a| 
400 Mauvaise requête



 a| 
Commande de pièces invalide
 a| 
400 Mauvaise requête



 a| 
Plage invalide
 a| 
416 Plage demandée non satisfaisante



 a| 
Demande invalide
 a| 
400 Mauvaise requête



 a| 
Classe de stockage invalide
 a| 
400 Mauvaise requête



 a| 
Balise invalide
 a| 
400 Mauvaise requête



 a| 
URI invalide
 a| 
400 Mauvaise requête



 a| 
Clé trop longue
 a| 
400 Mauvaise requête



 a| 
XML malformé
 a| 
400 Mauvaise requête



 a| 
Métadonnées trop volumineuses
 a| 
400 Mauvaise requête



 a| 
Méthode non autorisée
 a| 
Méthode 405 non autorisée



 a| 
Longueur du contenu manquant
 a| 
411 Longueur requise



 a| 
Erreur de corps de demande manquante
 a| 
400 Mauvaise requête



 a| 
En-tête de sécurité manquant
 a| 
400 Mauvaise requête



 a| 
Aucun seau de ce type
 a| 
404 non trouvé



 a| 
Aucune clé de ce type
 a| 
404 non trouvé



 a| 
Aucun téléchargement de ce type
 a| 
404 non trouvé



 a| 
Non implémenté
 a| 
501 non implémenté



 a| 
Politique NoSuchBucket
 a| 
404 non trouvé



 a| 
Erreur de configuration de verrouillage d'objet non trouvée
 a| 
404 non trouvé



 a| 
Précondition échouée
 a| 
412 Échec de la condition préalable



 a| 
RequestTimeTooSkewed
 a| 
403 Interdit



 a| 
Service non disponible
 a| 
Service 503 indisponible



 a| 
La signature ne correspond pas
 a| 
403 Interdit



 a| 
Trop de seaux
 a| 
400 Mauvaise requête



 a| 
La clé utilisateur doit être spécifiée
 a| 
400 Mauvaise requête

|===


== Codes d'erreur personnalisés StorageGRID

[cols="2a,2a,1a"]
|===
| Nom | Description | Statut HTTP 


 a| 
XBucketLifecycleNon autorisé
 a| 
La configuration du cycle de vie du bucket n'est pas autorisée dans un bucket conforme hérité
 a| 
400 Mauvaise requête



 a| 
Exception d'analyse de politique XBucket
 a| 
Échec de l'analyse de la politique de bucket JSON reçue.
 a| 
400 Mauvaise requête



 a| 
Conflit de conformité X
 a| 
Opération refusée en raison de paramètres de conformité hérités.
 a| 
403 Interdit



 a| 
XComplianceRéduitRedondanceInterdit
 a| 
La redondance réduite n'est pas autorisée dans le bucket conforme hérité
 a| 
400 Mauvaise requête



 a| 
XMaxBucketPolicyLengthDépassé
 a| 
Votre politique dépasse la durée maximale autorisée pour la politique de compartiment.
 a| 
400 Mauvaise requête



 a| 
En-tête de demande interne XMissing
 a| 
Il manque un en-tête d'une requête interne.
 a| 
400 Mauvaise requête



 a| 
XNoSuchBucketCompliance
 a| 
La conformité héritée n'est pas activée pour le bucket spécifié.
 a| 
404 non trouvé



 a| 
XNonAcceptable
 a| 
La demande contient un ou plusieurs en-têtes d'acceptation qui n'ont pas pu être satisfaits.
 a| 
406 Non acceptable



 a| 
XNonImplémenté
 a| 
La demande que vous avez fournie implique une fonctionnalité qui n'est pas implémentée.
 a| 
501 non implémenté

|===