---
permalink: s3/get-bucket-consistency-request.html 
sidebar: sidebar 
keywords: S3 REST API, S3 operations, GET bucket consistency 
summary: La demande de cohérence GET Bucket vous permet de déterminer la cohérence appliquée à un bucket particulier. 
---
= Cohérence du bucket GET
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La demande de cohérence GET Bucket vous permet de déterminer la cohérence appliquée à un bucket particulier.

La cohérence par défaut est définie pour garantir la lecture après écriture des objets nouvellement créés.

Vous devez disposer de l'autorisation s3:GetBucketConsistency ou être root du compte pour terminer cette opération.



== Exemple de demande

[listing, subs="specialcharacters,quotes"]
----
GET /bucket?x-ntap-sg-consistency HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----


== Réponse

Dans la réponse XML, `<Consistency>` renverra l'une des valeurs suivantes :

[cols="1a,2a"]
|===
| Cohérence | Description 


 a| 
tous
 a| 
Tous les nœuds reçoivent les données immédiatement, sinon la demande échouera.



 a| 
fort-mondial
 a| 
Garantit la cohérence de lecture après écriture pour toutes les demandes client sur tous les sites.



 a| 
site fort
 a| 
Garantit la cohérence de lecture après écriture pour toutes les demandes client au sein d'un site.



 a| 
lecture après nouvelle écriture
 a| 
(Par défaut) Fournit une cohérence de lecture après écriture pour les nouveaux objets et une cohérence éventuelle pour les mises à jour d'objets.  Offre des garanties de haute disponibilité et de protection des données.  Recommandé dans la plupart des cas.



 a| 
disponible
 a| 
Assure une cohérence éventuelle pour les nouveaux objets et les mises à jour d'objets.  Pour les buckets S3, utilisez-les uniquement si nécessaire (par exemple, pour un bucket contenant des valeurs de journal rarement lues ou pour des opérations HEAD ou GET sur des clés qui n'existent pas).  Non pris en charge pour les buckets S3 FabricPool .

|===


== Exemple de réponse

[listing]
----
HTTP/1.1 200 OK
Date: Fri, 18 Sep 2020 01:02:18 GMT
Connection: CLOSE
Server: StorageGRID/11.5.0
x-amz-request-id: 12345
Content-Length: 127
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8"?>
<Consistency xmlns="http://s3.storagegrid.com/doc/2015-02-01/">read-after-new-write</Consistency>
----
.Informations connexes
link:consistency-controls.html["Valeurs de cohérence"]
