---
permalink: s3/get-storage-usage-request.html 
sidebar: sidebar 
keywords: S3 REST API, S3 operations, GET storage usage request 
summary: La demande GET Storage Usage vous indique la quantité totale de stockage utilisée par un compte et pour chaque bucket associé au compte. 
---
= Demande d'utilisation du stockage GET
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La demande GET Storage Usage vous indique la quantité totale de stockage utilisée par un compte et pour chaque bucket associé au compte.

La quantité de stockage utilisée par un compte et ses buckets peut être obtenue par une requête ListBuckets modifiée avec le `x-ntap-sg-usage` paramètre de requête.  L'utilisation du stockage du bucket est suivie séparément des requêtes PUT et DELETE traitées par le système.  Il peut y avoir un certain délai avant que les valeurs d'utilisation correspondent aux valeurs attendues en fonction du traitement des demandes, en particulier si le système est soumis à une charge importante.

Par défaut, StorageGRID tente de récupérer les informations d’utilisation à l’aide d’une cohérence globale forte.  Si une cohérence globale forte ne peut pas être obtenue, StorageGRID tente de récupérer les informations d'utilisation avec une cohérence de site forte.

Vous devez disposer de l'autorisation s3:ListAllMyBuckets ou être root du compte pour terminer cette opération.



== Exemple de demande

[listing, subs="specialcharacters,quotes"]
----
GET /?x-ntap-sg-usage HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----


== Exemple de réponse

Cet exemple montre un compte qui comporte quatre objets et 12 octets de données dans deux compartiments.  Chaque compartiment contient deux objets et six octets de données.

[listing]
----
HTTP/1.1 200 OK
Date: Sat, 29 Nov 2015 00:49:05 GMT
Connection: KEEP-ALIVE
Server: StorageGRID/10.2.0
x-amz-request-id: 727237123
Content-Length: 427
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8"?>
<UsageResult xmlns="http://s3.storagegrid.com/doc/2015-02-01">
<CalculationTime>2014-11-19T05:30:11.000000Z</CalculationTime>
<ObjectCount>4</ObjectCount>
<DataBytes>12</DataBytes>
<Buckets>
<Bucket>
<Name>bucket1</Name>
<ObjectCount>2</ObjectCount>
<DataBytes>6</DataBytes>
</Bucket>
<Bucket>
<Name>bucket2</Name>
<ObjectCount>2</ObjectCount>
<DataBytes>6</DataBytes>
</Bucket>
</Buckets>
</UsageResult>
----


== Gestion des versions

Chaque version d'objet stockée contribuera à la `ObjectCount` et `DataBytes` valeurs dans la réponse.  Les marqueurs de suppression ne sont pas ajoutés au `ObjectCount` total.

.Informations connexes
link:consistency-controls.html["Valeurs de cohérence"]
