---
permalink: s3/index.html 
sidebar: sidebar 
keywords: about s3, s3 rest api, s3 overview 
summary: 'StorageGRID prend en charge l"API Simple Storage Service (S3), qui est implémentée sous la forme d"un ensemble de services Web Representational State Transfer (REST).' 
---
= Versions et mises à jour prises en charge par l'API REST S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID prend en charge l'API Simple Storage Service (S3), qui est implémentée sous la forme d'un ensemble de services Web Representational State Transfer (REST).

La prise en charge de l'API REST S3 vous permet de connecter des applications orientées services développées pour les services Web S3 avec un stockage d'objets sur site qui utilise le système StorageGRID .  Des modifications minimales sont requises dans l'utilisation actuelle des appels d'API REST S3 par une application cliente.



== Versions prises en charge

StorageGRID prend en charge les versions spécifiques suivantes de S3 et HTTP.

[cols="1a,1a"]
|===
| Article | Version 


 a| 
Spécification de l'API S3
 a| 
http://docs.aws.amazon.com/AmazonS3/latest/API/Welcome.html["Documentation Amazon Web Services (AWS) : Référence de l'API Amazon Simple Storage Service"^]



 a| 
HTTP
 a| 
1,1

Pour plus d'informations sur HTTP, consultez HTTP/1.1 (RFC 7230-35).

https://datatracker.ietf.org/doc/html/rfc2616["IETF RFC 2616 : Protocole de transfert hypertexte (HTTP/1.1)"^]

*Remarque* : StorageGRID ne prend pas en charge le pipeline HTTP/1.1.

|===


== Mises à jour de la prise en charge de l'API REST S3

[cols="1a,4a"]
|===
| Libérer | Commentaires 


 a| 
11,9
 a| 
* Ajout de la prise en charge des valeurs de somme de contrôle SHA-256 précalculées pour les requêtes suivantes et les en-têtes pris en charge.  Vous pouvez utiliser cette fonctionnalité pour vérifier l’intégrité des objets téléchargés :
+
** Téléchargement complet en plusieurs parties : `x-amz-checksum-sha256`
** Créer un téléchargement multi-parties : `x-amz-checksum-algorithm`
** Obtenir l'objet : `x-amz-checksum-mode`
** HeadObject : `x-amz-checksum-mode`
** Liste des pièces
** PutObject : `x-amz-checksum-sha256`
** TéléchargerPartie : `x-amz-checksum-sha256`


* Ajout de la possibilité pour l'administrateur de la grille de contrôler les paramètres de conservation et de conformité au niveau du locataire.  Ces paramètres affectent les paramètres de verrouillage d’objet S3.
+
** Mode de conservation par défaut du bucket et mode de conservation des objets : Gouvernance ou Conformité, si autorisé par l'administrateur de la grille.
** Période de conservation par défaut du bucket et date de conservation de l'objet : doit être inférieure ou égale à ce qui est autorisé par la période de conservation maximale définie par l'administrateur de la grille.


* Prise en charge améliorée pour `aws-chunked` encodage et streaming de contenu `x-amz-content-sha256` valeurs. Limites:
+
** Si présent, `chunk-signature` est facultatif et non validé
** Si présent, `x-amz-trailer` le contenu est ignoré






 a| 
11,8
 a| 
Mise à jour des noms des opérations S3 pour correspondre aux noms utilisés dans le http://docs.aws.amazon.com/AmazonS3/latest/API/Welcome.html["Documentation Amazon Web Services (AWS) : Référence de l'API Amazon Simple Storage Service"^] .



 a| 
11,7
 a| 
* Ajoutélink:quick-reference-support-for-aws-apis.html["Référence rapide : requêtes API S3 prises en charge"] .
* Ajout de la prise en charge de l'utilisation du mode GOUVERNANCE avec S3 Object Lock.
* Ajout de la prise en charge spécifique à StorageGRID `x-ntap-sg-cgr-replication-status` en-tête de réponse pour les requêtes GET Object et HEAD Object.  Cet en-tête fournit l'état de réplication d'un objet pour la réplication inter-grille.
* Les requêtes SelectObjectContent prennent désormais en charge les objets Parquet.




 a| 
11,6
 a| 
* Ajout de la prise en charge de l'utilisation du `partNumber` paramètre de requête dans les requêtes d'objet GET et d'objet HEAD.
* Ajout de la prise en charge d'un mode de conservation par défaut et d'une période de conservation par défaut au niveau du bucket pour S3 Object Lock.
* Ajout du support pour le `s3:object-lock-remaining-retention-days` clé de condition de politique pour définir la plage de périodes de conservation autorisées pour vos objets.
* La taille maximale _recommandée_ pour une seule opération d'objet PUT a été modifiée à 5 Gio (5 368 709 120 octets).  Si vous avez des objets dont la taille est supérieure à 5 Gio, utilisez plutôt le téléchargement en plusieurs parties.




 a| 
11,5
 a| 
* Prise en charge ajoutée pour la gestion du chiffrement du bucket.
* Ajout de la prise en charge du verrouillage d'objet S3 et des demandes de conformité héritées obsolètes.
* Ajout de la prise en charge de l'utilisation de DELETE Multiple Objects sur des buckets versionnés.
* Le `Content-MD5` l'en-tête de requête est désormais correctement pris en charge.




 a| 
11,4
 a| 
* Prise en charge ajoutée pour le balisage des buckets DELETE, GET et PUT.  Les balises d'allocation des coûts ne sont pas prises en charge.
* Pour les buckets créés dans StorageGRID 11.4, la restriction des noms de clés d'objet pour respecter les meilleures pratiques en matière de performances n'est plus nécessaire.
* Ajout de la prise en charge des notifications de bucket sur le `s3:ObjectRestore:Post` type d'événement.
* Les limites de taille AWS pour les pièces en plusieurs parties sont désormais appliquées.  Chaque partie d'un téléchargement en plusieurs parties doit être comprise entre 5 Mio et 5 Gio.  La dernière partie peut être inférieure à 5 Mio.
* Ajout de la prise en charge de TLS 1.3




 a| 
11,3
 a| 
* Ajout de la prise en charge du chiffrement côté serveur des données d'objet avec des clés fournies par le client (SSE-C).
* Prise en charge ajoutée pour les opérations de cycle de vie du bucket DELETE, GET et PUT (action d'expiration uniquement) et pour le `x-amz-expiration` en-tête de réponse.
* Objet PUT mis à jour, Objet PUT - Copie et Téléchargement en plusieurs parties pour décrire l'impact des règles ILM qui utilisent le placement synchrone lors de l'ingestion.
* Les chiffrements TLS 1.1 ne sont plus pris en charge.




 a| 
11,2
 a| 
Prise en charge ajoutée pour la restauration d'objets POST à ​​utiliser avec les pools de stockage cloud.  Ajout de la prise en charge de l'utilisation de la syntaxe AWS pour l'ARN, les clés de condition de stratégie et les variables de stratégie dans les stratégies de groupe et de compartiment.  Les stratégies de groupe et de compartiment existantes qui utilisent la syntaxe StorageGRID continueront d'être prises en charge.

*Remarque :* les utilisations d’ARN/URN dans d’autres configurations JSON/XML, y compris celles utilisées dans les fonctionnalités StorageGRID personnalisées, n’ont pas changé.



 a| 
11,1
 a| 
Ajout de la prise en charge du partage de ressources inter-origines (CORS), du HTTP pour les connexions client S3 aux nœuds de grille et des paramètres de conformité sur les buckets.



 a| 
11,0
 a| 
Prise en charge ajoutée pour la configuration des services de plateforme (réplication CloudMirror, notifications et intégration de recherche Elasticsearch) pour les buckets.  La prise en charge des contraintes d'emplacement de balisage d'objets pour les buckets et la cohérence disponible ont également été ajoutées.



 a| 
10,4
 a| 
Ajout de la prise en charge des modifications d'analyse ILM apportées au contrôle de version, aux mises à jour de la page Noms de domaine de point de terminaison, aux conditions et variables dans les politiques, aux exemples de politiques et à l'autorisation PutOverwriteObject.



 a| 
10,3
 a| 
Prise en charge ajoutée pour le contrôle de version.



 a| 
10,2
 a| 
Ajout de la prise en charge des stratégies d'accès aux groupes et aux buckets, ainsi que de la copie en plusieurs parties (Télécharger une partie - Copier).



 a| 
10,1
 a| 
Prise en charge ajoutée pour le téléchargement en plusieurs parties, les demandes de type hébergé virtuellement et l'authentification v4.



 a| 
10,0
 a| 
Prise en charge initiale de l'API REST S3 par le système StorageGRID . La version actuellement prise en charge de la _Référence API du service de stockage simple_ est le 01/03/2006.

|===