---
permalink: s3/operations-on-buckets.html 
sidebar: sidebar 
keywords: bucket, buckets, operations on buckets 
summary: Le système StorageGRID prend en charge un maximum de 5 000 buckets pour chaque compte de locataire S3. 
---
= Opérations sur les godets
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le système StorageGRID prend en charge un maximum de 5 000 buckets pour chaque compte de locataire S3.

Chaque grille peut contenir un maximum de 100 000 buckets.

Pour prendre en charge 5 000 buckets, chaque nœud de stockage de la grille doit disposer d'un minimum de 64 Go de RAM.

Les restrictions de nom de bucket suivent les restrictions régionales standard AWS US, mais vous devez les restreindre davantage aux conventions de dénomination DNS pour prendre en charge les demandes de style hébergé virtuel S3.

Pour plus d'informations, voir les éléments suivants :

* https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html["Guide de l'utilisateur d'Amazon Simple Storage Service : quotas, restrictions et limitations des buckets"^]
* link:../admin/configuring-s3-api-endpoint-domain-names.html["Configurer les noms de domaine des points de terminaison S3"]


Les opérations ListObjects (GET Bucket) et ListObjectVersions (versions d'objet GET Bucket) prennent en charge StorageGRIDlink:consistency-controls.html["valeurs de cohérence"] .

Vous pouvez vérifier si les mises à jour de l'heure du dernier accès sont activées ou désactivées pour des compartiments individuels. Voir link:get-bucket-last-access-time-request.html["Heure du dernier accès au bucket GET"] .

Le tableau suivant décrit comment StorageGRID implémente les opérations de bucket S3 REST API.  Pour effectuer l’une de ces opérations, les informations d’accès nécessaires doivent être fournies pour le compte.

[cols="1a,3a"]
|===
| Opération | Mise en œuvre 


 a| 
Créer un bucket
 a| 
Crée un nouveau bucket.  En créant le bucket, vous devenez le propriétaire du bucket.

* Les noms de bucket doivent respecter les règles suivantes :
+
** Doit être unique sur chaque système StorageGRID (pas seulement unique au sein du compte locataire).
** Doit être conforme au DNS.
** Doit contenir au moins 3 et pas plus de 63 caractères.
** Peut être une série d'une ou plusieurs étiquettes, avec des étiquettes adjacentes séparées par un point.  Chaque étiquette doit commencer et se terminer par une lettre minuscule ou un chiffre et ne peut utiliser que des lettres minuscules, des chiffres et des traits d'union.
** Ne doit pas ressembler à une adresse IP au format texte.
** Ne doit pas utiliser de points dans les requêtes de style hébergé virtuellement.  Les points entraîneront des problèmes avec la vérification du certificat générique du serveur.


* Par défaut, les buckets sont créés dans le `us-east-1` région; cependant, vous pouvez utiliser le `LocationConstraint` élément de demande dans le corps de la demande pour spécifier une région différente.  Lors de l'utilisation du `LocationConstraint` élément, vous devez spécifier le nom exact d'une région qui a été définie à l'aide du gestionnaire de grille ou de l'API de gestion de grille.  Contactez votre administrateur système si vous ne connaissez pas le nom de la région à utiliser.
+
*Remarque* : une erreur se produira si votre demande CreateBucket utilise une région qui n’a pas été définie dans StorageGRID.

* Vous pouvez inclure le `x-amz-bucket-object-lock-enabled` en-tête de demande pour créer un bucket avec S3 Object Lock activé. Voir link:../s3/use-s3-api-for-s3-object-lock.html["Utiliser l'API REST S3 pour configurer le verrouillage d'objet S3"] .
+
Vous devez activer le verrouillage d’objet S3 lorsque vous créez le bucket.  Vous ne pouvez pas ajouter ou désactiver le verrouillage d'objet S3 après la création d'un bucket.  S3 Object Lock nécessite le contrôle de version du bucket, qui est activé automatiquement lorsque vous créez le bucket.





 a| 
Supprimer le bucket
 a| 
Supprime le bucket.



 a| 
SupprimerBucketCors
 a| 
Supprime la configuration CORS pour le bucket.



 a| 
Supprimer le chiffrement du bucket
 a| 
Supprime le cryptage par défaut du bucket.  Les objets chiffrés existants restent chiffrés, mais tous les nouveaux objets ajoutés au bucket ne sont pas chiffrés.



 a| 
Supprimer le cycle de vie du bucket
 a| 
Supprime la configuration du cycle de vie du bucket. Voir link:create-s3-lifecycle-configuration.html["Créer une configuration du cycle de vie S3"] .



 a| 
Supprimer la politique de bucket
 a| 
Supprime la politique attachée au bucket.



 a| 
SupprimerBucketReplication
 a| 
Supprime la configuration de réplication attachée au bucket.



 a| 
Supprimer le balisage du bucket
 a| 
Utilise le `tagging` sous-ressource pour supprimer toutes les balises d'un bucket.

*Attention* : Si une balise de politique ILM non par défaut est définie pour ce compartiment, il y aura un `NTAP-SG-ILM-BUCKET-TAG` balise de bucket avec une valeur qui lui est attribuée.  N'émettez pas de demande DeleteBucketTagging s'il y a un `NTAP-SG-ILM-BUCKET-TAG` étiquette de seau.  Au lieu de cela, émettez une requête PutBucketTagging avec uniquement le `NTAP-SG-ILM-BUCKET-TAG` balise et sa valeur attribuée pour supprimer toutes les autres balises du bucket.  Ne pas modifier ni supprimer le `NTAP-SG-ILM-BUCKET-TAG` étiquette de seau.



 a| 
ObtenirBucketAcl
 a| 
Renvoie une réponse positive et l'ID, le nom d'affichage et l'autorisation du propriétaire du bucket, indiquant que le propriétaire a un accès complet au bucket.



 a| 
ObtenirBucketCors
 a| 
Renvoie le `cors` configuration pour le bucket.



 a| 
Obtenir le chiffrement du bucket
 a| 
Renvoie la configuration de chiffrement par défaut pour le bucket.



 a| 
GetBucketLifecycleConfiguration

(anciennement appelé cycle de vie du bucket GET)
 a| 
Renvoie la configuration du cycle de vie du bucket. Voir link:create-s3-lifecycle-configuration.html["Créer une configuration du cycle de vie S3"] .



 a| 
Obtenir l'emplacement du bucket
 a| 
Renvoie la région qui a été définie à l'aide de `LocationConstraint` élément dans la requête CreateBucket.  Si la région du bucket est `us-east-1` , une chaîne vide est renvoyée pour la région.



 a| 
Configuration de GetBucketNotification

(anciennement appelée notification GET Bucket)
 a| 
Renvoie la configuration de notification attachée au bucket.



 a| 
Obtenir la politique de Bucket
 a| 
Renvoie la politique attachée au bucket.



 a| 
Réplication GetBucket
 a| 
Renvoie la configuration de réplication attachée au bucket.



 a| 
Obtenir le balisage du bucket
 a| 
Utilise le `tagging` sous-ressource pour renvoyer toutes les balises d'un bucket.

*Attention* : Si une balise de politique ILM non par défaut est définie pour ce compartiment, il y aura un `NTAP-SG-ILM-BUCKET-TAG` balise de bucket avec une valeur qui lui est attribuée.  Ne pas modifier ni supprimer cette balise.



 a| 
Obtenir la gestion des versions du bucket
 a| 
Cette implémentation utilise le `versioning` sous-ressource pour renvoyer l'état de version d'un bucket.

* _blank_ : le contrôle de version n'a jamais été activé (le bucket est « Non versionné »)
* Activé : le contrôle de version est activé
* Suspendu : le contrôle de version était précédemment activé et est suspendu




 a| 
Obtenir la configuration du verrouillage de l'objet
 a| 
Renvoie le mode de conservation par défaut du bucket et la période de conservation par défaut, si configurés.

Voir link:../s3/use-s3-api-for-s3-object-lock.html["Utiliser l'API REST S3 pour configurer le verrouillage d'objet S3"] .



 a| 
Tête de godet
 a| 
Détermine si un bucket existe et si vous avez l'autorisation d'y accéder.

Cette opération renvoie :

* `x-ntap-sg-bucket-id`: L'UUID du bucket au format UUID.
* `x-ntap-sg-trace-id`: L'ID de trace unique de la demande associée.




 a| 
ListObjects et ListObjectsV2

(anciennement nommé GET Bucket)
 a| 
Renvoie tout ou partie (jusqu'à 1 000) des objets d'un bucket.  La classe de stockage des objets peut avoir l'une des deux valeurs, même si l'objet a été ingéré avec le `REDUCED_REDUNDANCY` option de classe de stockage :

* `STANDARD`, ce qui indique que l'objet est stocké dans un pool de stockage composé de nœuds de stockage.
* `GLACIER`, ce qui indique que l'objet a été déplacé vers le bucket externe spécifié par le pool de stockage Cloud.


Si le compartiment contient un grand nombre de clés supprimées qui ont le même préfixe, la réponse peut inclure certaines `CommonPrefixes` qui ne contiennent pas de clés.



 a| 
ListObjectVersions

(anciennement appelées versions d'objets GET Bucket)
 a| 
Avec un accès en LECTURE sur un bucket, en utilisant cette opération avec le `versions` la sous-ressource répertorie les métadonnées de toutes les versions des objets dans le bucket.



 a| 
PutBucketCors
 a| 
Définit la configuration CORS pour un bucket afin que celui-ci puisse traiter les demandes inter-origines.  Le partage de ressources inter-origines (CORS) est un mécanisme de sécurité qui permet aux applications Web clientes d'un domaine d'accéder aux ressources d'un domaine différent.  Par exemple, supposons que vous utilisiez un bucket S3 nommé `images` pour stocker des graphiques.  En définissant la configuration CORS pour le `images` bucket, vous pouvez autoriser l'affichage des images de ce bucket sur le site Web `+http://www.example.com+` .



 a| 
Cryptage PutBucket
 a| 
Définit l'état de cryptage par défaut d'un bucket existant.  Lorsque le chiffrement au niveau du bucket est activé, tout nouvel objet ajouté au bucket est chiffré. StorageGRID prend en charge le chiffrement côté serveur avec des clés gérées par StorageGRID.  Lors de la spécification de la règle de configuration de chiffrement côté serveur, définissez le `SSEAlgorithm` paramètre à `AES256` , et n'utilisez pas le `KMSMasterKeyID` paramètre.

La configuration de chiffrement par défaut du bucket est ignorée si la demande de téléchargement d'objet spécifie déjà le chiffrement (c'est-à-dire si la demande inclut le `x-amz-server-side-encryption-*` en-tête de requête).



 a| 
Configuration du cycle de vie de PutBucket

(anciennement appelé cycle de vie du bucket PUT)
 a| 
Crée une nouvelle configuration de cycle de vie pour le bucket ou remplace une configuration de cycle de vie existante.  StorageGRID prend en charge jusqu'à 1 000 règles de cycle de vie dans une configuration de cycle de vie.  Chaque règle peut inclure les éléments XML suivants :

* Expiration (jours, date, ExpiredObjectDeleteMarker)
* NoncurrentVersionExpiration (NewerNoncurrentVersions, NoncurrentDays)
* Filtre (préfixe, balise)
* Statut
* ID


StorageGRID ne prend pas en charge ces actions :

* AbandonnerTéléchargement multi-parties incomplet
* Transition


Voir link:create-s3-lifecycle-configuration.html["Créer une configuration du cycle de vie S3"] . Pour comprendre comment l'action Expiration dans un cycle de vie de bucket interagit avec les instructions de placement ILM, voirlink:../ilm/how-ilm-operates-throughout-objects-life.html["Comment ILM fonctionne tout au long de la vie d'un objet"] .

*Remarque* : la configuration du cycle de vie du bucket peut être utilisée avec les buckets pour lesquels le verrouillage d'objet S3 est activé, mais la configuration du cycle de vie du bucket n'est pas prise en charge pour les buckets conformes hérités.



 a| 
Configuration de PutBucketNotification

(anciennement appelée notification PUT Bucket)
 a| 
Configure les notifications pour le bucket à l'aide du XML de configuration de notification inclus dans le corps de la demande.  Vous devez être conscient des détails de mise en œuvre suivants :

* StorageGRID prend en charge les rubriques Amazon Simple Notification Service (Amazon SNS) ou Kafka comme destinations.  Les points de terminaison Simple Queue Service (SQS) ou Amazon Lambda ne sont pas pris en charge.
* La destination des notifications doit être spécifiée comme l'URN d'un point de terminaison StorageGRID .  Les points de terminaison peuvent être créés à l’aide du gestionnaire de locataires ou de l’API de gestion des locataires.
+
Le point de terminaison doit exister pour que la configuration des notifications réussisse.  Si le point de terminaison n'existe pas, un `400 Bad Request` l'erreur est renvoyée avec le code `InvalidArgument` .

* Vous ne pouvez pas configurer de notification pour les types d’événements suivants.  Ces types d'événements ne sont *pas* pris en charge.
+
** `s3:ReducedRedundancyLostObject`
** `s3:ObjectRestore:Completed`


* Les notifications d'événements envoyées depuis StorageGRID utilisent le format JSON standard, sauf qu'elles n'incluent pas certaines clés et utilisent des valeurs spécifiques pour d'autres, comme indiqué dans la liste suivante :
+
** *Source de l'événement*
+
`sgws:s3`

** *awsRegion*
+
non inclus

** *x-amz-id-2*
+
non inclus

** *arn*
+
`urn:sgws:s3:::bucket_name`







 a| 
Politique de PutBucket
 a| 
Définit la politique attachée au bucket. Voir link:bucket-and-group-access-policies.html["Utiliser des politiques d'accès aux buckets et aux groupes"] .



 a| 
Réplication de PutBucket
 a| 
Configurelink:../tenant/understanding-cloudmirror-replication-service.html["Réplication StorageGRID CloudMirror"] pour le bucket utilisant la configuration de réplication XML fournie dans le corps de la demande.  Pour la réplication CloudMirror, vous devez connaître les détails d’implémentation suivants :

* StorageGRID prend uniquement en charge la version V1 de la configuration de réplication.  Cela signifie que StorageGRID ne prend pas en charge l'utilisation du `Filter` élément pour les règles et suit les conventions V1 pour la suppression des versions d'objet.  Pour plus de détails, voir https://docs.aws.amazon.com/AmazonS3/latest/userguide/replication-add-config.html["Guide de l'utilisateur d'Amazon Simple Storage Service : Configuration de la réplication"^] .
* La réplication de bucket peut être configurée sur des buckets versionnés ou non versionnés.
* Vous pouvez spécifier un bucket de destination différent dans chaque règle du XML de configuration de réplication.  Un bucket source peut être répliqué vers plusieurs buckets de destination.
* Les buckets de destination doivent être spécifiés comme URN des points de terminaison StorageGRID comme spécifié dans le gestionnaire de locataires ou l'API de gestion des locataires. Voir link:../tenant/configuring-cloudmirror-replication.html["Configurer la réplication CloudMirror"] .
+
Le point de terminaison doit exister pour que la configuration de la réplication réussisse.  Si le point de terminaison n'existe pas, la demande échoue en tant que `400 Bad Request` . Le message d'erreur indique : `Unable to save the replication policy. The specified endpoint URN does not exist: _URN_.`

* Vous n'avez pas besoin de spécifier un `Role` dans la configuration XML.  Cette valeur n'est pas utilisée par StorageGRID et sera ignorée si elle est soumise.
* Si vous omettez la classe de stockage du XML de configuration, StorageGRID utilise le `STANDARD` classe de stockage par défaut.
* Si vous supprimez un objet du bucket source ou si vous supprimez le bucket source lui-même, le comportement de la réplication inter-région est le suivant :
+
** Si vous supprimez l'objet ou le bucket avant qu'il ne soit répliqué, l'objet/bucket n'est pas répliqué et vous n'en êtes pas averti.
** Si vous supprimez l'objet ou le compartiment après sa réplication, StorageGRID suit le comportement de suppression standard d'Amazon S3 pour la V1 de la réplication inter-régions.






 a| 
Balisage de PutBucket
 a| 
Utilise le `tagging` sous-ressource pour ajouter ou mettre à jour un ensemble de balises pour un bucket.  Lorsque vous ajoutez des balises de bucket, tenez compte des limitations suivantes :

* StorageGRID et Amazon S3 prennent en charge jusqu'à 50 balises pour chaque compartiment.
* Les balises associées à un bucket doivent avoir des clés de balise uniques.  Une clé de balise peut comporter jusqu'à 128 caractères Unicode.
* Les valeurs des balises peuvent contenir jusqu'à 256 caractères Unicode.
* La clé et les valeurs sont sensibles à la casse.


*Attention* : Si une balise de politique ILM non par défaut est définie pour ce compartiment, il y aura un `NTAP-SG-ILM-BUCKET-TAG` balise de bucket avec une valeur qui lui est attribuée.  Assurez-vous que le `NTAP-SG-ILM-BUCKET-TAG` la balise de bucket est incluse avec la valeur attribuée dans toutes les requêtes PutBucketTagging.  Ne pas modifier ni supprimer cette balise.

*Remarque* : cette opération écrasera toutes les balises actuelles que le bucket possède déjà.  Si des balises existantes sont omises de l'ensemble, ces balises seront supprimées pour le bucket.



 a| 
Gestion des versions de PutBucket
 a| 
Utilise le `versioning` sous-ressource pour définir l'état de version d'un bucket existant.  Vous pouvez définir l’état de versionnage avec l’une des valeurs suivantes :

* Activé : active le contrôle de version pour les objets du bucket.  Tous les objets ajoutés au bucket reçoivent un ID de version unique.
* Suspendu : désactive le contrôle de version pour les objets du bucket.  Tous les objets ajoutés au bucket reçoivent l'ID de version `null` .




 a| 
Configuration de PutObjectLock
 a| 
Configure ou supprime le mode de conservation par défaut du bucket et la période de conservation par défaut.

Si la période de conservation par défaut est modifiée, la date de conservation des versions d'objet existantes reste la même et n'est pas recalculée à l'aide de la nouvelle période de conservation par défaut.

Voirlink:../s3/use-s3-api-for-s3-object-lock.html["Utiliser l'API REST S3 pour configurer le verrouillage d'objet S3"] pour des informations détaillées.

|===