---
permalink: s3/post-object-restore.html 
sidebar: sidebar 
keywords: post, RestoreObject, object 
summary: Vous pouvez utiliser la demande S3 RestoreObject pour restaurer un objet stocké dans un pool de stockage cloud. 
---
= Restaurer l'objet
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser la demande S3 RestoreObject pour restaurer un objet stocké dans un pool de stockage cloud.



== Type de demande pris en charge

StorageGRID prend uniquement en charge les requêtes RestoreObject pour restaurer un objet.  Il ne prend pas en charge le `SELECT` type de restauration.  Sélectionnez les demandes de retour `XNotImplemented` .



== Gestion des versions

En option, précisez `versionId` pour restaurer une version spécifique d'un objet dans un bucket versionné.  Si vous ne précisez pas `versionId` , la version la plus récente de l'objet est restaurée



== Comportement de RestoreObject sur les objets du pool de stockage cloud

Si un objet a été stocké dans unlink:../ilm/what-cloud-storage-pool-is.html["Pool de stockage cloud"] , une demande RestoreObject a le comportement suivant, en fonction de l'état de l'objet. Voirlink:head-object.html["HeadObject"] pour plus de détails.


NOTE: Si un objet est stocké dans un pool de stockage cloud et qu'une ou plusieurs copies de l'objet existent également sur la grille, il n'est pas nécessaire de restaurer l'objet en émettant une demande RestoreObject.  Au lieu de cela, la copie locale peut être récupérée directement, à l'aide d'une requête GetObject.

[cols="1a,2a"]
|===
| État de l'objet | Comportement de RestoreObject 


 a| 
Objet ingéré dans StorageGRID mais pas encore évalué par ILM, ou l'objet ne se trouve pas dans un pool de stockage cloud
 a| 
`403 Forbidden` ,  `InvalidObjectState`



 a| 
Objet dans le pool de stockage cloud, mais pas encore passé à un état non récupérable
 a| 
`200 OK`Aucune modification n'est apportée.

*Remarque* : Avant qu'un objet ne soit passé à un état non récupérable, vous ne pouvez pas modifier son `expiry-date` .



 a| 
Objet passé à un état non récupérable
 a| 
`202 Accepted`Restaure une copie récupérable de l'objet dans le pool de stockage cloud pendant le nombre de jours spécifié dans le corps de la demande.  À la fin de cette période, l’objet est remis dans un état non récupérable.

En option, utilisez le `Tier` élément de demande pour déterminer combien de temps la tâche de restauration prendra pour se terminer(`Expedited` , `Standard` , ou `Bulk` ).  Si vous ne précisez pas `Tier` , le `Standard` le niveau est utilisé.

*Important* : Si un objet a été transféré vers S3 Glacier Deep Archive ou si le pool de stockage cloud utilise le stockage Azure Blob, vous ne pouvez pas le restaurer à l'aide de `Expedited` étage.  L'erreur suivante est renvoyée `403 Forbidden` , `InvalidTier` : `Retrieval option is not supported by this storage class` .



 a| 
Objet en cours de restauration à partir d'un état non récupérable
 a| 
`409 Conflict` ,  `RestoreAlreadyInProgress`



 a| 
Objet entièrement restauré dans le pool de stockage cloud
 a| 
`200 OK`

*Remarque :* si un objet a été restauré dans un état récupérable, vous pouvez modifier son `expiry-date` en réémettant la requête RestoreObject avec une nouvelle valeur pour `Days` .  La date de restauration est mise à jour par rapport à l'heure de la demande.

|===