---
permalink: s3/put-bucket-consistency-request.html 
sidebar: sidebar 
keywords: S3 REST API, S3 operations, PUT bucket consistency request 
summary: La demande de cohérence PUT Bucket vous permet de spécifier la cohérence à appliquer aux opérations effectuées sur un bucket. 
---
= Cohérence du seau PUT
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La demande de cohérence PUT Bucket vous permet de spécifier la cohérence à appliquer aux opérations effectuées sur un bucket.

La cohérence par défaut est définie pour garantir la lecture après écriture des objets nouvellement créés.

.Avant de commencer
Vous devez disposer de l'autorisation s3:PutBucketConsistency ou être root du compte pour terminer cette opération.



== Demande

Le `x-ntap-sg-consistency` le paramètre doit contenir l'une des valeurs suivantes :

[cols="1a,2a"]
|===
| Cohérence | Description 


 a| 
tous
 a| 
Tous les nœuds reçoivent les données immédiatement, sinon la demande échouera.



 a| 
fort-mondial
 a| 
Garantit la cohérence de lecture après écriture pour toutes les demandes client sur tous les sites.



 a| 
site fort
 a| 
Garantit la cohérence de lecture après écriture pour toutes les demandes client au sein d'un site.



 a| 
lecture après nouvelle écriture
 a| 
(Par défaut) Fournit une cohérence de lecture après écriture pour les nouveaux objets et une cohérence éventuelle pour les mises à jour d'objets.  Offre des garanties de haute disponibilité et de protection des données.  Recommandé dans la plupart des cas.



 a| 
disponible
 a| 
Assure une cohérence éventuelle pour les nouveaux objets et les mises à jour d'objets.  Pour les buckets S3, utilisez-les uniquement si nécessaire (par exemple, pour un bucket contenant des valeurs de journal rarement lues ou pour des opérations HEAD ou GET sur des clés qui n'existent pas).  Non pris en charge pour les buckets S3 FabricPool .

|===
*Remarque :* En général, vous devez utiliser la cohérence « Lecture après nouvelle écriture ».  Si les requêtes ne fonctionnent pas correctement, modifiez le comportement du client de l’application si possible.  Ou configurez le client pour spécifier la cohérence de chaque demande d’API.  Définissez la consistance au niveau du seau uniquement en dernier recours.



== Exemple de demande

[listing, subs="specialcharacters,quotes"]
----
PUT /bucket?x-ntap-sg-consistency=strong-global HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----
.Informations connexes
link:consistency-controls.html["Valeurs de cohérence"]
