---
permalink: s3/upload-part.html 
sidebar: sidebar 
keywords: s3 UploadPart operation 
summary: 'L"opération UploadPart télécharge une partie dans un téléchargement en plusieurs parties pour un objet.' 
---
= Télécharger une partie
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'opération UploadPart télécharge une partie dans un téléchargement en plusieurs parties pour un objet.



== En-têtes de requête pris en charge

Les en-têtes de requête suivants sont pris en charge :

* `x-amz-checksum-sha256`
* `Content-Length`
* `Content-MD5`




== En-têtes de requête pour le chiffrement côté serveur

Si vous avez spécifié le chiffrement SSE-C pour la demande CreateMultipartUpload, vous devez également inclure les en-têtes de demande suivants dans chaque demande UploadPart :

* `x-amz-server-side-encryption-customer-algorithm`: Préciser `AES256` .
* `x-amz-server-side-encryption-customer-key`:Spécifiez la même clé de chiffrement que celle que vous avez fournie dans la demande CreateMultipartUpload.
* `x-amz-server-side-encryption-customer-key-MD5`: Spécifiez le même condensé MD5 que celui que vous avez fourni dans la demande CreateMultipartUpload.



CAUTION: Les clés de chiffrement que vous fournissez ne sont jamais stockées.  Si vous perdez une clé de chiffrement, vous perdez l'objet correspondant.  Avant d'utiliser les clés fournies par le client pour sécuriser les données d'objet, examinez les considérations danslink:using-server-side-encryption.html["Utiliser le cryptage côté serveur"] .

Si vous avez spécifié une somme de contrôle SHA-256 lors de la demande CreateMultipartUpload, vous devez également inclure l'en-tête de demande suivant dans chaque demande UploadPart :

* `x-amz-checksum-sha256`:Spécifiez la somme de contrôle SHA-256 pour cette partie.




== En-têtes de requête non pris en charge

Les en-têtes de requête suivants ne sont pas pris en charge :

* `x-amz-sdk-checksum-algorithm`
* `x-amz-trailer`




== Gestion des versions

Le téléchargement en plusieurs parties consiste en des opérations distinctes pour lancer le téléchargement, répertorier les téléchargements, télécharger des parties, assembler les parties téléchargées et terminer le téléchargement.  Les objets sont créés (et versionnés si applicable) lorsque l'opération CompleteMultipartUpload est effectuée.
