---
permalink: monitor/disabling-alert-rules.html 
sidebar: sidebar 
keywords: how to disable alert rules, how to remove a custom alert rule 
summary: 'Vous pouvez modifier l"état activé/désactivé d"une règle d"alerte par défaut ou personnalisée.' 
---
= Désactiver les règles d'alerte
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez modifier l'état activé/désactivé d'une règle d'alerte par défaut ou personnalisée.

.Avant de commencer
* Vous êtes connecté au Grid Manager à l'aide d'unlink:../admin/web-browser-requirements.html["navigateur Web pris en charge"] .
* Vous avez lelink:../admin/admin-group-permissions.html["Gérer les alertes ou l'autorisation d'accès root"] .


.À propos de cette tâche
Lorsqu'une règle d'alerte est désactivée, ses expressions ne sont pas évaluées et aucune alerte n'est déclenchée.


CAUTION: En général, il n’est pas recommandé de désactiver une règle d’alerte par défaut.  Si une règle d’alerte est désactivée, vous risquez de ne pas détecter un problème sous-jacent jusqu’à ce qu’il empêche une opération critique de se terminer.

.Étapes
. Sélectionnez *ALERTES* > *Règles*.
+
La page Règles d’alerte s’affiche.

. Sélectionnez le bouton radio correspondant à la règle d’alerte que vous souhaitez désactiver ou activer.
. Sélectionnez *Modifier la règle*.
+
La boîte de dialogue Modifier la règle s’affiche.

. Cochez ou décochez la case *Activé* pour déterminer si cette règle d'alerte est actuellement activée.
+
Si une règle d’alerte est désactivée, ses expressions ne sont pas évaluées et aucune alerte n’est déclenchée.

+

NOTE: Si vous désactivez la règle d'alerte pour une alerte en cours, vous devez attendre quelques minutes pour que l'alerte ne s'affiche plus comme une alerte active.

. Sélectionnez *Enregistrer*.
+
*Désactivé* apparaît dans la colonne *Statut*.


