---
permalink: monitor/manually-triggering-autosupport-message.html 
sidebar: sidebar 
keywords: autosupport, triggering autosupport, manually triggering autosupport, autosupport triggers 
summary: 'Pour aider le support technique à résoudre les problèmes liés à votre système StorageGRID , vous pouvez déclencher manuellement l"envoi d"un package AutoSupport .' 
---
= Déclencher manuellement un package AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour aider le support technique à résoudre les problèmes liés à votre système StorageGRID , vous pouvez déclencher manuellement l'envoi d'un package AutoSupport .

.Avant de commencer
* Vous devez être connecté au Grid Manager à l'aide d'unlink:../admin/web-browser-requirements.html["navigateur Web pris en charge"] .
* Vous devez disposer de l'accès root ou de l'autorisation de configuration d'une autre grille.


.Étapes
. Sélectionnez *SUPPORT* > *Outils* > * AutoSupport*.
. Dans l'onglet *Actions*, sélectionnez *Envoyer AutoSupport déclenchée par l'utilisateur*.
+
StorageGRID tente d'envoyer un package AutoSupport au site de support NetApp . Si la tentative réussit, les valeurs *Résultat le plus récent* et *Dernière heure de réussite* dans l'onglet *Résultats* sont mises à jour. En cas de problème, la valeur *Résultat le plus récent* est mise à jour sur « Échec » et StorageGRID n'essaie pas d'envoyer à nouveau le package AutoSupport .

+

TIP: Après avoir envoyé un package AutoSupport déclenché par l'utilisateur, actualisez la page AutoSupport dans votre navigateur après 1 minute pour accéder aux résultats les plus récents.


