---
permalink: monitor/monitoring-load-balancing-operations.html 
sidebar: sidebar 
keywords: load balancing, monitoring 
summary: 'Si vous utilisez un équilibreur de charge pour gérer les connexions client à StorageGRID, vous devez surveiller les opérations d"équilibrage de charge après avoir configuré le système initialement et après avoir apporté des modifications de configuration ou effectué une extension.' 
---
= Surveiller les opérations d'équilibrage de charge
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous utilisez un équilibreur de charge pour gérer les connexions client à StorageGRID, vous devez surveiller les opérations d'équilibrage de charge après avoir configuré le système initialement et après avoir apporté des modifications de configuration ou effectué une extension.

.À propos de cette tâche
Vous pouvez utiliser le service Load Balancer sur les nœuds d'administration ou les nœuds de passerelle ou un équilibreur de charge tiers externe pour répartir les demandes des clients sur plusieurs nœuds de stockage.

Après avoir configuré l’équilibrage de charge, vous devez confirmer que les opérations d’ingestion et de récupération d’objets sont réparties uniformément sur les nœuds de stockage.  Des demandes réparties uniformément garantissent que StorageGRID reste réactif aux demandes des clients sous charge et peut aider à maintenir les performances des clients.

Si vous avez configuré un groupe haute disponibilité (HA) de nœuds de passerelle ou de nœuds d'administration en mode de sauvegarde active, un seul nœud du groupe distribue activement les demandes des clients.

Pour plus d'informations, consultez la section link:../admin/configuring-client-connections.html["Configurer les connexions client S3"] .

.Étapes
. Si les clients S3 se connectent à l'aide du service Load Balancer, vérifiez que les nœuds d'administration ou les nœuds de passerelle distribuent activement le trafic comme prévu :
+
.. Sélectionnez *NODES*.
.. Sélectionnez un nœud de passerelle ou un nœud d’administration.
.. Dans l'onglet *Vue d'ensemble*, vérifiez si une interface de nœud se trouve dans un groupe HA et si l'interface de nœud a le rôle de Principal.
+
Les nœuds avec le rôle principal et les nœuds qui ne font pas partie d'un groupe HA doivent distribuer activement les demandes aux clients.

.. Pour chaque nœud qui doit distribuer activement les demandes des clients, sélectionnez l'optionlink:viewing-load-balancer-tab.html["Onglet Équilibreur de charge"] .
.. Consultez le graphique du trafic des demandes d’équilibrage de charge de la semaine dernière pour vous assurer que le nœud a distribué activement les demandes.
+
Les nœuds d’un groupe HA de sauvegarde active peuvent assumer le rôle de sauvegarde de temps à autre.  Pendant ce temps, les nœuds ne distribuent pas les requêtes des clients.

.. Consultez le graphique du taux de demandes entrantes de l’équilibreur de charge de la semaine dernière pour évaluer le débit d’objet du nœud.
.. Répétez ces étapes pour chaque nœud d’administration ou nœud de passerelle dans le système StorageGRID .
.. Vous pouvez également utiliser des stratégies de classification du trafic pour afficher une analyse plus détaillée du trafic traité par le service Load Balancer.


. Vérifiez que ces demandes sont réparties uniformément entre les nœuds de stockage.
+
.. Sélectionnez *_Nœud de stockage_* > *LDR* > *HTTP*.
.. Consultez le nombre de *sessions entrantes actuellement établies*.
.. Répétez l’opération pour chaque nœud de stockage dans la grille.
+
Le nombre de sessions doit être à peu près égal sur tous les nœuds de stockage.




