---
permalink: monitor/removing-custom-alert-rules.html 
sidebar: sidebar 
keywords: how to disable alert rules, how to remove a custom alert rule 
summary: Vous pouvez supprimer une règle d’alerte personnalisée si vous ne souhaitez plus l’utiliser. 
---
= Supprimer les règles d'alerte personnalisées
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez supprimer une règle d’alerte personnalisée si vous ne souhaitez plus l’utiliser.

.Avant de commencer
* Vous êtes connecté au Grid Manager à l'aide d'unlink:../admin/web-browser-requirements.html["navigateur Web pris en charge"] .
* Vous avez lelink:../admin/admin-group-permissions.html["Gérer les alertes ou l'autorisation d'accès root"] .


.Étapes
. Sélectionnez *ALERTES* > *Règles*.
+
La page Règles d’alerte s’affiche.

. Sélectionnez le bouton radio correspondant à la règle d’alerte personnalisée que vous souhaitez supprimer.
+
Vous ne pouvez pas supprimer une règle d’alerte par défaut.

. Sélectionnez *Supprimer la règle personnalisée*.
+
Une boîte de dialogue de confirmation apparaît.

. Sélectionnez *OK* pour supprimer la règle d’alerte.
+
Toutes les instances actives de l’alerte seront résolues dans les 10 minutes.


