---
permalink: monitor/using-snmp-monitoring.html 
sidebar: sidebar 
keywords: snmp, monitoring 
summary: 'Si vous souhaitez surveiller StorageGRID à l"aide du protocole SNMP (Simple Network Management Protocol), vous devez configurer l"agent SNMP inclus avec StorageGRID.' 
---
= Utiliser la surveillance SNMP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous souhaitez surveiller StorageGRID à l'aide du protocole SNMP (Simple Network Management Protocol), vous devez configurer l'agent SNMP inclus avec StorageGRID.

* link:configuring-snmp-agent.html["Configurer l'agent SNMP"]
* link:updating-snmp-agent.html["Mettre à jour l'agent SNMP"]




== Capacités

Chaque nœud StorageGRID exécute un agent SNMP, ou démon, qui fournit une MIB.  La MIB StorageGRID contient des définitions de table et de notification pour les alertes.  La MIB contient également des informations de description du système telles que la plate-forme et le numéro de modèle pour chaque nœud.  Chaque nœud StorageGRID prend également en charge un sous-ensemble d’objets MIB-II.


NOTE: Voirlink:access-snmp-mib.html["Accéder aux fichiers MIB"] si vous souhaitez télécharger les fichiers MIB sur vos nœuds de grille.

Initialement, SNMP est désactivé sur tous les nœuds.  Lorsque vous configurez l'agent SNMP, tous les nœuds StorageGRID reçoivent la même configuration.

L'agent SNMP StorageGRID prend en charge les trois versions du protocole SNMP.  Il fournit un accès MIB en lecture seule pour les requêtes et peut envoyer deux types de notifications basées sur des événements à un système de gestion :

Pièges:: Les interruptions sont des notifications envoyées par l'agent SNMP qui ne nécessitent pas d'accusé de réception par le système de gestion.  Les interruptions servent à informer le système de gestion qu'un événement s'est produit dans StorageGRID, comme le déclenchement d'une alerte.
+
--
Les interruptions sont prises en charge dans les trois versions de SNMP.

--
Informe:: Les informations sont similaires aux pièges, mais elles nécessitent une reconnaissance par le système de gestion.  Si l'agent SNMP ne reçoit pas d'accusé de réception dans un certain délai, il renvoie l'information jusqu'à ce qu'un accusé de réception soit reçu ou que la valeur de nouvelle tentative maximale soit atteinte.
+
--
Les informations sont prises en charge dans SNMPv2c et SNMPv3.

--


Les notifications d'interruption et d'information sont envoyées dans les cas suivants :

* Une alerte par défaut ou personnalisée est déclenchée à n’importe quel niveau de gravité.  Pour supprimer les notifications SNMP pour une alerte, vous devezlink:silencing-alert-notifications.html["configurer un silence"] pour l'alerte.  Les notifications d'alerte sont envoyées par lelink:../primer/what-admin-node-is.html["nœud d'administration de l'expéditeur préféré"] .
+
Chaque alerte est mappée à l’un des trois types d’interruption en fonction du niveau de gravité de l’alerte : activeMinorAlert, activeMajorAlert et activeCriticalAlert.  Pour une liste des alertes qui peuvent déclencher ces pièges, consultez lelink:alerts-reference.html["Référence des alertes"] .





== Prise en charge des versions SNMP

Le tableau fournit un résumé de haut niveau de ce qui est pris en charge pour chaque version SNMP.

[cols="1a,2a,2a,2a"]
|===
|  | SNMPv1 | SNMPv2c | SNMPv3 


 a| 
Requêtes

(GET et GETNEXT)
 a| 
Requêtes MIB en lecture seule
 a| 
Requêtes MIB en lecture seule
 a| 
Requêtes MIB en lecture seule



 a| 
Authentification des requêtes
 a| 
Chaîne communautaire
 a| 
Chaîne communautaire
 a| 
Modèle de sécurité basé sur l'utilisateur (USM) utilisateur



 a| 
Notifications

(PIÈGE et INFORME)
 a| 
Pièges uniquement
 a| 
Pièges et informations
 a| 
Pièges et informations



 a| 
Authentification des notifications
 a| 
Communauté de piège par défaut ou chaîne de communauté personnalisée pour chaque destination de piège
 a| 
Communauté de piège par défaut ou chaîne de communauté personnalisée pour chaque destination de piège
 a| 
Utilisateur USM pour chaque destination de trap

|===


== Limites

* StorageGRID prend en charge l'accès MIB en lecture seule.  L'accès en lecture-écriture n'est pas pris en charge.
* Tous les nœuds de la grille reçoivent la même configuration.
* SNMPv3 : StorageGRID ne prend pas en charge le mode de support de transport (TSM).
* SNMPv3 : le seul protocole d’authentification pris en charge est SHA (HMAC-SHA-96).
* SNMPv3 : le seul protocole de confidentialité pris en charge est AES.

