---
permalink: maintain/checking-storage-state-after-recovering-sga.html 
sidebar: sidebar 
keywords: storagegrid, recovery, node recovery, storage state 
summary: 'Après avoir récupéré un nœud de stockage d"appliance, vous devez vérifier que l"état souhaité du nœud de stockage de l"appliance est défini sur en ligne et vous assurer que l"état sera en ligne par défaut à chaque redémarrage du serveur de nœud de stockage.' 
---
= Vérifier l'état du stockage après la récupération du nœud de stockage de l'appliance
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Après avoir récupéré un nœud de stockage d'appliance, vous devez vérifier que l'état souhaité du nœud de stockage de l'appliance est défini sur en ligne et vous assurer que l'état sera en ligne par défaut à chaque redémarrage du serveur de nœud de stockage.

.Avant de commencer
* Vous êtes connecté au Grid Manager à l'aide d'unlink:../admin/web-browser-requirements.html["navigateur Web pris en charge"] .
* Le nœud de stockage a été récupéré et la récupération des données est terminée.


.Étapes
. Sélectionnez *SUPPORT* > *Outils* > *Topologie de grille*.
. Vérifiez les valeurs de *Nœud de stockage récupéré* > *LDR* > *Stockage* > *État de stockage -- Souhaité* et *État de stockage -- Actuel*.
+
La valeur des deux attributs doit être En ligne.

. Si l'état de stockage souhaité est défini sur Lecture seule, procédez comme suit :
+
.. Cliquez sur l'onglet *Configuration*.
.. Dans la liste déroulante *État de stockage – Souhaité*, sélectionnez *En ligne*.
.. Cliquez sur *Appliquer les modifications*.
.. Cliquez sur l'onglet *Aperçu* et confirmez que les valeurs de *État de stockage -- Souhaité* et *État de stockage -- Actuel* sont mises à jour sur En ligne.



