---
permalink: maintain/considerations-for-decommissioning-storage-nodes.html 
sidebar: sidebar 
keywords: storage node decommission, considerations, appliance node clone 
summary: Avant de mettre hors service un nœud de stockage, déterminez si vous pouvez cloner le nœud à la place.  Ensuite, si vous décidez de mettre hors service le nœud, vérifiez comment StorageGRID gère les objets et les métadonnées pendant la procédure de mise hors service. 
---
= Considérations relatives à la mise hors service des nœuds de stockage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de mettre hors service un nœud de stockage, déterminez si vous pouvez cloner le nœud à la place.  Ensuite, si vous décidez de mettre hors service le nœud, vérifiez comment StorageGRID gère les objets et les métadonnées pendant la procédure de mise hors service.



== Quand cloner un nœud au lieu de le mettre hors service

Si vous souhaitez remplacer un nœud de stockage d'appareil plus ancien par un appareil plus récent ou plus grand, envisagez de cloner le nœud d'appareil au lieu d'ajouter un nouvel appareil dans une extension, puis de mettre hors service l'ancien appareil.

Le clonage de nœud d'appliance vous permet de remplacer facilement un nœud d'appliance existant par une appliance compatible sur le même site StorageGRID .  Le processus de clonage transfère toutes les données vers le nouvel appareil, met le nouvel appareil en service et laisse l'ancien appareil dans un état de pré-installation.

Vous pouvez cloner un nœud d’appliance si vous en avez besoin :

* Remplacer un appareil qui arrive en fin de vie.
* Mettez à niveau un nœud existant pour profiter d’une technologie d’appareil améliorée.
* Augmentez la capacité de stockage de la grille sans modifier le nombre de nœuds de stockage dans votre système StorageGRID .
* Améliorez l’efficacité du stockage, par exemple en modifiant le mode RAID.


Voir https://docs.netapp.com/us-en/storagegrid-appliances/commonhardware/how-appliance-node-cloning-works.html["Clonage de nœud d'appareil"^] pour plus de détails.



== Considérations relatives aux nœuds de stockage connectés

Passez en revue les considérations relatives à la mise hors service d’un nœud de stockage connecté.

* Vous ne devez pas mettre hors service plus de 10 nœuds de stockage dans une seule procédure de mise hors service de nœud.
* Le système doit, à tout moment, inclure suffisamment de nœuds de stockage pour satisfaire aux exigences opérationnelles, y compris lalink:understanding-adc-service-quorum.html["Quorum du CDA"] et l'actiflink:reviewing-ilm-policy-and-storage-configuration.html["Politique ILM"] .  Pour satisfaire à cette restriction, vous devrez peut-être ajouter un nouveau nœud de stockage dans une opération d'extension avant de pouvoir mettre hors service un nœud de stockage existant.
+
Soyez prudent lorsque vous désaffectez des nœuds de stockage dans une grille contenant uniquement des nœuds de métadonnées basés sur des logiciels.  Si vous désactivez tous les nœuds configurés pour stocker à la fois des objets et des métadonnées, la possibilité de stocker des objets est supprimée de la grille.  Voirlink:../primer/what-storage-node-is.html#types-of-storage-nodes["Types de nœuds de stockage"] pour plus d'informations sur les nœuds de stockage contenant uniquement des métadonnées.

* Lorsque vous supprimez un nœud de stockage, de grands volumes de données d'objets sont transférés sur le réseau.  Bien que ces transferts ne devraient pas affecter les opérations normales du système, ils peuvent affecter la quantité totale de bande passante réseau consommée par le système StorageGRID .
* Les tâches associées à la mise hors service du nœud de stockage ont une priorité inférieure à celle des tâches associées aux opérations normales du système.  Cela signifie que la mise hors service n'interfère pas avec les opérations normales du système StorageGRID et n'a pas besoin d'être planifiée pour une période d'inactivité du système.  Étant donné que le déclassement est effectué en arrière-plan, il est difficile d’estimer combien de temps le processus prendra.  En général, la mise hors service se termine plus rapidement lorsque le système est silencieux ou si un seul nœud de stockage est supprimé à la fois.
* La mise hors service d’un nœud de stockage peut prendre des jours ou des semaines.  Planifiez cette procédure en conséquence.  Bien que le processus de mise hors service soit conçu pour ne pas avoir d’impact sur les opérations du système, il peut limiter d’autres procédures.  En général, vous devez effectuer toutes les mises à niveau ou extensions système prévues avant de supprimer les nœuds de grille.
* Si vous devez effectuer une autre procédure de maintenance pendant que les nœuds de stockage sont supprimés, vous pouvezlink:pausing-and-resuming-decommission-process-for-storage-nodes.html["suspendre la procédure de déclassement"] et reprenez-le une fois l'autre procédure terminée.
+

NOTE: Le bouton *Pause* est activé uniquement lorsque les étapes d'évaluation ILM ou de mise hors service des données codées par effacement sont atteintes ; cependant, l'évaluation ILM (migration des données) continuera de s'exécuter en arrière-plan.

* Vous ne pouvez pas exécuter d’opérations de réparation de données sur aucun nœud de grille lorsqu’une tâche de mise hors service est en cours d’exécution.
* Vous ne devez apporter aucune modification à une stratégie ILM pendant la mise hors service d'un nœud de stockage.
* Pour supprimer définitivement et en toute sécurité les données, vous devez effacer les lecteurs du nœud de stockage une fois la procédure de mise hors service terminée.




== Considérations relatives aux nœuds de stockage déconnectés

Passez en revue les considérations relatives à la mise hors service d’un nœud de stockage déconnecté.

* Ne mettez jamais hors service un nœud déconnecté à moins d'être sûr qu'il ne peut pas être remis en ligne ou récupéré.
+

CAUTION: N'exécutez pas cette procédure si vous pensez qu'il est possible de récupérer les données de l'objet à partir du nœud.  Contactez plutôt le support technique pour déterminer si la récupération du nœud est possible.

* Lorsque vous mettez hors service un nœud de stockage déconnecté, StorageGRID utilise les données d'autres nœuds de stockage pour reconstruire les données et métadonnées d'objet qui se trouvaient sur le nœud déconnecté.
* Une perte de données peut se produire si vous mettez hors service plusieurs nœuds de stockage déconnectés.  Le système peut ne pas être en mesure de reconstruire les données si le nombre de copies d'objets, de fragments codés par effacement ou de métadonnées d'objets disponibles n'est pas suffisant.  Lors de la mise hors service des nœuds de stockage dans une grille avec des nœuds basés uniquement sur des métadonnées logicielles, la mise hors service de tous les nœuds configurés pour stocker à la fois des objets et des métadonnées supprime tout le stockage d'objets de la grille.  Voirlink:../primer/what-storage-node-is.html#types-of-storage-nodes["Types de nœuds de stockage"] pour plus d'informations sur les nœuds de stockage contenant uniquement des métadonnées.
+

CAUTION: Si vous avez plusieurs nœuds de stockage déconnectés que vous ne pouvez pas récupérer, contactez le support technique pour déterminer la meilleure marche à suivre.

* Lorsque vous mettez hors service un nœud de stockage déconnecté, StorageGRID démarre les tâches de réparation des données à la fin du processus de mise hors service.  Ces tâches tentent de reconstruire les données et les métadonnées de l’objet qui ont été stockées sur le nœud déconnecté.
* Lorsque vous mettez hors service un nœud de stockage déconnecté, la procédure de mise hors service se termine relativement rapidement.  Cependant, les tâches de réparation des données peuvent prendre des jours ou des semaines à s'exécuter et ne sont pas surveillées par la procédure de mise hors service.  Vous devez surveiller manuellement ces tâches et les redémarrer si nécessaire. Voir link:checking-data-repair-jobs.html["Vérifier les tâches de réparation de données"] .
* Si vous désactivez un nœud de stockage déconnecté qui contient la seule copie d'un objet, l'objet sera perdu.  Les tâches de réparation de données ne peuvent reconstruire et récupérer des objets que si au moins une copie répliquée ou suffisamment de fragments codés par effacement existent sur les nœuds de stockage actuellement connectés.

