---
permalink: maintain/deploying-new-linux-hosts.html 
sidebar: sidebar 
keywords: storagegrid, deploy linux host, new host, new linux host 
summary: À quelques exceptions près, vous préparez les nouveaux hôtes comme vous l’avez fait lors du processus d’installation initial. 
---
= Déployer de nouveaux hôtes Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
À quelques exceptions près, vous préparez les nouveaux hôtes comme vous l’avez fait lors du processus d’installation initial.

Pour déployer des hôtes Linux physiques ou virtuels nouveaux ou réinstallés, suivez la procédure de préparation des hôtes dans les instructions d'installation de StorageGRID pour votre système d'exploitation Linux :

* link:../rhel/installing-linux.html["Installer Linux (Red Hat Enterprise Linux)"]
* link:../ubuntu/installing-linux.html["Installer Linux (Ubuntu ou Debian)"]


Cette procédure comprend les étapes permettant d’accomplir les tâches suivantes :

. Installer Linux.
. Configurer le réseau hôte.
. Configurer le stockage hôte.
. Installer le moteur du conteneur.
. Installez le service hôte StorageGRID .
+

CAUTION: Arrêtez-vous après avoir terminé la tâche « Installer le service hôte StorageGRID » dans les instructions d'installation.  Ne démarrez pas la tâche « Déploiement des nœuds de grille ».



Lorsque vous effectuez ces étapes, notez les directives importantes suivantes :

* Assurez-vous d’utiliser les mêmes noms d’interface d’hôte que ceux utilisés sur l’hôte d’origine.
* Si vous utilisez un stockage partagé pour prendre en charge vos nœuds StorageGRID , ou si vous avez déplacé une partie ou la totalité des lecteurs ou SSD des nœuds défaillants vers les nœuds de remplacement, vous devez rétablir les mêmes mappages de stockage qui étaient présents sur l'hôte d'origine.  Par exemple, si vous avez utilisé des WWID et des alias dans `/etc/multipath.conf` comme recommandé dans les instructions d'installation, assurez-vous d'utiliser les mêmes paires alias/WWID dans `/etc/multipath.conf` sur l'hôte de remplacement.
* Si le nœud StorageGRID utilise le stockage attribué à partir d'un système NetApp ONTAP , vérifiez que le volume n'a pas de stratégie de hiérarchisation FabricPool activée.  La désactivation de la hiérarchisation FabricPool pour les volumes utilisés avec les nœuds StorageGRID simplifie le dépannage et les opérations de stockage.
+

CAUTION: N'utilisez jamais FabricPool pour hiérarchiser les données liées à StorageGRID vers StorageGRID lui-même.  La hiérarchisation des données StorageGRID vers StorageGRID augmente le dépannage et la complexité opérationnelle.


