---
permalink: maintain/downloading-recovery-package.html 
sidebar: sidebar 
keywords: storagegrid, recovery package 
summary: Le fichier Recovery Package vous permet de restaurer le système StorageGRID en cas de panne. 
---
= Télécharger le package de récupération
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le fichier Recovery Package vous permet de restaurer le système StorageGRID en cas de panne.

.Avant de commencer
* À partir du nœud d'administration principal, vous êtes connecté au gestionnaire de grille à l'aide d'unlink:../admin/web-browser-requirements.html["navigateur Web pris en charge"] .
* Vous disposez de la phrase secrète de provisionnement.
* Tu aslink:../admin/admin-group-permissions.html["autorisations d'accès spécifiques"] .


Téléchargez le fichier du package de récupération actuel avant d'apporter des modifications à la topologie de grille du système StorageGRID ou avant de mettre à niveau le logiciel.  Ensuite, téléchargez une nouvelle copie du package de récupération après avoir apporté des modifications à la topologie de la grille ou après avoir mis à niveau le logiciel.

.Étapes
. Sélectionnez *MAINTENANCE* > *Système* > *Package de récupération*.
. Saisissez la phrase secrète d’approvisionnement et sélectionnez *Démarrer le téléchargement*.
+
Le téléchargement démarre immédiatement.

. Une fois le téléchargement terminé, ouvrez le `.zip` fichier et confirmez que vous pouvez accéder au contenu, y compris le `Passwords.txt` déposer.
. Copiez le fichier du package de récupération téléchargé(`.zip` ) vers deux endroits sûrs, sécurisés et séparés.
+

CAUTION: Le fichier du package de récupération doit être sécurisé car il contient des clés de chiffrement et des mots de passe qui peuvent être utilisés pour obtenir des données à partir du système StorageGRID .


