---
permalink: maintain/installing-services-appliance-platform-change-only.html 
sidebar: sidebar 
keywords: storagegrid, recover services appliance, recover appliance, recovering appliance, recovering services appliance, install services appliance, installing services appliance, services appliance 
summary: 'Lorsque vous récupérez un nœud de grille défaillant hébergé sur VMware ou un hôte Linux et que vous utilisez un dispositif de services pour le nœud de remplacement, vous devez d"abord installer le nouveau matériel du dispositif en utilisant le même nom de nœud (nom du système) que le nœud défaillant.' 
---
= Installer l'appareil de services (changement de plateforme uniquement)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque vous récupérez un nœud de grille défaillant hébergé sur VMware ou un hôte Linux et que vous utilisez un dispositif de services pour le nœud de remplacement, vous devez d'abord installer le nouveau matériel du dispositif en utilisant le même nom de nœud (nom du système) que le nœud défaillant.

.Avant de commencer
Vous disposez des informations suivantes sur le nœud défaillant :

* *Nom du nœud* : vous devez installer le dispositif de services en utilisant le même nom de nœud que le nœud défaillant.  Le nom du nœud est le nom d'hôte (nom du système).
* *Adresses IP* : vous pouvez attribuer au dispositif de services les mêmes adresses IP que le nœud défaillant, ce qui est l'option préférée, ou vous pouvez sélectionner une nouvelle adresse IP inutilisée sur chaque réseau.


.À propos de cette tâche
Exécutez cette procédure uniquement si vous récupérez un nœud défaillant hébergé sur VMware ou Linux et que vous le remplacez par un nœud hébergé sur un dispositif de services.

.Étapes
. Suivez les instructions pour installer un nouveau dispositif de services. Voir https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/index.html["Démarrage rapide pour l'installation du matériel"^] .
. Lorsque vous êtes invité à saisir un nom de nœud, utilisez le nom de nœud du nœud défaillant.

