---
permalink: maintain/modifying-dns-configuration-for-single-grid-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, dns, modify dns 
summary: Plutôt que de configurer le DNS globalement pour l’ensemble du déploiement, vous pouvez exécuter un script pour configurer le DNS différemment pour chaque nœud de grille. 
---
= Modifier la configuration DNS pour un nœud de grille unique
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Plutôt que de configurer le DNS globalement pour l’ensemble du déploiement, vous pouvez exécuter un script pour configurer le DNS différemment pour chaque nœud de grille.

En général, vous devez utiliser l'option *MAINTENANCE* > *Réseau* > *Serveurs DNS* sur le Gestionnaire de grille pour configurer les serveurs DNS. Utilisez le script suivant uniquement si vous devez utiliser différents serveurs DNS pour différents nœuds de grille.

.Étapes
. Connectez-vous au nœud d’administration principal :
+
.. Entrez la commande suivante : `ssh admin@_primary_Admin_Node_IP_`
.. Entrez le mot de passe indiqué dans le `Passwords.txt` déposer.
.. Entrez la commande suivante pour passer en root : `su -`
.. Entrez le mot de passe indiqué dans le `Passwords.txt` déposer.
+
Lorsque vous êtes connecté en tant que root, l'invite passe de `$` à `#` .

.. Ajoutez la clé privée SSH à l’agent SSH.  Entrer: `ssh-add`
.. Saisissez le mot de passe d'accès SSH répertorié dans le `Passwords.txt` déposer.


. [[log_in_to_node]]Connectez-vous au nœud que vous souhaitez mettre à jour avec une configuration DNS personnalisée : `ssh _node_IP_address_`
. Exécutez le script de configuration DNS : `setup_resolv.rb.`
+
Le script répond avec la liste des commandes prises en charge.

+
[listing]
----
Tool to modify external name servers

available commands:
  add search <domain>
               add a specified domain to search list
               e.g.> add search netapp.com
  remove search <domain>
               remove a specified domain from list
               e.g.> remove search netapp.com
  add nameserver <ip>
               add a specified IP address to the name server list
               e.g.> add nameserver 192.0.2.65
  remove nameserver <ip>
               remove a specified IP address from list
               e.g.> remove nameserver 192.0.2.65
  remove nameserver all
               remove all nameservers from list
  save         write configuration to disk and quit
  abort        quit without saving changes
  help         display this help message


Current list of name servers:
    192.0.2.64
Name servers inherited from global DNS configuration:
    192.0.2.126
    192.0.2.127
Current list of search entries:
    netapp.com

Enter command [`add search <domain>|remove search <domain>|add nameserver <ip>`]
              [`remove nameserver <ip>|remove nameserver all|save|abort|help`]
----
. Ajoutez l’adresse IPv4 d’un serveur qui fournit un service de nom de domaine pour votre réseau : `add <nameserver IP_address>`
. Répétez le `add nameserver` commande pour ajouter des serveurs de noms.
. Suivez les instructions demandées pour les autres commandes.
. Enregistrez vos modifications et quittez l'application : `save`
. [[close_cmd_shell]]Fermez l'interpréteur de commandes sur le serveur : `exit`
. Pour chaque nœud de la grille, répétez les étapes à partir de<<log_in_to_node,connexion au nœud>> à travers<<close_cmd_shell,fermeture de l'interpréteur de commandes>> .
. Lorsque vous n’avez plus besoin d’un accès sans mot de passe à d’autres serveurs, supprimez la clé privée de l’agent SSH.  Entrer: `ssh-add -D`

