---
permalink: maintain/preparing-appliance-for-reinstallation-platform-replacement-only.html 
sidebar: sidebar 
keywords: storagegrid, recover, appliance, reinstallation appliance, reinstall appliance 
summary: 'Lors de la récupération d"un nœud de grille hébergé sur un dispositif de services, vous devez d"abord préparer le dispositif pour la réinstallation du logiciel StorageGRID .' 
---
= Préparer l'appareil pour la réinstallation (remplacement de la plate-forme uniquement)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lors de la récupération d'un nœud de grille hébergé sur un dispositif de services, vous devez d'abord préparer le dispositif pour la réinstallation du logiciel StorageGRID .

Effectuez cette procédure uniquement si vous remplacez un nœud défaillant hébergé sur un dispositif de services.  Ne suivez pas ces étapes si le nœud défaillant était initialement hébergé sur VMware ou sur un hôte Linux.

.Étapes
. Connectez-vous au nœud de grille défaillant :
+
.. Entrez la commande suivante : `ssh admin@_grid_node_IP_`
.. Entrez le mot de passe indiqué dans le `Passwords.txt` déposer.
.. Entrez la commande suivante pour passer en root : `su -`
.. Entrez le mot de passe indiqué dans le `Passwords.txt` déposer.


+
Lorsque vous êtes connecté en tant que root, l'invite passe de `$` à `#` .

. Préparez l'appareil pour l'installation du logiciel StorageGRID .  Entrer: `sgareinstall`
. Lorsque vous êtes invité à continuer, entrez : `y`
+
L'appareil redémarre et votre session SSH se termine.  Il faut généralement environ 5 minutes pour que le programme d'installation de l'appliance StorageGRID soit disponible, bien que dans certains cas, vous devrez peut-être attendre jusqu'à 30 minutes.

+
L'appareil de services est réinitialisé et les données sur le nœud de grille ne sont plus accessibles.  Les adresses IP configurées lors du processus d'installation d'origine doivent rester intactes ; cependant, il est recommandé de confirmer cela une fois la procédure terminée.

+
Après avoir exécuté le `sgareinstall` commande, tous les comptes, mots de passe et clés SSH provisionnés par StorageGRID sont supprimés et de nouvelles clés d'hôte sont générées.


