---
permalink: maintain/preparing-appliance-storage-node-for-reinstallation.html 
sidebar: sidebar 
keywords: storagegrid, recover, appliance, reinstallation appliance, reinstall appliance 
summary: 'Lors de la récupération d"un nœud de stockage d"appliance, vous devez d"abord préparer l"appliance pour la réinstallation du logiciel StorageGRID .' 
---
= Préparer le nœud de stockage de l'appareil pour la réinstallation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lors de la récupération d'un nœud de stockage d'appliance, vous devez d'abord préparer l'appliance pour la réinstallation du logiciel StorageGRID .

.Étapes
. Connectez-vous au nœud de stockage défaillant :
+
.. Entrez la commande suivante : `ssh admin@_grid_node_IP_`
.. Entrez le mot de passe indiqué dans le `Passwords.txt` déposer.
.. Entrez la commande suivante pour passer en root : `su -`
.. Entrez le mot de passe indiqué dans le `Passwords.txt` déposer.


+
Lorsque vous êtes connecté en tant que root, l'invite passe de `$` à `#` .

. Préparez le nœud de stockage de l'appliance pour l'installation du logiciel StorageGRID . `sgareinstall`
. Lorsque vous êtes invité à continuer, entrez : `y`
+
L'appareil redémarre et votre session SSH se termine.  Il faut généralement environ 5 minutes pour que le programme d'installation de l'appliance StorageGRID soit disponible, bien que dans certains cas, vous devrez peut-être attendre jusqu'à 30 minutes.

+

CAUTION: N'essayez pas d'accélérer le redémarrage en coupant puis en éteignant l'appareil ou en le réinitialisant.  Vous risquez d'interrompre les mises à niveau automatiques du BIOS, du BMC ou d'autres micrologiciels.

+
Le nœud de stockage de l'appliance StorageGRID est réinitialisé et les données sur le nœud de stockage ne sont plus accessibles.  Les adresses IP configurées lors du processus d'installation d'origine doivent rester intactes ; cependant, il est recommandé de confirmer cela une fois la procédure terminée.

+
Après avoir exécuté le `sgareinstall` commande, tous les comptes, mots de passe et clés SSH provisionnés par StorageGRID sont supprimés et de nouvelles clés d'hôte sont générées.


