---
permalink: maintain/recovering-from-primary-admin-node-failures.html 
sidebar: sidebar 
keywords: storagegrid, recover, primary admin node failure 
summary: 'Vous devez effectuer un ensemble spécifique de tâches pour récupérer après une panne du nœud d"administration principal.  Le nœud d’administration principal héberge le service de nœud de gestion de configuration (CMN) pour la grille.' 
---
= Récupérer après une panne du nœud d'administration principal
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez effectuer un ensemble spécifique de tâches pour récupérer après une panne du nœud d'administration principal.  Le nœud d’administration principal héberge le service de nœud de gestion de configuration (CMN) pour la grille.


CAUTION: Vous devez réparer ou remplacer rapidement un nœud d’administration principal défaillant, sinon la grille risque de perdre sa capacité à ingérer de nouveaux objets.  La période exacte dépend de votre taux d'ingestion d'objets : si vous avez besoin d'une évaluation plus précise du délai de votre grille, contactez le support technique.

Le service de nœud de gestion de configuration (CMN) sur le nœud d'administration principal est responsable de l'émission de blocs d'identifiants d'objets pour la grille.  Ces identifiants sont attribués aux objets au fur et à mesure de leur ingestion.  Les nouveaux objets ne peuvent pas être ingérés à moins que des identifiants ne soient disponibles.  L'ingestion d'objets peut continuer pendant que le CMN n'est pas disponible, car environ un mois d'approvisionnement en identifiants est mis en cache dans la grille.  Cependant, une fois les identifiants mis en cache épuisés, aucun nouvel objet ne peut être ajouté.

Suivez ces étapes de haut niveau pour récupérer un nœud d’administration principal :

. link:copying-audit-logs-from-failed-primary-admin-node.html["Copier les journaux d'audit du nœud d'administration principal défaillant"]
. link:replacing-primary-admin-node.html["Remplacer le nœud d'administration principal"]
. link:configuring-replacement-primary-admin-node.html["Configurer le nœud d'administration principal de remplacement"]
. link:assess-hotfix-requirement-during-primary-admin-node-recovery.html["Déterminer s'il existe une exigence de correctif pour le nœud d'administration principal récupéré"]
. link:restoring-audit-log-on-recovered-primary-admin-node.html["Restaurer le journal d'audit sur le nœud d'administration principal récupéré"]
. link:restoring-admin-node-database-primary-admin-node.html["Restaurer la base de données du nœud d'administration lors de la récupération d'un nœud d'administration principal"]
. link:restoring-prometheus-metrics-primary-admin-node.html["Restaurer les métriques Prometheus lors de la récupération d'un nœud d'administration principal"]

