---
permalink: maintain/replacing-non-primary-admin-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, replace non-primary admin node, replacing non-primary admin node, non-primary admin node 
summary: Pour récupérer un nœud d’administration non principal, vous devez d’abord remplacer le matériel physique ou virtuel. 
---
= Remplacer le nœud d'administration non principal
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour récupérer un nœud d’administration non principal, vous devez d’abord remplacer le matériel physique ou virtuel.

Vous pouvez remplacer un nœud d'administration non principal défaillant par un nœud d'administration non principal exécuté sur la même plate-forme, ou vous pouvez remplacer un nœud d'administration non principal exécuté sur VMware ou un hôte Linux par un nœud d'administration non principal hébergé sur un dispositif de services.

Utilisez la procédure correspondant à la plate-forme de remplacement que vous sélectionnez pour le nœud.  Une fois la procédure de remplacement du nœud terminée (qui convient à tous les types de nœuds), cette procédure vous dirigera vers l’étape suivante pour la récupération du nœud d’administration non principal.

[cols="1a,2a"]
|===
| Plateforme de remplacement | Procédure 


 a| 
VMware
 a| 
link:all-node-types-replacing-vmware-node.html["Remplacer un nœud VMware"]



 a| 
Linux
 a| 
link:all-node-types-replacing-linux-node.html["Remplacer un nœud Linux"]



 a| 
Appareils de service
 a| 
link:replacing-failed-node-with-services-appliance.html["Remplacer un appareil de service"]



 a| 
OpenStack
 a| 
Les fichiers de disque et les scripts de machine virtuelle fournis par NetApp pour OpenStack ne sont plus pris en charge pour les opérations de récupération.  Si vous devez récupérer un nœud exécuté dans un déploiement OpenStack, téléchargez les fichiers pour votre système d'exploitation Linux.  Ensuite, suivez la procédure pourlink:all-node-types-replacing-linux-node.html["remplacement d'un nœud Linux"] .

|===