---
permalink: maintain/reviewing-ilm-policy-and-storage-configuration.html 
sidebar: sidebar 
keywords: storagegrid, restore, ilm policy, storage configuration 
summary: Si vous prévoyez de mettre hors service un nœud de stockage, vous devez consulter la politique ILM de votre système StorageGRID avant de démarrer le processus de mise hors service. 
---
= Examiner la politique ILM et la configuration du stockage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous prévoyez de mettre hors service un nœud de stockage, vous devez consulter la politique ILM de votre système StorageGRID avant de démarrer le processus de mise hors service.

Lors de la mise hors service, toutes les données d'objet sont migrées du nœud de stockage mis hors service vers d'autres nœuds de stockage.


NOTE: La politique ILM que vous avez _pendant_ la mise hors service sera celle utilisée _après_ la mise hors service.  Vous devez vous assurer que cette politique répond à vos exigences en matière de données avant de commencer la mise hors service et une fois celle-ci terminée.

Vous devriez revoir les règles de chaquelink:../ilm/creating-ilm-policy.html["politique ILM active"] pour garantir que le système StorageGRID continuera à disposer d'une capacité suffisante du type correct et aux emplacements corrects pour permettre la mise hors service d'un nœud de stockage.

Considérez ce qui suit :

* Sera-t-il possible pour les services d’évaluation ILM de copier les données d’objet de manière à ce que les règles ILM soient satisfaites ?
* Que se passe-t-il si un site devient temporairement indisponible pendant le démantèlement ?  Des copies supplémentaires peuvent-elles être réalisées dans un autre endroit ?
* Comment le processus de déclassement affectera-t-il la distribution finale du contenu ?  Comme décrit danslink:consolidating-storage-nodes.html["Consolider les nœuds de stockage"] , tu devraislink:../expand/index.html["ajouter de nouveaux nœuds de stockage"] avant de mettre hors service les anciens.  Si vous ajoutez un nœud de stockage de remplacement plus grand après la mise hors service d'un nœud de stockage plus petit, les anciens nœuds de stockage pourraient être proches de leur capacité et le nouveau nœud de stockage pourrait n'avoir presque aucun contenu.  La plupart des opérations d’écriture pour les nouvelles données d’objet seraient alors dirigées vers le nouveau nœud de stockage, réduisant ainsi l’efficacité globale des opérations du système.
* Le système comprendra-t-il à tout moment suffisamment de nœuds de stockage pour satisfaire les politiques ILM actives ?
+

NOTE: Une politique ILM qui ne peut pas être satisfaite entraînera des retards et des alertes, et pourrait interrompre le fonctionnement du système StorageGRID .



Vérifiez que la topologie proposée qui résultera du processus de déclassement satisfait la politique ILM en évaluant les zones répertoriées dans le tableau.

[cols="1a,2a"]
|===
| Zone à évaluer | Ce qu'il faut prendre en compte 


 a| 
Capacité disponible
 a| 
Y aura-t-il suffisamment de capacité de stockage pour accueillir toutes les données d'objet stockées dans le système StorageGRID , y compris les copies permanentes des données d'objet actuellement stockées sur le nœud de stockage à mettre hors service ?

Y aura-t-il suffisamment de capacité pour gérer la croissance prévue des données d’objets stockées pendant un intervalle de temps raisonnable après la fin du déclassement ?



 a| 
Lieu de stockage
 a| 
S'il reste suffisamment de capacité dans le système StorageGRID dans son ensemble, la capacité est-elle aux bons endroits pour satisfaire les règles métier du système StorageGRID ?



 a| 
Type de stockage
 a| 
Y aura-t-il suffisamment de stockage du type approprié une fois le déclassement terminé ?

Par exemple, les règles ILM peuvent déplacer du contenu d’un type de stockage vers un autre à mesure que le contenu vieillit.  Dans ce cas, vous devez vous assurer qu'un espace de stockage suffisant du type approprié est disponible dans la configuration finale du système StorageGRID .

|===