---
permalink: maintain/service-with-error-state.html 
sidebar: sidebar 
keywords: storagegrid, recover, service error state, error, error state 
summary: Si vous détectez qu’un service est entré dans un état d’erreur, essayez de redémarrer le service. 
---
= Service avec un état d'erreur
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous détectez qu’un service est entré dans un état d’erreur, essayez de redémarrer le service.

.Avant de commencer
Vous avez le `Passwords.txt` déposer.

.À propos de cette tâche
Le Gestionnaire de serveur surveille les services et redémarre ceux qui se sont arrêtés de manière inattendue.  Si un service échoue, le Gestionnaire de serveur tente de le redémarrer.  Si trois tentatives de démarrage d'un service échouent dans un délai de cinq minutes, le service entre dans un état d'erreur.  Le Gestionnaire de serveur ne tente pas d'effectuer un autre redémarrage.

.Étapes
. Connectez-vous au nœud de grille :
+
.. Entrez la commande suivante : `ssh admin@_grid_node_IP_`
.. Entrez le mot de passe indiqué dans le `Passwords.txt` déposer.
.. Entrez la commande suivante pour passer en root : `su -`
.. Entrez le mot de passe indiqué dans le `Passwords.txt` déposer.


+
Lorsque vous êtes connecté en tant que root, l'invite passe de `$` à `#` .

. Confirmer l’état d’erreur du service : `service _servicename_ status`
+
Par exemple:

+
[listing]
----
service ldr status
----
+
Si le service est dans un état d’erreur, le message suivant est renvoyé : `_servicename_ in error state` . Par exemple:

+
[listing]
----
ldr in error state
----
+

NOTE: Si l'état du service est `disabled` , voir les instructions pourlink:using-donotstart-file.html["suppression d'un fichier DoNotStart pour un service"] .

. Tentez de supprimer l’état d’erreur en redémarrant le service : `service _servicename_ restart`
+
Si le service ne parvient pas à redémarrer, contactez le support technique.

. Déconnectez-vous de l'interpréteur de commandes : `exit`

