---
permalink: maintain/shutting-down-grid-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, node shutdown, shut down node, node shut down 
summary: 'Vous pouvez arrêter un nœud de grille à partir de l"interpréteur de commandes du nœud.' 
---
= Arrêter le nœud du réseau
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez arrêter un nœud de grille à partir de l'interpréteur de commandes du nœud.

.Avant de commencer
* Vous avez le `Passwords.txt` déposer.


.À propos de cette tâche
Avant d’effectuer cette procédure, passez en revue ces considérations :

* En général, vous ne devez pas arrêter plus d’un nœud à la fois pour éviter les interruptions.
* N'arrêtez pas un nœud pendant une procédure de maintenance, sauf si la documentation ou le support technique vous le demande explicitement.
* Le processus d’arrêt est basé sur l’endroit où le nœud est installé, comme suit :
+
** L’arrêt d’un nœud VMware arrête la machine virtuelle.
** L’arrêt d’un nœud Linux arrête le conteneur.
** L’arrêt d’un nœud d’appliance StorageGRID arrête le contrôleur de calcul.


* Si vous prévoyez d'arrêter plusieurs nœuds de stockage sur un site, arrêtez d'ingérer des objets sur ce site pendant environ une heure avant d'arrêter les nœuds.
+
Si une règle ILM utilise l'option d'ingestion *Double validation* (ou si une règle utilise l'option *Équilibrée* et que toutes les copies requises ne peuvent pas être créées immédiatement), StorageGRID valide immédiatement tous les objets nouvellement ingérés sur deux nœuds de stockage sur le même site et évalue ILM ultérieurement.  Si plusieurs nœuds de stockage d'un site sont arrêtés, vous risquez de ne pas pouvoir accéder aux objets nouvellement ingérés pendant la durée de l'arrêt.  Les opérations d’écriture peuvent également échouer si trop peu de nœuds de stockage restent disponibles sur le site. Voir link:../ilm/index.html["Gérer les objets avec ILM"] .



.Étapes
. Connectez-vous au nœud de grille :
+
.. Entrez la commande suivante : `ssh admin@_grid_node_IP_`
.. Entrez le mot de passe indiqué dans le `Passwords.txt` déposer.
.. Entrez la commande suivante pour passer en root : `su -`
.. Entrez le mot de passe indiqué dans le `Passwords.txt` déposer.


+
Lorsque vous êtes connecté en tant que root, l'invite passe de `$` à `#` .

. Arrêter tous les services : `service servermanager stop`
+
L'arrêt des services peut prendre jusqu'à 15 minutes et vous souhaiterez peut-être vous connecter au système à distance pour surveiller le processus d'arrêt.

. Si le nœud s'exécute sur une machine virtuelle VMware ou s'il s'agit d'un nœud d'appliance, émettez la commande d'arrêt : `shutdown -h now`
+
Effectuez cette étape quel que soit le résultat de l' `service servermanager stop` commande.

+

NOTE: Après avoir émis le `shutdown -h now` commande sur un nœud d'appareil, vous devez redémarrer l'appareil pour redémarrer le nœud.

+
Pour l'appareil, cette commande arrête le contrôleur, mais l'appareil est toujours sous tension.  Vous devez compléter l’étape suivante.

. Si vous mettez hors tension un nœud d’appareil, suivez les étapes correspondant à votre appareil.
+
[role="tabbed-block"]
====
.SG6160
--
.. Coupez l’alimentation du contrôleur de stockage SG6100-CN.
.. Attendez que le voyant d’alimentation bleu du contrôleur de stockage SG6100-CN s’éteigne.


--
.SGF6112
--
.. Coupez l’alimentation de l’appareil.
.. Attendez que le voyant d’alimentation bleu s’éteigne.


--
.SG6000
--
.. Attendez que le voyant vert Cache Active à l’arrière des contrôleurs de stockage s’éteigne.
+
Cette LED s'allume lorsque les données mises en cache doivent être écrites sur les lecteurs.  Vous devez attendre que cette LED s'éteigne avant de couper l'alimentation.

.. Coupez l’alimentation de l’appareil et attendez que le voyant d’alimentation bleu s’éteigne.


--
.SG5800
--
.. Attendez que le voyant vert Cache Active à l’arrière du contrôleur de stockage s’éteigne.
+
Cette LED s'allume lorsque les données mises en cache doivent être écrites sur les lecteurs.  Vous devez attendre que cette LED s'éteigne avant de couper l'alimentation.

.. Depuis la page d'accueil de SANtricity System Manager, sélectionnez *Afficher les opérations en cours*.
.. Confirmez que toutes les opérations sont terminées avant de passer à l’étape suivante.
.. Éteignez les deux interrupteurs d’alimentation sur l’étagère du contrôleur et attendez que tous les voyants de l’étagère du contrôleur s’éteignent.


--
.SG5700
--
.. Attendez que le voyant vert Cache Active à l’arrière du contrôleur de stockage s’éteigne.
+
Cette LED s'allume lorsque les données mises en cache doivent être écrites sur les lecteurs.  Vous devez attendre que cette LED s'éteigne avant de couper l'alimentation.

.. Coupez l’alimentation de l’appareil et attendez que toutes les activités des voyants LED et de l’affichage à sept segments s’arrêtent.


--
.SG100 ou SG1000
--
.. Coupez l’alimentation de l’appareil.
.. Attendez que le voyant d’alimentation bleu s’éteigne.


--
====

