---
permalink: maintain/starting-or-restarting-service.html 
sidebar: sidebar 
keywords: storagegrid, recover, service, start service, restart service 
summary: Vous devrez peut-être démarrer un service qui a été arrêté, ou vous devrez peut-être arrêter et redémarrer un service. 
---
= Démarrer ou redémarrer le service
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devrez peut-être démarrer un service qui a été arrêté, ou vous devrez peut-être arrêter et redémarrer un service.

.Avant de commencer
Vous avez le `Passwords.txt` déposer.

.Étapes
. Connectez-vous au nœud de grille :
+
.. Entrez la commande suivante : `ssh admin@_grid_node_IP_`
.. Entrez le mot de passe indiqué dans le `Passwords.txt` déposer.
.. Entrez la commande suivante pour passer en root : `su -`
.. Entrez le mot de passe indiqué dans le `Passwords.txt` déposer.


+
Lorsque vous êtes connecté en tant que root, l'invite passe de `$` à `#` .

. Décidez quelle commande émettre, selon que le service est en cours d’exécution ou arrêté.
+
** Si le service est actuellement arrêté, utilisez le `start` commande pour démarrer le service manuellement : `service _servicename_ start`
+
Par exemple:

+
[listing]
----
service ldr start
----
** Si le service est actuellement en cours d'exécution, utilisez le `restart` commande pour arrêter le service puis le redémarrer : `service _servicename_ restart`
+
Par exemple:

+
[listing]
----
service ldr restart
----
+

NOTE: En utilisant le `restart` commande est la même que l'utilisation de la `stop` commande suivie de la `start` commande.  Vous pouvez émettre `restart` même si le service est actuellement arrêté.



. Déconnectez-vous de l'interpréteur de commandes : `exit`

