---
permalink: maintain/starting-server-manager-and-all-services.html 
sidebar: sidebar 
keywords: storagegrid, recover, server manager, start server manager, start services, start all services 
summary: Vous devrez peut-être démarrer le Gestionnaire de serveur, qui démarre également tous les services sur le nœud de grille. 
---
= Démarrer le Gestionnaire de serveur et tous les services
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devrez peut-être démarrer le Gestionnaire de serveur, qui démarre également tous les services sur le nœud de grille.

.Avant de commencer
Vous avez le `Passwords.txt` déposer.

.À propos de cette tâche
Le démarrage du Gestionnaire de serveur sur un nœud de grille où il est déjà en cours d’exécution entraîne un redémarrage du Gestionnaire de serveur et de tous les services sur le nœud de grille.

.Étapes
. Connectez-vous au nœud de grille :
+
.. Entrez la commande suivante : `ssh admin@_grid_node_IP_`
.. Entrez le mot de passe indiqué dans le `Passwords.txt` déposer.
.. Entrez la commande suivante pour passer en root : `su -`
.. Entrez le mot de passe indiqué dans le `Passwords.txt` déposer.


+
Lorsque vous êtes connecté en tant que root, l'invite passe de `$` à `#` .

. Démarrer le gestionnaire de serveur : `service servermanager start`
. Déconnectez-vous de l'interpréteur de commandes : `exit`

