---
permalink: maintain/step-3-revise-ilm-policy.html 
sidebar: sidebar 
keywords: storagegrid, recover, revise ilm policies 
summary: 'À partir de l"étape 3 (Réviser les politiques ILM) de l"assistant de mise hors service du site, vous pouvez déterminer si le site est référencé par une politique ILM.' 
---
= Étape 3 : Réviser les politiques ILM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
À partir de l'étape 3 (Réviser les politiques ILM) de l'assistant de mise hors service du site, vous pouvez déterminer si le site est référencé par une politique ILM.

.Avant de commencer
Vous avez une bonne compréhension de la façon delink:../ilm/index.html["gérer les objets avec ILM"] .  Vous êtes familiarisé avec la création de pools de stockage et de règles ILM, ainsi qu'avec la simulation et l'activation d'une politique ILM.

.À propos de cette tâche
StorageGRID ne peut pas désactiver un site si une règle ILM dans une politique (active ou inactive) fait référence à ce site.

Si une politique ILM fait référence au site que vous souhaitez mettre hors service, vous devez supprimer ces politiques ou les modifier afin qu'elles répondent aux exigences suivantes :

* Protégez entièrement toutes les données de l'objet.
* Ne faites pas référence au site que vous décommissionnez.
* N'utilisez pas de pools de stockage qui font référence au site ou n'utilisez pas l'option Tous les sites.
* N'utilisez pas de profils de codage d'effacement qui font référence au site.
* N'utilisez pas la règle « Créer 2 copies » des installations StorageGRID 11.6 ou antérieures.



CAUTION: Ne créez jamais une règle ILM à copie unique pour prendre en charge la suppression d'un site.  Une règle ILM qui crée une seule copie répliquée pour une période donnée expose les données à un risque de perte permanente.  Si une seule copie répliquée d’un objet existe, cet objet est perdu si un nœud de stockage échoue ou présente une erreur importante.  Vous perdez également temporairement l’accès à l’objet pendant les procédures de maintenance telles que les mises à niveau.


TIP: Si vous effectuez une _décommission d'un site connecté_, vous devez prendre en compte la manière dont StorageGRID doit gérer les données d'objet actuellement présentes sur le site que vous souhaitez supprimer.  En fonction de vos exigences en matière de protection des données, de nouvelles règles peuvent déplacer les données d'objet existantes vers différents sites ou supprimer toutes les copies d'objet supplémentaires qui ne sont plus nécessaires.

Contactez le support technique si vous avez besoin d’aide pour concevoir une nouvelle politique.

.Étapes
. À partir de l’étape 3 (Réviser les politiques ILM), déterminez si des politiques ILM font référence au site que vous avez sélectionné pour la mise hors service.
. Si aucune politique n'est répertoriée, sélectionnez *Suivant* pour accéder àlink:step-4-remove-ilm-references.html["Étape 4 : Supprimer les références ILM"] .
. Si une ou plusieurs stratégies ILM _actives_ sont répertoriées, clonez chaque stratégie existante ou créez de nouvelles stratégies qui ne font pas référence au site en cours de mise hors service :
+
.. Sélectionnez le lien de la politique dans la colonne Nom de la politique.
+
La page des détails de la politique ILM pour la politique apparaît dans un nouvel onglet du navigateur.  La page Site de déclassement restera ouverte sur l’autre onglet.

.. Suivez ces directives et instructions selon vos besoins :
+
*** Travailler avec les règles ILM :
+
**** link:../ilm/creating-storage-pool.html["Créer un ou plusieurs pools de stockage"]qui ne font pas référence au site.
**** link:../ilm/working-with-ilm-rules-and-ilm-policies.html["Modifier ou remplacer les règles"]qui font référence au site.
+

NOTE: Ne sélectionnez pas la règle *Créer 2 copies* car cette règle utilise le pool de stockage *Tous les nœuds de stockage*, ce qui n'est pas autorisé.



*** Travailler avec les politiques ILM :
+
**** link:../ilm/working-with-ilm-rules-and-ilm-policies.html#clone-ilm-policy["Cloner une politique ILM existante"]oulink:../ilm/creating-ilm-policy.html["créer une nouvelle politique ILM"] .
**** Assurez-vous que la règle par défaut et les autres règles ne font pas référence au site.
+

CAUTION: Vous devez confirmer que les règles ILM sont dans le bon ordre.  Lorsque la politique est activée, les objets nouveaux et existants sont évalués par les règles dans l'ordre répertorié, en commençant par le haut.





.. Ingérez des objets de test et simulez la politique pour garantir que les règles correctes sont appliquées.
+

CAUTION: Des erreurs dans une politique ILM peuvent entraîner une perte de données irrécupérable.  Examinez et simulez attentivement la politique avant de l’activer pour confirmer qu’elle fonctionnera comme prévu.

+

CAUTION: Lorsque vous activez une nouvelle stratégie ILM, StorageGRID l’utilise pour gérer tous les objets, y compris les objets existants et les objets nouvellement ingérés.  Avant d’activer une nouvelle stratégie ILM, vérifiez toutes les modifications apportées au placement des objets répliqués et codés par effacement existants.  La modification de l'emplacement d'un objet existant peut entraîner des problèmes de ressources temporaires lorsque les nouveaux emplacements sont évalués et mis en œuvre.

.. Activez les nouvelles politiques et assurez-vous que les anciennes politiques sont désormais inactives.
+
Si vous souhaitez activer plusieurs politiques,link:../ilm/creating-ilm-policy.html#activate-ilm-policy["suivez les étapes pour créer des balises de politique ILM"] .

+
Si vous effectuez une mise hors service d'un site connecté, StorageGRID commence à supprimer les données d'objet du site sélectionné dès que vous activez la nouvelle stratégie ILM.  Le déplacement ou la suppression de toutes les copies d’objets peut prendre des semaines.  Bien que vous puissiez démarrer en toute sécurité la mise hors service d'un site alors que les données d'objet existent toujours sur le site, la procédure de mise hors service s'exécutera plus rapidement et avec moins d'interruptions et d'impacts sur les performances si vous autorisez le déplacement des données du site avant de démarrer la procédure de mise hors service proprement dite (en sélectionnant *Démarrer la mise hors service* à l'étape 5 de l'assistant).



. Pour chaque politique _inactive_, modifiez-la ou supprimez-la en sélectionnant d'abord le lien de chaque politique comme décrit dans les étapes précédentes.
+
** link:../ilm/working-with-ilm-rules-and-ilm-policies.html#edit-ilm-policy["Modifier la politique"]il ne s'agit donc pas du site à démanteler.
** link:../ilm/working-with-ilm-rules-and-ilm-policies.html#remove-ilm-policy["Supprimer une politique"] .


. Une fois que vous avez terminé d’apporter des modifications aux règles et politiques ILM, aucune autre politique ne devrait être répertoriée à l’étape 3 (Réviser les politiques ILM). Sélectionnez *Suivant*.
+
L'étape 4 (Supprimer les références ILM) apparaît.


