---
permalink: maintain/storagegrid-hotfix-procedure.html 
sidebar: sidebar 
keywords: apply hotfix, install hotfix, replace primary admin node 
summary: Vous devrez peut-être appliquer un correctif à votre système StorageGRID si des problèmes avec le logiciel sont détectés et résolus entre les versions de fonctionnalités. 
---
= Procédure de correctif logiciel StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devrez peut-être appliquer un correctif à votre système StorageGRID si des problèmes avec le logiciel sont détectés et résolus entre les versions de fonctionnalités.

Les correctifs StorageGRID contiennent des modifications logicielles qui sont rendues disponibles en dehors d'une fonctionnalité ou d'une version de correctif.  Les mêmes modifications sont incluses dans une future version.  De plus, chaque version de correctif contient un récapitulatif de tous les correctifs précédents dans la version de fonctionnalité ou de correctif.



== Considérations relatives à l'application d'un correctif

Vous ne pouvez pas appliquer un correctif StorageGRID lorsqu'une autre procédure de maintenance est en cours d'exécution.  Par exemple, vous ne pouvez pas appliquer un correctif pendant qu'une procédure de mise hors service, d'extension ou de récupération est en cours d'exécution.


NOTE: Si une procédure de mise hors service d'un nœud ou d'un site est suspendue, vous pouvez appliquer un correctif en toute sécurité.  En outre, vous pourrez peut-être appliquer un correctif lors des dernières étapes d'une procédure de mise à niveau de StorageGRID .  Consultez les instructions de mise à niveau du logiciel StorageGRID pour plus de détails.

Une fois le correctif téléchargé dans le gestionnaire de grille, il est appliqué automatiquement au nœud d'administration principal.  Ensuite, vous pouvez approuver l’application du correctif au reste des nœuds de votre système StorageGRID .

Si un correctif ne parvient pas à être appliqué à un ou plusieurs nœuds, la raison de l'échec apparaît dans la colonne Détails du tableau de progression du correctif.  Vous devez résoudre tous les problèmes à l’origine des échecs, puis réessayer l’ensemble du processus.  Les nœuds avec une application réussie du correctif seront ignorés dans les applications ultérieures.  Vous pouvez réessayer le processus de correctif en toute sécurité autant de fois que nécessaire jusqu'à ce que tous les nœuds aient été mis à jour.  Le correctif doit être installé avec succès sur tous les nœuds de la grille pour que l'application soit complète.

Bien que les nœuds de grille soient mis à jour avec la nouvelle version du correctif, les modifications réelles d'un correctif peuvent uniquement affecter des services spécifiques sur des types de nœuds spécifiques.  Par exemple, un correctif peut uniquement affecter le service LDR sur les nœuds de stockage.



== Comment les correctifs sont appliqués pour la récupération et l'extension

Une fois qu'un correctif a été appliqué à votre grille, le nœud d'administration principal installe automatiquement la même version de correctif sur tous les nœuds restaurés par des opérations de récupération ou ajoutés dans une extension.

Cependant, si vous devez récupérer le nœud d'administration principal, vous devez installer manuellement la version StorageGRID correcte, puis appliquer le correctif.  La version finale de StorageGRID du nœud d’administration principal doit correspondre à la version des autres nœuds de la grille.

L'exemple suivant illustre comment appliquer un correctif lors de la récupération du nœud d'administration principal :

. Supposons que la grille exécute une version StorageGRID 11._A.B_ avec le dernier correctif.  La « version grille » est 11._A.B.y_.
. Le nœud d’administration principal échoue.
. Vous redéployez le nœud d’administration principal à l’aide de StorageGRID 11._A.B_ et effectuez la procédure de récupération.
+

NOTE: Comme requis pour correspondre à la version de la grille, vous pouvez utiliser une version mineure lors du déploiement du nœud ; vous n’avez pas besoin de déployer d’abord la version majeure.

. Vous appliquez ensuite le correctif 11._A.B.y_ au nœud d’administration principal.


Pour plus d'informations, consultez la section link:configuring-replacement-primary-admin-node.html["Configurer le nœud d'administration principal de remplacement"] .
