---
permalink: maintain/viewing-current-status-of-service.html 
sidebar: sidebar 
keywords: storagegrid, recover, service, status 
summary: Vous pouvez afficher l’état actuel d’un service exécuté sur un nœud de grille à tout moment. 
---
= Afficher l'état actuel du service
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez afficher l’état actuel d’un service exécuté sur un nœud de grille à tout moment.

.Avant de commencer
Vous avez le `Passwords.txt` déposer.

.Étapes
. Connectez-vous au nœud de grille :
+
.. Entrez la commande suivante : `ssh admin@_grid_node_IP_`
.. Entrez le mot de passe indiqué dans le `Passwords.txt` déposer.
.. Entrez la commande suivante pour passer en root : `su -`
.. Entrez le mot de passe indiqué dans le `Passwords.txt` déposer.


+
Lorsque vous êtes connecté en tant que root, l'invite passe de `$` à `#` .

. Afficher l'état actuel d'un service exécuté sur un nœud de grille : `*service _servicename_ status* L'état actuel du service demandé exécuté sur le nœud de grille est signalé (en cours d'exécution ou non). Par exemple:
+
[listing]
----
cmn running for 1d, 14h, 21m, 2s
----
. Déconnectez-vous de l'interpréteur de commandes : `*exit*`

