---
permalink: primer/hybrid-clouds-with-storagegrid.html 
sidebar: sidebar 
keywords: hybrid cloud, cloud storage pool, platform services, fabricpool, ontap 
summary: 'Utilisez StorageGRID dans une configuration de cloud hybride en mettant en œuvre une gestion des données basée sur des politiques pour stocker des objets dans des pools de stockage cloud, en exploitant les services de la plateforme StorageGRID et en hiérarchisant les données d" ONTAP vers StorageGRID avec NetApp FabricPool.' 
---
= Clouds hybrides avec StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilisez StorageGRID dans une configuration de cloud hybride en mettant en œuvre une gestion des données basée sur des politiques pour stocker des objets dans des pools de stockage cloud, en exploitant les services de la plateforme StorageGRID et en hiérarchisant les données d' ONTAP vers StorageGRID avec NetApp FabricPool.



== Pools de stockage cloud

Les pools de stockage cloud vous permettent de stocker des objets en dehors du système StorageGRID .  Par exemple, vous souhaiterez peut-être déplacer des objets rarement consultés vers un stockage cloud moins coûteux, tel qu'Amazon S3 Glacier, S3 Glacier Deep Archive, Google Cloud ou le niveau d'accès Archive dans le stockage Microsoft Azure Blob.  Ou, vous souhaiterez peut-être conserver une sauvegarde cloud des objets StorageGRID , qui peut être utilisée pour récupérer des données perdues en raison d'une défaillance d'un volume de stockage ou d'un nœud de stockage.

Le stockage de partenaires tiers est également pris en charge, y compris le stockage sur disque et sur bande.


NOTE: L’utilisation de pools de stockage Cloud avec FabricPool n’est pas prise en charge en raison de la latence supplémentaire nécessaire pour récupérer un objet à partir de la cible du pool de stockage Cloud.



== Services de la plateforme S3

Les services de la plateforme S3 vous offrent la possibilité d'utiliser des services distants comme points de terminaison pour la réplication d'objets, les notifications d'événements ou l'intégration de la recherche.  Les services de plateforme fonctionnent indépendamment des règles ILM de la grille et sont activés pour les compartiments S3 individuels.  Les services suivants sont pris en charge :

* Le service de réplication CloudMirror met automatiquement en miroir les objets spécifiés dans un compartiment S3 cible, qui peut se trouver sur Amazon S3 ou sur un deuxième système StorageGRID .
* Le service de notification d'événements envoie des messages sur les actions spécifiées à un point de terminaison externe qui prend en charge la réception d'événements Simple Notification Service (Amazon SNS).
* Le service d'intégration de recherche envoie des métadonnées d'objet à un service Elasticsearch externe, ce qui permet de rechercher, de visualiser et d'analyser les métadonnées à l'aide d'outils tiers.


Par exemple, vous pouvez utiliser la réplication CloudMirror pour mettre en miroir des enregistrements clients spécifiques dans Amazon S3, puis exploiter les services AWS pour effectuer des analyses sur vos données.



== Hiérarchisation des données ONTAP à l'aide de FabricPool

Vous pouvez réduire le coût du stockage ONTAP en hiérarchisant les données vers StorageGRID à l'aide de FabricPool.  FabricPool permet la hiérarchisation automatisée des données vers des niveaux de stockage d'objets à faible coût, sur site ou hors site.

Contrairement aux solutions de hiérarchisation manuelle, FabricPool réduit le coût total de possession en automatisant la hiérarchisation des données pour réduire le coût de stockage. Il offre les avantages de l'économie du cloud en s'intégrant aux clouds publics et privés, y compris StorageGRID.

.Informations connexes
* link:../ilm/what-cloud-storage-pool-is.html["Qu'est-ce qu'un pool de stockage cloud ?"]
* link:../tenant/what-platform-services-are.html["Gérer les services de la plateforme"]
* link:../fabricpool/index.html["Configurer StorageGRID pour FabricPool"]

