---
permalink: expand/adding-grid-nodes-to-existing-site-or-adding-new-site.html 
sidebar: sidebar 
keywords: grid node, add node, add site, expand, expansion 
summary: 'Suivez cette procédure pour ajouter des nœuds de grille à des sites existants ou pour ajouter un nouveau site.  Vous ne pouvez effectuer qu"un seul type d"extension à la fois.' 
---
= Ajouter des nœuds de grille à un site existant ou ajouter un nouveau site
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Suivez cette procédure pour ajouter des nœuds de grille à des sites existants ou pour ajouter un nouveau site.  Vous ne pouvez effectuer qu'un seul type d'extension à la fois.

.Avant de commencer
* Vous avez lelink:../admin/admin-group-permissions.html["Accès root ou autorisation de maintenance"] .
* Tous les nœuds existants dans la grille sont opérationnels sur tous les sites.
* Toutes les procédures d’extension, de mise à niveau, de mise hors service ou de récupération précédentes sont terminées.
+

NOTE: Vous ne pouvez pas démarrer une extension lorsqu'une autre procédure d'extension, de mise à niveau, de récupération ou de mise hors service active est en cours.  Toutefois, si nécessaire, vous pouvez suspendre une procédure de mise hors service pour démarrer une extension.



.Étapes
. link:updating-subnets-for-grid-network.html["Mettre à jour les sous-réseaux pour Grid Network"] .
. link:deploying-new-grid-nodes.html["Déployer de nouveaux nœuds de grille"] .
. link:performing-expansion.html["Effectuer une expansion"] .

