---
permalink: expand/copying-admin-node-database.html 
sidebar: sidebar 
keywords: copy Admin Node database, alert history, Admin Node expansion 
summary: 'Lors de l"ajout de nœuds d"administration via une procédure d"extension, vous pouvez éventuellement copier la base de données du nœud d"administration principal vers le nouveau nœud d"administration.  La copie de la base de données vous permet de conserver des informations historiques sur les attributs, les alertes et les alertes.' 
---
= Copier la base de données du nœud d'administration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lors de l'ajout de nœuds d'administration via une procédure d'extension, vous pouvez éventuellement copier la base de données du nœud d'administration principal vers le nouveau nœud d'administration.  La copie de la base de données vous permet de conserver des informations historiques sur les attributs, les alertes et les alertes.

.Avant de commencer
* Vous avez terminé les étapes d’extension requises pour ajouter un nœud d’administration.
* Vous avez le `Passwords.txt` déposer.
* Vous disposez de la phrase secrète de provisionnement.


.À propos de cette tâche
Le processus d’activation du logiciel StorageGRID crée une base de données vide pour le service NMS sur le nœud d’administration d’extension.  Lorsque le service NMS démarre sur le nœud d'administration d'extension, il enregistre les informations sur les serveurs et les services qui font actuellement partie du système ou qui sont ajoutés ultérieurement.  Cette base de données de nœud d'administration comprend les informations suivantes :

* Historique des alertes
* Données d'attributs historiques, utilisées dans les graphiques de style hérité sur la page Nœuds


Pour garantir que la base de données du nœud d'administration est cohérente entre les nœuds, vous pouvez copier la base de données du nœud d'administration principal vers le nœud d'administration d'extension.


NOTE: La copie de la base de données du nœud d'administration principal (the__source Admin Node__) vers un nœud d'administration d'extension peut prendre jusqu'à plusieurs heures.  Pendant cette période, le Grid Manager est inaccessible.

Suivez ces étapes pour arrêter le service MI et le service API de gestion sur le nœud d’administration principal et le nœud d’administration d’extension avant de copier la base de données.

.Étapes
. Effectuez les étapes suivantes sur le nœud d’administration principal :
+
.. Connectez-vous au nœud d'administration :
+
... Entrez la commande suivante : `ssh admin@_grid_node_IP_`
... Entrez le mot de passe indiqué dans le `Passwords.txt` déposer.
... Entrez la commande suivante pour passer en root : `su -`
... Entrez le mot de passe indiqué dans le `Passwords.txt` déposer.


.. Exécutez la commande suivante : `recover-access-points`
.. Saisissez la phrase secrète d’approvisionnement.
.. Arrêter le service MI : `service mi stop`
.. Arrêtez le service d'interface de programmation d'application de gestion (mgmt-api) : `service mgmt-api stop`


. Effectuez les étapes suivantes sur le nœud d’administration d’extension :
+
.. Connectez-vous au nœud d'administration de l'extension :
+
... Entrez la commande suivante : `ssh admin@_grid_node_IP_`
... Entrez le mot de passe indiqué dans le `Passwords.txt` déposer.
... Entrez la commande suivante pour passer en root : `su -`
... Entrez le mot de passe indiqué dans le `Passwords.txt` déposer.


.. Arrêter le service MI : `service mi stop`
.. Arrêtez le service mgmt-api : `service mgmt-api stop`
.. Ajoutez la clé privée SSH à l’agent SSH.  Entrer:``ssh-add``
.. Saisissez le mot de passe d'accès SSH répertorié dans le `Passwords.txt` déposer.
.. Copiez la base de données du nœud d'administration source vers le nœud d'administration d'extension : `/usr/local/mi/bin/mi-clone-db.sh _Source_Admin_Node_IP_`
.. Lorsque vous y êtes invité, confirmez que vous souhaitez écraser la base de données MI sur le nœud d’administration d’extension.
+
La base de données et ses données historiques sont copiées sur le nœud d'administration d'extension.  Une fois l’opération de copie terminée, le script démarre le nœud d’administration d’extension.

.. Lorsque vous n’avez plus besoin d’un accès sans mot de passe à d’autres serveurs, supprimez la clé privée de l’agent SSH.  Entrer:``ssh-add -D``


. Redémarrez les services sur le nœud d’administration principal : `service servermanager start`

