---
permalink: expand/copying-audit-logs.html 
sidebar: sidebar 
keywords: copy audit log, Admin Node expansion, 
summary: 'Lorsque vous ajoutez un nouveau nœud d"administration via une procédure d"extension, son service AMS enregistre uniquement les événements et les actions qui se produisent après son adhésion au système. Si nécessaire, vous pouvez copier les journaux d"audit d"un nœud d"administration précédemment installé vers le nouveau nœud d"administration d"extension afin qu"il soit synchronisé avec le reste du système StorageGRID .' 
---
= Copier les journaux d'audit
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque vous ajoutez un nouveau nœud d'administration via une procédure d'extension, son service AMS enregistre uniquement les événements et les actions qui se produisent après son adhésion au système. Si nécessaire, vous pouvez copier les journaux d'audit d'un nœud d'administration précédemment installé vers le nouveau nœud d'administration d'extension afin qu'il soit synchronisé avec le reste du système StorageGRID .

.Avant de commencer
* Vous avez terminé les étapes d’extension requises pour ajouter un nœud d’administration.
* Vous avez le `Passwords.txt` déposer.


.À propos de cette tâche
Pour rendre les messages d'audit historiques disponibles sur un nouveau nœud d'administration, vous devez copier manuellement les fichiers journaux d'audit d'un nœud d'administration existant vers le nœud d'administration d'extension.

[NOTE]
====
Par défaut, les informations d’audit sont envoyées au journal d’audit sur les nœuds d’administration.  Vous pouvez ignorer ces étapes si l’une des situations suivantes s’applique :

* Vous avez configuré un serveur Syslog externe et les journaux d'audit sont désormais envoyés au serveur Syslog au lieu des nœuds d'administration.
* Vous avez explicitement spécifié que les messages d’audit doivent être enregistrés uniquement sur les nœuds locaux qui les ont générés.


Voirlink:../monitor/configure-audit-messages.html["Configurer les messages d'audit et les destinations des journaux"] pour plus de détails.

====
.Étapes
. Connectez-vous au nœud d’administration principal :
+
.. Entrez la commande suivante : `ssh _admin@_primary_Admin_Node_IP_`
.. Entrez le mot de passe indiqué dans le `Passwords.txt` déposer.
.. Entrez la commande suivante pour passer en root : `su -`
.. Entrez le mot de passe indiqué dans le `Passwords.txt` déposer.
+
Lorsque vous êtes connecté en tant que root, l'invite passe de `$` à `#` .



. Arrêtez le service AMS pour l'empêcher de créer un nouveau fichier : `service ams stop`
. Accédez au répertoire d’exportation d’audit :
+
`cd /var/local/log`

. Renommer la source `audit.log` fichier pour garantir qu'il n'écrase pas le fichier sur le nœud d'administration d'extension sur lequel vous le copiez :
+
[listing]
----
ls -l
mv audit.log _new_name_.txt
----
. Copiez tous les fichiers journaux d’audit vers l’emplacement de destination sur le nœud d’administration d’extension :
+
`scp -p * _IP_address_:/var/local/log`

. Si vous êtes invité à saisir la phrase secrète pour `/root/.ssh/id_rsa` , entrez le mot de passe d'accès SSH pour le nœud d'administration principal répertorié dans le `Passwords.txt` déposer.
. Restaurer l'original `audit.log` déposer:
+
`mv _new_name_.txt audit.log`

. Démarrer le service AMS :
+
`service ams start`

. Se déconnecter du serveur :
+
`exit`

. Connectez-vous au nœud d'administration de l'extension :
+
.. Entrez la commande suivante : `ssh admin@_expansion_Admin_Node_IP_`
.. Entrez le mot de passe indiqué dans le `Passwords.txt` déposer.
.. Entrez la commande suivante pour passer en root : `su -`
.. Entrez le mot de passe indiqué dans le `Passwords.txt` déposer.
+
Lorsque vous êtes connecté en tant que root, l'invite passe de `$` à `#` .



. Mettre à jour les paramètres utilisateur et groupe pour les fichiers journaux d’audit :
+
`cd /var/local/log`

+
`chown ams-user:bycast *`

. Se déconnecter du serveur :
+
`exit`


