---
permalink: expand/index.html 
sidebar: sidebar 
keywords: expand grid 
summary: Vous pouvez étendre la capacité ou les fonctionnalités de votre système StorageGRID sans interrompre les opérations du système. 
---
= Types d'extension
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez étendre la capacité ou les fonctionnalités de votre système StorageGRID sans interrompre les opérations du système.

Une extension StorageGRID vous permet d'ajouter :

* Volumes de stockage vers nœuds de stockage
* Nouveaux nœuds de grille sur un site existant
* Un tout nouveau site


La raison pour laquelle vous effectuez l’extension détermine le nombre de nouveaux nœuds de chaque type que vous devez ajouter et l’emplacement de ces nouveaux nœuds.  Par exemple, les exigences en matière de nœuds sont différentes si vous effectuez une extension pour augmenter la capacité de stockage, ajouter de la capacité de métadonnées ou ajouter de la redondance ou de nouvelles fonctionnalités.

Suivez les étapes correspondant au type d’extension que vous effectuez :

[role="tabbed-block"]
====
.Ajouter des volumes de stockage
--
Suivez les étapes pourlink:adding-storage-volumes-to-storage-nodes.html["ajout de volumes de stockage aux nœuds de stockage"] .

--
.Ajouter des nœuds de grille
--
. Suivez les étapes pourlink:adding-grid-nodes-to-existing-site-or-adding-new-site.html["ajout de nœuds de grille à un site existant"] .
. link:updating-subnets-for-grid-network.html["Mettre à jour les sous-réseaux"] .
. Déployer les nœuds de grille :
+
** link:deploying-new-grid-nodes.html#appliances-deploying-storage-gateway-or-non-primary-admin-nodes["appareils électroménagers"]
** link:deploying-new-grid-nodes.html#vmware-deploy-grid-nodes["VMware"]
** link:deploying-new-grid-nodes.html#linux-deploy-grid-nodes["Linux"]
+

NOTE: « Linux » fait référence à un déploiement Red Hat Enterprise Linux, Ubuntu ou Debian. Pour une liste des versions prises en charge, consultez le https://imt.netapp.com/matrix/#welcome["Outil de matrice d'interopérabilité NetApp (IMT)"^] .



. link:performing-expansion.html["Effectuer l'expansion"] .
. link:configuring-expanded-storagegrid-system.html["Configurer le système étendu"] .


--
.Ajouter un nouveau site
--
. Suivez les étapes pourlink:adding-grid-nodes-to-existing-site-or-adding-new-site.html["Ajout d'un nouveau site"] .
. link:updating-subnets-for-grid-network.html["Mettre à jour les sous-réseaux"] .
. Déployer les nœuds de grille :
+
** link:deploying-new-grid-nodes.html#appliances-deploying-storage-gateway-or-non-primary-admin-nodes["appareils électroménagers"]
** link:deploying-new-grid-nodes.html#vmware-deploy-grid-nodes["VMware"]
** link:deploying-new-grid-nodes.html#linux-deploy-grid-nodes["Linux"]
+

NOTE: « Linux » fait référence à un déploiement Red Hat Enterprise Linux, Ubuntu ou Debian. Pour une liste des versions prises en charge, consultez le https://imt.netapp.com/matrix/#welcome["Outil de matrice d'interopérabilité NetApp (IMT)"^] .



. link:performing-expansion.html["Effectuer l'expansion"] .
. link:configuring-expanded-storagegrid-system.html["Configurer le système étendu"] .


--
====