---
permalink: expand/updating-subnets-for-grid-network.html 
sidebar: sidebar 
keywords: expand, expansion, add subnets, Grid Network 
summary: Lorsque vous ajoutez des nœuds de grille ou un nouveau site dans une extension, vous devrez peut-être mettre à jour ou ajouter des sous-réseaux au réseau de grille. 
---
= Mettre à jour les sous-réseaux pour Grid Network
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque vous ajoutez des nœuds de grille ou un nouveau site dans une extension, vous devrez peut-être mettre à jour ou ajouter des sous-réseaux au réseau de grille.

StorageGRID conserve une liste des sous-réseaux réseau utilisés pour communiquer entre les nœuds de grille sur le réseau de grille (eth0).  Ces entrées incluent les sous-réseaux utilisés pour le réseau Grid par chaque site de votre système StorageGRID ainsi que tous les sous-réseaux utilisés pour NTP, DNS, LDAP ou d'autres serveurs externes accessibles via la passerelle du réseau Grid.

.Avant de commencer
* Vous êtes connecté au Grid Manager à l'aide d'unlink:../admin/web-browser-requirements.html["navigateur Web pris en charge"] .
* Vous avez lelink:../admin/admin-group-permissions.html["Autorisation d'accès de maintenance ou root"] .
* Vous disposez de la phrase secrète de provisionnement.
* Vous disposez des adresses réseau, en notation CIDR, des sous-réseaux que vous souhaitez configurer.


.À propos de cette tâche
Si l'un des nouveaux nœuds possède une adresse IP de réseau de grille sur un sous-réseau non utilisé auparavant, vous devez ajouter le nouveau sous-réseau à la liste des sous-réseaux du réseau de grille avant de démarrer l'extension.  Sinon, vous devrez annuler l’extension, ajouter le nouveau sous-réseau et recommencer la procédure.

[NOTE]
====
N'utilisez pas de sous-réseaux contenant les adresses IPv4 suivantes pour le réseau de grille, le réseau d'administration ou le réseau client d'un nœud :

* 192 168 130 101
* 192 168 131 101
* 192 168 130 102
* 192 168 131 102
* 198.51.100.2
* 198.51.100.4


Par exemple, n'utilisez pas les plages de sous-réseaux suivantes pour le réseau de grille, le réseau d'administration ou le réseau client d'un nœud :

* 192.168.130.0/24 car cette plage de sous-réseaux contient les adresses IP 192.168.130.101 et 192.168.130.102
* 192.168.131.0/24 car cette plage de sous-réseaux contient les adresses IP 192.168.131.101 et 192.168.131.102
* 198.51.100.0/24 car cette plage de sous-réseaux contient les adresses IP 198.51.100.2 et 198.51.100.4


====
.Étapes
. Sélectionnez *MAINTENANCE* > *Réseau* > *Réseau de grille*.
. Sélectionnez *Ajouter un autre sous-réseau* pour ajouter un nouveau sous-réseau en notation CIDR.
+
Par exemple, entrez `10.96.104.0/22` .

. Saisissez la phrase secrète de provisionnement et sélectionnez *Enregistrer*.
. Attendez que les modifications soient appliquées, puis téléchargez un nouveau package de récupération.
+
.. Sélectionnez *MAINTENANCE* > *Système* > *Package de récupération*.
.. Saisissez la *phrase secrète de provisionnement*.
+

CAUTION: Le fichier du package de récupération doit être sécurisé car il contient des clés de chiffrement et des mots de passe qui peuvent être utilisés pour obtenir des données à partir du système StorageGRID . Il est également utilisé pour récupérer le nœud d’administration principal.





Les sous-réseaux que vous avez spécifiés sont configurés automatiquement pour votre système StorageGRID .
