---
permalink: expand/verifying-storage-node-is-active.html 
sidebar: sidebar 
keywords: expand, expansion, add storage nodes, verify node is active 
summary: 'Une fois l"opération d"extension qui ajoute de nouveaux nœuds de stockage terminée, le système StorageGRID doit automatiquement commencer à utiliser les nouveaux nœuds de stockage.  Vous devez utiliser le système StorageGRID pour vérifier que le nouveau nœud de stockage est actif.' 
---
= Vérifiez que le nœud de stockage est actif
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Une fois l'opération d'extension qui ajoute de nouveaux nœuds de stockage terminée, le système StorageGRID doit automatiquement commencer à utiliser les nouveaux nœuds de stockage.  Vous devez utiliser le système StorageGRID pour vérifier que le nouveau nœud de stockage est actif.

.Étapes
. Sign in au Grid Manager à l'aide d'unlink:../admin/web-browser-requirements.html["navigateur Web pris en charge"] .
. Sélectionnez *NODES* > *_Expansion Storage Node_* > *Storage*.
. Placez votre curseur sur le graphique *Stockage utilisé - Données d'objet* pour afficher la valeur de *Utilisé*, qui correspond à la quantité d'espace total utilisable qui a été utilisée pour les données d'objet.
. Vérifiez que la valeur de *Utilisé* augmente lorsque vous déplacez votre curseur vers la droite sur le graphique.

