---
permalink: troubleshoot/troubleshooting-network-hardware-and-platform-issues.html 
sidebar: sidebar 
keywords: how to troubleshoot network, how to troubleshoot hardware, how to troubleshoot platform 
summary: Il existe plusieurs tâches que vous pouvez effectuer pour vous aider à déterminer la source des problèmes liés au réseau, au matériel et à la plate-forme StorageGRID . 
---
= Résoudre les problèmes de réseau, de matériel et de plate-forme
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il existe plusieurs tâches que vous pouvez effectuer pour vous aider à déterminer la source des problèmes liés au réseau, au matériel et à la plate-forme StorageGRID .



== Erreur « 422 : Entité non traitable »

L'erreur 422 : Entité non traitable peut se produire pour différentes raisons.  Vérifiez le message d’erreur pour déterminer la cause de votre problème.

Si vous voyez l’un des messages d’erreur répertoriés, prenez l’action recommandée.

[cols="2a,3a"]
|===
| Message d'erreur | Cause profonde et action corrective 


 a| 
[listing]
----
422: Unprocessable Entity

Validation failed. Please check
the values you entered for
errors. Test connection failed.
Please verify your
configuration. Unable to
authenticate, please verify
your username and password:
LDAP Result Code 8 "Strong
Auth Required": 00002028:
LdapErr: DSID-0C090256,
comment: The server requires
binds to turn on integrity
checking if SSL\TLS are not
already active on the
connection, data 0, v3839
---- a| 
Ce message peut s’afficher si vous sélectionnez l’option *Ne pas utiliser TLS* pour Transport Layer Security (TLS) lors de la configuration de la fédération d’identité à l’aide de Windows Active Directory (AD).

L'utilisation de l'option *Ne pas utiliser TLS* n'est pas prise en charge pour une utilisation avec des serveurs AD qui appliquent la signature LDAP.  Vous devez sélectionner l'option *Utiliser STARTTLS* ou l'option *Utiliser LDAPS* pour TLS.



 a| 
[listing]
----
422: Unprocessable Entity

Validation failed. Please check
the values you entered for
errors. Test connection failed.
Please verify your
configuration.Unable to
begin TLS, verify your
certificate and TLS
configuration: LDAP Result
Code 200 "Network Error":
TLS handshake failed
    (EOF)
---- a| 
Ce message s'affiche si vous essayez d'utiliser un chiffrement non pris en charge pour établir une connexion TLS (Transport Layer Security) depuis StorageGRID vers un système externe utilisé pour identifier la fédération ou les pools de stockage cloud.

Vérifiez les chiffrements proposés par le système externe.  Le système doit utiliser l’un deslink:../admin/supported-ciphers-for-outgoing-tls-connections.html["chiffrements pris en charge par StorageGRID"] pour les connexions TLS sortantes, comme indiqué dans les instructions d'administration de StorageGRID.

|===


== [[troubleshoot_MTU_alert]]Alerte de non-concordance MTU du réseau de grille

L'alerte *Incompatibilité MTU du réseau de grille* est déclenchée lorsque le paramètre d'unité de transmission maximale (MTU) pour l'interface du réseau de grille (eth0) diffère considérablement entre les nœuds de la grille.

.À propos de cette tâche
Les différences dans les paramètres MTU peuvent indiquer que certains réseaux eth0, mais pas tous, sont configurés pour les trames jumbo.  Une non-concordance de taille MTU supérieure à 1 000 peut entraîner des problèmes de performances réseau.

.Étapes
. Répertoriez les paramètres MTU pour eth0 sur tous les nœuds.
+
** Utilisez la requête fournie dans le gestionnaire de grille.
** Accéder à `_primary Admin Node IP address_/metrics/graph` et entrez la requête suivante : `node_network_mtu_bytes{device="eth0"}`


. https://docs.netapp.com/us-en/storagegrid-appliances/commonhardware/changing-mtu-setting.html["Modifier les paramètres MTU"^]si nécessaire pour garantir qu'ils sont les mêmes pour l'interface du réseau Grid (eth0) sur tous les nœuds.
+
** Pour les nœuds basés sur Linux et VMware, utilisez la commande suivante : `+/usr/sbin/change-ip.py [-h] [-n node] mtu network [network...]+`
+
*Exemple*: `change-ip.py -n node 1500 grid admin`

+
*Remarque* : Sur les nœuds basés sur Linux, si la valeur MTU souhaitée pour le réseau dans le conteneur dépasse la valeur déjà configurée sur l'interface hôte, vous devez d'abord configurer l'interface hôte pour avoir la valeur MTU souhaitée, puis utiliser le `change-ip.py` script pour changer la valeur MTU du réseau dans le conteneur.

+
Utilisez les arguments suivants pour modifier le MTU sur les nœuds basés sur Linux ou VMware.

+
[cols="1a,2a"]
|===
| Arguments positionnels | Description 


 a| 
`mtu`
 a| 
Le MTU à définir.  Doit être compris entre 1280 et 9216.



 a| 
`network`
 a| 
Les réseaux auxquels appliquer le MTU.  Inclure un ou plusieurs des types de réseaux suivants :

*** grille
*** administrateur
*** client


|===
+
[cols="2a,2a"]
|===
| Arguments optionnels | Description 


 a| 
`-h, – help`
 a| 
Afficher le message d'aide et quitter.



 a| 
`-n node, --node node`
 a| 
Le nœud.  La valeur par défaut est le nœud local.

|===






== Alerte d'erreur de réception de trame de réseau de nœuds

Les alertes *Erreur de réception de trame de réseau de nœuds* peuvent être provoquées par des problèmes de connectivité entre StorageGRID et votre matériel réseau.  Cette alerte disparaît d’elle-même une fois le problème sous-jacent résolu.

.À propos de cette tâche
Les alertes *Erreur de réception de trame de réseau de nœud* peuvent être provoquées par les problèmes suivants avec le matériel réseau qui se connecte à StorageGRID:

* La correction d'erreur directe (FEC) est requise et n'est pas utilisée
* Incompatibilité entre le port du commutateur et le MTU de la carte réseau
* Taux d'erreur de lien élevés
* Dépassement de mémoire tampon en anneau de la carte réseau


.Étapes
. Suivez les étapes de dépannage pour toutes les causes potentielles de cette alerte en fonction de la configuration de votre réseau.
. Effectuez les étapes suivantes en fonction de la cause de l’erreur :
+
[role="tabbed-block"]
====
.Incompatibilité FEC
--

NOTE: Ces étapes s'appliquent uniquement aux alertes *Erreur de trame de réception du réseau de nœuds* causées par une incompatibilité FEC sur les appliances StorageGRID .

.. Vérifiez l’état FEC du port dans le commutateur connecté à votre appliance StorageGRID .
.. Vérifiez l’intégrité physique des câbles reliant l’appareil au commutateur.
.. Si vous souhaitez modifier les paramètres FEC pour tenter de résoudre l'alerte, assurez-vous d'abord que l'appliance est configurée pour le mode *Auto* sur la page Configuration de liaison du programme d'installation de l'appliance StorageGRID (consultez les instructions de votre appliance :
+
*** https://docs.netapp.com/us-en/storagegrid-appliances/sg6100/changing-link-configuration-of-sgf6112-appliance.html["SG6160"^]
*** https://docs.netapp.com/us-en/storagegrid-appliances/sg6100/changing-link-configuration-of-sgf6112-appliance.html["SGF6112"^]
*** https://docs.netapp.com/us-en/storagegrid-appliances/sg6000/changing-link-configuration-of-sg6000-cn-controller.html["SG6000"^]
*** https://docs.netapp.com/us-en/storagegrid-appliances/sg5800/changing-link-configuration-of-sg5800-controller.html["SG5800"^]
*** https://docs.netapp.com/us-en/storagegrid-appliances/sg5700/changing-link-configuration-of-e5700sg-controller.html["SG5700"^]
*** https://docs.netapp.com/us-en/storagegrid-appliances/sg110-1100/changing-link-configuration-of-sg110-and-sg1100-appliance.html["SG110 et SG1100"^]
*** https://docs.netapp.com/us-en/storagegrid-appliances/sg100-1000/changing-link-configuration-of-services-appliance.html["SG100 et SG1000"^]


.. Modifiez les paramètres FEC sur les ports du commutateur.  Les ports de l'appliance StorageGRID ajusteront leurs paramètres FEC pour correspondre, si possible.
+
Vous ne pouvez pas configurer les paramètres FEC sur les appliances StorageGRID .  Au lieu de cela, les appareils tentent de découvrir et de refléter les paramètres FEC sur les ports de commutateur auxquels ils sont connectés.  Si les liaisons sont forcées à des vitesses de réseau de 25 GbE ou 100 GbE, le commutateur et la carte réseau risquent de ne pas parvenir à négocier un paramètre FEC commun.  Sans paramètre FEC commun, le réseau reviendra au mode « sans FEC ».  Lorsque FEC n'est pas activé, les connexions sont plus sensibles aux erreurs causées par le bruit électrique.

+

NOTE: Les appliances StorageGRID prennent en charge Firecode (FC) et Reed Solomon (RS) FEC, ainsi que l'absence de FEC.



--
.Incompatibilité entre le port du commutateur et le MTU de la carte réseau
--
Si l'alerte est provoquée par une incompatibilité entre le port de commutateur et le MTU de la carte réseau, vérifiez que la taille du MTU configurée sur le nœud est la même que le paramètre MTU du port de commutateur.

La taille MTU configurée sur le nœud peut être inférieure au paramètre sur le port de commutateur auquel le nœud est connecté.  Si un nœud StorageGRID reçoit une trame Ethernet supérieure à son MTU, ce qui est possible avec cette configuration, l'alerte *Erreur de trame de réception du réseau du nœud* peut être signalée.  Si vous pensez que c'est ce qui se passe, modifiez le MTU du port du commutateur pour qu'il corresponde au MTU de l'interface réseau StorageGRID ou modifiez le MTU de l'interface réseau StorageGRID pour qu'il corresponde au port du commutateur, en fonction de vos objectifs ou exigences en matière de MTU de bout en bout.


NOTE: Pour des performances réseau optimales, tous les nœuds doivent être configurés avec des valeurs MTU similaires sur leurs interfaces Grid Network.  L'alerte *Incompatibilité MTU du réseau de grille* est déclenchée s'il existe une différence significative dans les paramètres MTU du réseau de grille sur des nœuds individuels.  Les valeurs MTU ne doivent pas nécessairement être les mêmes pour tous les types de réseaux. Voir <<troubleshoot_MTU_alert,Dépannage de l'alerte de non-concordance MTU du réseau de grille>> pour plus d'informations.


NOTE: Voir aussi https://docs.netapp.com/us-en/storagegrid-appliances/commonhardware/changing-mtu-setting.html["Modifier le paramètre MTU"^] .

--
.Taux d'erreur de lien élevés
--
.. Activez FEC, si ce n’est pas déjà fait.
.. Vérifiez que votre câblage réseau est de bonne qualité et qu’il n’est pas endommagé ou mal connecté.
.. Si les câbles ne semblent pas être le problème, contactez le support technique.
+

NOTE: Vous remarquerez peut-être des taux d’erreur élevés dans un environnement avec un bruit électrique élevé.



--
.Dépassement de mémoire tampon en anneau de la carte réseau
--
Si l’erreur est un dépassement de mémoire tampon en anneau de la carte réseau, contactez le support technique.

La mémoire tampon en anneau peut être saturée lorsque le système StorageGRID est surchargé et incapable de traiter les événements réseau en temps opportun.

--
====
. Surveillez le problème et contactez le support technique si l’alerte ne se résout pas.




== Erreurs de synchronisation horaire

Vous pourriez rencontrer des problèmes de synchronisation horaire dans votre grille.

Si vous rencontrez des problèmes de synchronisation horaire, vérifiez que vous avez spécifié au moins quatre sources NTP externes, chacune fournissant une référence Stratum 3 ou supérieure, et que toutes les sources NTP externes fonctionnent normalement et sont accessibles par vos nœuds StorageGRID .


NOTE: Quandlink:../maintain/configuring-ntp-servers.html["spécification de la source NTP externe"] pour une installation StorageGRID de niveau production, n'utilisez pas le service Windows Time (W32Time) sur une version de Windows antérieure à Windows Server 2016.  Le service de temps des versions antérieures de Windows n’est pas suffisamment précis et n’est pas pris en charge par Microsoft pour une utilisation dans des environnements de haute précision, tels que StorageGRID.



== Linux : problèmes de connectivité réseau

Vous pourriez rencontrer des problèmes de connectivité réseau pour les nœuds StorageGRID hébergés sur des hôtes Linux.



=== Clonage d'adresse MAC

Dans certains cas, les problèmes de réseau peuvent être résolus en utilisant le clonage d'adresse MAC. Si vous utilisez des hôtes virtuels, définissez la valeur de la clé de clonage d'adresse MAC pour chacun de vos réseaux sur « true » dans votre fichier de configuration de nœud. Ce paramètre oblige l'adresse MAC du conteneur StorageGRID à utiliser l'adresse MAC de l'hôte. Pour créer des fichiers de configuration de nœud, consultez les instructions pourlink:../rhel/creating-node-configuration-files.html["Red Hat Enterprise Linux"] oulink:../ubuntu/creating-node-configuration-files.html["Ubuntu ou Debian"] .


NOTE: Créez des interfaces réseau virtuelles distinctes à utiliser par le système d’exploitation hôte Linux.  L'utilisation des mêmes interfaces réseau pour le système d'exploitation hôte Linux et le conteneur StorageGRID peut rendre le système d'exploitation hôte inaccessible si le mode promiscuité n'a pas été activé sur l'hyperviseur.

Pour plus d'informations sur l'activation du clonage MAC, consultez les instructions delink:../rhel/configuring-host-network.html["Red Hat Enterprise Linux"] oulink:../ubuntu/configuring-host-network.html["Ubuntu ou Debian"] .



=== Mode promiscuité

Si vous ne souhaitez pas utiliser le clonage d'adresse MAC et préférez autoriser toutes les interfaces à recevoir et à transmettre des données pour des adresses MAC autres que celles attribuées par l'hyperviseur, assurez-vous que les propriétés de sécurité au niveau du commutateur virtuel et du groupe de ports sont définies sur *Accepter* pour le mode promiscuité, les modifications d'adresse MAC et les transmissions falsifiées.  Les valeurs définies sur le commutateur virtuel peuvent être remplacées par les valeurs au niveau du groupe de ports. Assurez-vous donc que les paramètres sont les mêmes aux deux endroits.

Pour plus d'informations sur l'utilisation du mode Promiscuous, consultez les instructions delink:../rhel/configuring-host-network.html["Red Hat Enterprise Linux"] oulink:../ubuntu/configuring-host-network.html["Ubuntu ou Debian"] .



== Linux : l'état du nœud est « orphelin »

Un nœud Linux dans un état orphelin indique généralement que le service StorageGrid ou le démon du nœud StorageGRID contrôlant le conteneur du nœud est mort de manière inattendue.

.À propos de cette tâche
Si un nœud Linux signale qu’il est dans un état orphelin, vous devez :

* Vérifiez les journaux pour les erreurs et les messages.
* Essayez de redémarrer le nœud.
* Si nécessaire, utilisez les commandes du moteur de conteneur pour arrêter le conteneur de nœud existant.
* Redémarrez le nœud.


.Étapes
. Vérifiez les journaux du démon de service et du nœud orphelin pour détecter d'éventuelles erreurs évidentes ou des messages concernant une sortie inattendue.
. Connectez-vous à l'hôte en tant que root ou en utilisant un compte avec l'autorisation sudo.
. Essayez de redémarrer le nœud en exécutant la commande suivante : `$ sudo storagegrid node start node-name`
+
 $ sudo storagegrid node start DC1-S1-172-16-1-172
+
Si le nœud est orphelin, la réponse est

+
[listing]
----
Not starting ORPHANED node DC1-S1-172-16-1-172
----
. Depuis Linux, arrêtez le moteur de conteneur et tous les processus de contrôle du nœud de grille de stockage. Par exemple : ``sudo docker stop --time secondscontainer-name``
+
Pour `seconds` , entrez le nombre de secondes pendant lesquelles vous souhaitez attendre que le conteneur s'arrête (généralement 15 minutes ou moins). Par exemple:

+
[listing]
----
sudo docker stop --time 900 storagegrid-DC1-S1-172-16-1-172
----
. Redémarrer le nœud : `storagegrid node start node-name`
+
[listing]
----
storagegrid node start DC1-S1-172-16-1-172
----




== Linux : Dépannage de la prise en charge d'IPv6

Vous devrez peut-être activer la prise en charge IPv6 dans le noyau si vous avez installé des nœuds StorageGRID sur des hôtes Linux et que vous remarquez que les adresses IPv6 n'ont pas été attribuées aux conteneurs de nœuds comme prévu.

.À propos de cette tâche
Pour voir l’adresse IPv6 qui a été attribuée à un nœud de grille :

. Sélectionnez *NODES* et sélectionnez le nœud.
. Sélectionnez *Afficher les adresses IP supplémentaires* à côté de *Adresses IP* dans l'onglet Présentation.


Si l'adresse IPv6 n'est pas affichée et que le nœud est installé sur un hôte Linux, suivez ces étapes pour activer la prise en charge IPv6 dans le noyau.

.Étapes
. Connectez-vous à l'hôte en tant que root ou en utilisant un compte avec l'autorisation sudo.
. Exécutez la commande suivante : `sysctl net.ipv6.conf.all.disable_ipv6`
+
[listing]
----
root@SG:~ # sysctl net.ipv6.conf.all.disable_ipv6
----
+
Le résultat devrait être 0.

+
[listing]
----
net.ipv6.conf.all.disable_ipv6 = 0
----
+

NOTE: Si le résultat n'est pas 0, consultez la documentation de votre système d'exploitation pour modifier `sysctl` paramètres.  Ensuite, changez la valeur à 0 avant de continuer.

. Entrez le conteneur de nœud StorageGRID : `storagegrid node enter node-name`
. Exécutez la commande suivante : `sysctl net.ipv6.conf.all.disable_ipv6`
+
[listing]
----
root@DC1-S1:~ # sysctl net.ipv6.conf.all.disable_ipv6
----
+
Le résultat devrait être 1.

+
[listing]
----
net.ipv6.conf.all.disable_ipv6 = 1
----
+

NOTE: Si le résultat n’est pas 1, cette procédure ne s’applique pas. Contactez le support technique.

. Sortir du conteneur : `exit`
+
[listing]
----
root@DC1-S1:~ # exit
----
. En tant que root, éditez le fichier suivant : `/var/lib/storagegrid/settings/sysctl.d/net.conf` .
+
[listing]
----
sudo vi /var/lib/storagegrid/settings/sysctl.d/net.conf
----
. Localisez les deux lignes suivantes et supprimez les balises de commentaire.  Ensuite, enregistrez et fermez le fichier.
+
[listing]
----
net.ipv6.conf.all.disable_ipv6 = 0
----
+
[listing]
----
net.ipv6.conf.default.disable_ipv6 = 0
----
. Exécutez ces commandes pour redémarrer le conteneur StorageGRID :
+
[listing]
----
storagegrid node stop node-name
----
+
[listing]
----
storagegrid node start node-name
----

