---
permalink: troubleshoot/troubleshooting-admin-node-and-user-interface-issues.html 
sidebar: sidebar 
keywords: how to troubleshoot admin node issues, how to troubleshoot user interface issues 
summary: Vous pouvez effectuer plusieurs tâches pour aider à déterminer la source des problèmes liés aux nœuds d’administration et à l’interface utilisateur de StorageGRID . 
---
= Résoudre les problèmes liés au nœud d'administration et à l'interface utilisateur
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez effectuer plusieurs tâches pour aider à déterminer la source des problèmes liés aux nœuds d’administration et à l’interface utilisateur de StorageGRID .



== Erreurs de connexion au nœud d'administration

Si vous rencontrez une erreur lorsque vous vous connectez à un nœud d'administration StorageGRID , votre système peut avoir un problème avec unlink:../troubleshoot/troubleshooting-network-hardware-and-platform-issues.html["réseautage"] ou https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/troubleshooting-hardware-installation-sg100-and-sg1000.html["matériel"^] problème, un problème aveclink:../primer/what-admin-node-is.html["Services du nœud d'administration"] , ou unlink:../maintain/recovering-failed-storage-volumes-and-rebuilding-cassandra-database.html["problème avec la base de données Cassandra"] sur les nœuds de stockage connectés.

.Avant de commencer
* Vous êtes connecté au Grid Manager à l'aide d'unlink:../admin/web-browser-requirements.html["navigateur Web pris en charge"] .
* Vous avez le `Passwords.txt` déposer.
* Tu aslink:../admin/admin-group-permissions.html["autorisations d'accès spécifiques"] .


.À propos de cette tâche
Utilisez ces instructions de dépannage si vous voyez l’un des messages d’erreur suivants lorsque vous tentez de vous connecter à un nœud d’administration :

* `Your credentials for this account were invalid. Please try again.`
* `Waiting for services to start...`
* `Internal server error. The server encountered an error and could not complete your request. Please try again. If the problem persists, contact Technical Support.`
* `Unable to communicate with server. Reloading page...`


.Étapes
. Attendez 10 minutes et essayez de vous connecter à nouveau.
+
Si l’erreur n’est pas résolue automatiquement, passez à l’étape suivante.

. Si votre système StorageGRID possède plusieurs nœuds d'administration, essayez de vous connecter au gestionnaire de grille à partir d'un autre nœud d'administration pour vérifier l'état d'un nœud d'administration indisponible.
+
** Si vous parvenez à vous connecter, vous pouvez utiliser les options *Tableau de bord*, *NODES*, *Alerts* et *SUPPORT* pour vous aider à déterminer la cause de l'erreur.
** Si vous n’avez qu’un seul nœud d’administration ou si vous ne parvenez toujours pas à vous connecter, passez à l’étape suivante.


. Déterminez si le matériel du nœud est hors ligne.
. Si l'authentification unique (SSO) est activée pour votre système StorageGRID , reportez-vous aux étapes pourlink:../admin/configuring-sso.html["configuration de l'authentification unique"] .
+
Vous devrez peut-être désactiver et réactiver temporairement SSO pour un seul nœud d'administration afin de résoudre les problèmes.

+

NOTE: Si SSO est activé, vous ne pouvez pas vous connecter à l'aide d'un port restreint.  Vous devez utiliser le port 443.

. Déterminez si le compte que vous utilisez appartient à un utilisateur fédéré.
+
Si le compte utilisateur fédéré ne fonctionne pas, essayez de vous connecter au gestionnaire de grille en tant qu'utilisateur local, tel que root.

+
** Si l'utilisateur local peut se connecter :
+
... Consultez les alertes.
... Sélectionnez *CONFIGURATION* > *Contrôle d'accès* > *Fédération d'identité*.
... Cliquez sur *Tester la connexion* pour valider vos paramètres de connexion au serveur LDAP.
... Si le test échoue, résolvez toutes les erreurs de configuration.


** Si l’utilisateur local ne peut pas se connecter et que vous êtes sûr que les informations d’identification sont correctes, passez à l’étape suivante.


. Utilisez Secure Shell (ssh) pour vous connecter au nœud d'administration :
+
.. Entrez la commande suivante : `ssh admin@Admin_Node_IP`
.. Entrez le mot de passe indiqué dans le `Passwords.txt` déposer.
.. Entrez la commande suivante pour passer en root : `su -`
.. Entrez le mot de passe indiqué dans le `Passwords.txt` déposer.
+
Lorsque vous êtes connecté en tant que root, l'invite passe de `$` à `#` .



. Afficher l’état de tous les services exécutés sur le nœud de grille : `storagegrid-status`
+
Assurez-vous que les services nms, mi, nginx et mgmt api sont tous en cours d'exécution.

+
La sortie est mise à jour immédiatement si l’état d’un service change.

+
....
$ storagegrid-status
Host Name                      99-211
IP Address                     10.96.99.211
Operating System Kernel        4.19.0         Verified
Operating System Environment   Debian 10.1    Verified
StorageGRID Webscale Release   11.4.0         Verified
Networking                                    Verified
Storage Subsystem                             Verified
Database Engine                5.5.9999+default Running
Network Monitoring             11.4.0         Running
Time Synchronization           1:4.2.8p10+dfsg Running
ams                            11.4.0         Running
cmn                            11.4.0         Running
nms                            11.4.0         Running
ssm                            11.4.0         Running
mi                             11.4.0         Running
dynip                          11.4.0         Running
nginx                          1.10.3         Running
tomcat                         9.0.27         Running
grafana                        6.4.3          Running
mgmt api                       11.4.0         Running
prometheus                     11.4.0         Running
persistence                    11.4.0         Running
ade exporter                   11.4.0         Running
alertmanager                   11.4.0         Running
attrDownPurge                  11.4.0         Running
attrDownSamp1                  11.4.0         Running
attrDownSamp2                  11.4.0         Running
node exporter                  0.17.0+ds      Running
sg snmp agent                  11.4.0         Running
....
. Confirmez que le service nginx-gw est en cours d'exécution `# service nginx-gw status`
. [[use_Lumberjack_to_collect_logs]]Utilisez Lumberjack pour collecter des journaux : `# /usr/local/sbin/lumberjack.rb`
+
Si l'échec d'authentification s'est produit dans le passé, vous pouvez utiliser les options de script Lumberjack --start et --end pour spécifier la plage horaire appropriée.  Utilisez lumberjack -h pour plus de détails sur ces options.

+
La sortie vers le terminal indique où l'archive du journal a été copiée.

. [[review_logs, start=10]]Consultez les journaux suivants :
+
** `/var/local/log/bycast.log`
** `/var/local/log/bycast-err.log`
** `/var/local/log/nms.log`
** `**/*commands.txt`


. Si vous ne parvenez pas à identifier de problèmes avec le nœud d’administration, exécutez l’une des commandes suivantes pour déterminer les adresses IP des trois nœuds de stockage qui exécutent le service ADC sur votre site.  En règle générale, il s’agit des trois premiers nœuds de stockage installés sur le site.
+
[listing]
----
# cat /etc/hosts
----
+
[listing]
----
# gpt-list-services adc
----
+
Les nœuds d’administration utilisent le service ADC pendant le processus d’authentification.

. Depuis le nœud d’administration, utilisez ssh pour vous connecter à chacun des nœuds de stockage ADC, en utilisant les adresses IP que vous avez identifiées.
. Afficher l’état de tous les services exécutés sur le nœud de grille : `storagegrid-status`
+
Assurez-vous que les services idnt, acct, nginx et cassandra sont tous en cours d'exécution.

. Répéter les étapes<<use_Lumberjack_to_collect_logs,Utilisez le bûcheron pour collecter des bûches>> et<<review_logs,Réviser les journaux>> pour consulter les journaux sur les nœuds de stockage.
. Si vous ne parvenez pas à résoudre le problème, contactez le support technique.
+
Fournissez les journaux que vous avez collectés au support technique. Voir aussi link:../monitor/logs-files-reference.html["Référence des fichiers journaux"] .





== Problèmes d'interface utilisateur

L'interface utilisateur du Grid Manager ou du Tenant Manager peut ne pas répondre comme prévu après la mise à niveau du logiciel StorageGRID .

.Étapes
. Assurez-vous que vous utilisez unlink:../admin/web-browser-requirements.html["navigateur Web pris en charge"] .
. Videz le cache de votre navigateur Web.
+
La suppression du cache supprime les ressources obsolètes utilisées par la version précédente du logiciel StorageGRID et permet à l'interface utilisateur de fonctionner à nouveau correctement.  Pour obtenir des instructions, consultez la documentation de votre navigateur Web.


