---
permalink: ilm/comparing-cloud-storage-pools-to-cloudmirror-replication.html 
sidebar: sidebar 
keywords: cloud storage pools, cloudmirror replication 
summary: Lorsque vous commencez à utiliser les pools de stockage Cloud, il peut être utile de comprendre les similitudes et les différences entre les pools de stockage Cloud et le service de réplication StorageGRID CloudMirror. 
---
= Comparer les pools de stockage cloud et la réplication CloudMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque vous commencez à utiliser les pools de stockage Cloud, il peut être utile de comprendre les similitudes et les différences entre les pools de stockage Cloud et le service de réplication StorageGRID CloudMirror.

[cols="1a,3a,3a"]
|===
|  | Pool de stockage cloud | Service de réplication CloudMirror 


 a| 
Quel est le but principal ?
 a| 
Agit comme une cible d'archivage.  La copie de l'objet dans le pool de stockage Cloud peut être la seule copie de l'objet ou une copie supplémentaire.  Autrement dit, au lieu de conserver deux copies sur site, vous pouvez conserver une copie dans StorageGRID et envoyer une copie au pool de stockage cloud.
 a| 
Permet à un locataire de répliquer automatiquement des objets d'un bucket dans StorageGRID (source) vers un bucket S3 externe (destination).  Crée une copie indépendante d'un objet dans une infrastructure S3 indépendante.



 a| 
Comment est-il configuré ?
 a| 
Défini de la même manière que les pools de stockage, à l'aide du Grid Manager ou de l'API Grid Management.  Peut être sélectionné comme emplacement de placement dans une règle ILM.  Alors qu’un pool de stockage se compose d’un groupe de nœuds de stockage, un pool de stockage cloud est défini à l’aide d’un point de terminaison S3 ou Azure distant (adresse IP, informations d’identification, etc.).
 a| 
Un utilisateur locatairelink:../tenant/configuring-cloudmirror-replication.html["configure la réplication CloudMirror"] en définissant un point de terminaison CloudMirror (adresse IP, informations d'identification, etc.) à l'aide du Tenant Manager ou de l'API S3.  Une fois le point de terminaison CloudMirror configuré, tout bucket appartenant à ce compte locataire peut être configuré pour pointer vers le point de terminaison CloudMirror.



 a| 
Qui est responsable de sa mise en place ?
 a| 
En règle générale, un administrateur de réseau
 a| 
En règle générale, un utilisateur locataire



 a| 
Quelle est la destination ?
 a| 
* Toute infrastructure S3 compatible (y compris Amazon S3)
* Niveau d'archive d'objets blob Azure
* Plateforme Google Cloud (GCP)

 a| 
* Toute infrastructure S3 compatible (y compris Amazon S3)
* Plateforme Google Cloud (GCP)




 a| 
Qu'est-ce qui provoque le déplacement des objets vers la destination ?
 a| 
Une ou plusieurs règles ILM dans les politiques ILM actives.  Les règles ILM définissent les objets que StorageGRID déplace vers le pool de stockage cloud et quand les objets sont déplacés.
 a| 
L’acte d’ingérer un nouvel objet dans un bucket source qui a été configuré avec un point de terminaison CloudMirror.  Les objets qui existaient dans le bucket source avant que le bucket ne soit configuré avec le point de terminaison CloudMirror ne sont pas répliqués, sauf s'ils sont modifiés.



 a| 
Comment les objets sont-ils récupérés ?
 a| 
Les applications doivent effectuer des demandes auprès de StorageGRID pour récupérer les objets qui ont été déplacés vers un pool de stockage cloud.  Si la seule copie d'un objet a été transférée vers un stockage d'archivage, StorageGRID gère le processus de restauration de l'objet afin qu'il puisse être récupéré.
 a| 
Étant donné que la copie en miroir dans le compartiment de destination est une copie indépendante, les applications peuvent récupérer l'objet en effectuant des demandes soit à StorageGRID , soit à la destination S3.  Par exemple, supposons que vous utilisiez la réplication CloudMirror pour mettre en miroir des objets vers une organisation partenaire.  Le partenaire peut utiliser ses propres applications pour lire ou mettre à jour des objets directement depuis la destination S3.  L'utilisation de StorageGRID n'est pas requise.



 a| 
Pouvez-vous lire directement depuis la destination ?
 a| 
Non. Les objets déplacés vers un pool de stockage cloud sont gérés par StorageGRID.  Les demandes de lecture doivent être dirigées vers StorageGRID (et StorageGRID sera responsable de la récupération à partir du Cloud Storage Pool).
 a| 
Oui, car la copie miroir est une copie indépendante.



 a| 
Que se passe-t-il si un objet est supprimé de la source ?
 a| 
L'objet est également supprimé du pool de stockage cloud.
 a| 
L'action de suppression n'est pas répliquée.  Un objet supprimé n’existe plus dans le bucket StorageGRID , mais il continue d’exister dans le bucket de destination.  De même, les objets du bucket de destination peuvent être supprimés sans affecter la source.



 a| 
Comment accéder aux objets après un sinistre (système StorageGRID non opérationnel) ?
 a| 
Les nœuds StorageGRID défaillants doivent être récupérés.  Au cours de ce processus, des copies d’objets répliqués peuvent être restaurées à l’aide des copies du pool de stockage cloud.
 a| 
Les copies d'objet dans la destination CloudMirror sont indépendantes de StorageGRID, elles sont donc accessibles directement avant la récupération des nœuds StorageGRID .

|===