---
permalink: ilm/how-object-retention-is-determined.html 
sidebar: sidebar 
keywords: how object retention is determined 
summary: 'StorageGRID fournit des options permettant aux administrateurs de grille et aux utilisateurs locataires individuels de spécifier la durée de stockage des objets.  En général, toutes les instructions de conservation fournies par un utilisateur locataire ont priorité sur les instructions de conservation fournies par l"administrateur de la grille.' 
---
= Comment la rétention d'objet est déterminée
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID fournit des options permettant aux administrateurs de grille et aux utilisateurs locataires individuels de spécifier la durée de stockage des objets.  En général, toutes les instructions de conservation fournies par un utilisateur locataire ont priorité sur les instructions de conservation fournies par l'administrateur de la grille.



== Comment les utilisateurs locataires contrôlent la rétention des objets

Les utilisateurs locataires peuvent utiliser ces méthodes pour contrôler la durée de stockage de leurs objets dans StorageGRID:

* Si le paramètre global de verrouillage d'objet S3 est activé pour la grille, les utilisateurs du locataire S3 peuvent créer des compartiments avec le verrouillage d'objet S3 activé, puis sélectionner une *Période de conservation par défaut* pour chaque compartiment.
* Si le paramètre global de verrouillage d'objet S3 est activé pour la grille, les utilisateurs du locataire S3 peuvent créer des compartiments avec le verrouillage d'objet S3 activé, puis utiliser l'API REST S3 pour spécifier les paramètres de conservation jusqu'à la date et de conservation légale pour chaque version d'objet ajoutée à ce compartiment.
+
** Une version d'objet soumise à une suspension légale ne peut être supprimée par aucune méthode.
** Avant que la date de conservation d'une version d'objet ne soit atteinte, cette version ne peut être supprimée par aucune méthode.
** Les objets dans les buckets avec le verrouillage d'objet S3 activé sont conservés par ILM « pour toujours ».  Cependant, une fois sa date de conservation atteinte, une version d'objet peut être supprimée par une demande client ou par l'expiration du cycle de vie du bucket. Voir link:managing-objects-with-s3-object-lock.html["Gérer les objets avec S3 Object Lock"] .


* Les utilisateurs locataires S3 peuvent ajouter une configuration de cycle de vie à leurs compartiments qui spécifie une action d’expiration.  Si un cycle de vie de compartiment existe, StorageGRID stocke un objet jusqu'à ce que la date ou le nombre de jours spécifiés dans l'action Expiration soient atteints, sauf si le client supprime d'abord l'objet. Voir link:../s3/create-s3-lifecycle-configuration.html["Créer une configuration du cycle de vie S3"] .
* Un client S3 peut émettre une demande de suppression d’objet.  StorageGRID donne toujours la priorité aux demandes de suppression des clients par rapport au cycle de vie du compartiment S3 ou à ILM pour déterminer s'il faut supprimer ou conserver un objet.




== Comment les administrateurs de réseau contrôlent la conservation des objets

Les administrateurs de grille peuvent utiliser ces méthodes pour contrôler la conservation des objets :

* Définissez une période de conservation maximale du verrouillage d’objet S3 pour chaque locataire.  Ensuite, les utilisateurs locataires peuvent définir une période de conservation par défaut pour chacun de leurs compartiments.  La période de conservation maximale est également appliquée à tous les objets nouvellement ingérés pour ce bucket (date de conservation de l'objet).
* Créez des instructions de placement ILM pour contrôler la durée de stockage des objets.  Lorsque des objets correspondent à une règle ILM, StorageGRID stocke ces objets jusqu'à ce que la dernière période de la règle ILM soit écoulée.  Les objets sont conservés indéfiniment si « pour toujours » est spécifié pour les instructions de placement.
* Quelle que soit la personne qui contrôle la durée de conservation des objets, les paramètres ILM contrôlent les types de copies d'objets (répliquées ou codées par effacement) qui sont stockées et où se trouvent les copies (nœuds de stockage ou pools de stockage cloud).




== Comment le cycle de vie du bucket S3 et l'ILM interagissent

Lorsqu'un cycle de vie de compartiment S3 est configuré, les actions d'expiration du cycle de vie remplacent la stratégie ILM pour les objets qui correspondent au filtre de cycle de vie.  Par conséquent, un objet peut être conservé sur la grille même après l'expiration des instructions ILM de placement de l'objet.



== Exemples de rétention d'objets

Pour mieux comprendre les interactions entre S3 Object Lock, les paramètres du cycle de vie du bucket, les demandes de suppression du client et ILM, considérez les exemples suivants.



=== Exemple 1 : le cycle de vie du bucket S3 conserve les objets plus longtemps que celui d'ILM

ILM:: Conservez deux copies pendant 1 an (365 jours)
Cycle de vie du bucket:: Expirer les objets dans 2 ans (730 jours)
Résultat:: StorageGRID stocke l'objet pendant 730 jours.  StorageGRID utilise les paramètres du cycle de vie du bucket pour déterminer s'il faut supprimer ou conserver un objet.



NOTE: Si le cycle de vie du bucket spécifie que les objets doivent être conservés plus longtemps que spécifié par ILM, StorageGRID continue d'utiliser les instructions de placement ILM lors de la détermination du nombre et du type de copies à stocker.  Dans cet exemple, deux copies de l’objet continueront d’être stockées dans StorageGRID du jour 366 au jour 730.



=== Exemple 2 : le cycle de vie du compartiment S3 expire les objets avant ILM

ILM:: Conservez deux copies pendant 2 ans (730 jours)
Cycle de vie du bucket:: Expirer les objets dans 1 an (365 jours)
Résultat:: StorageGRID supprime les deux copies de l'objet après le jour 365.




=== Exemple 3 : la suppression du client remplace le cycle de vie du bucket et l'ILM

ILM:: Stocker deux copies sur des nœuds de stockage « pour toujours »
Cycle de vie du bucket:: Expirer les objets dans 2 ans (730 jours)
Demande de suppression du client:: Publié le jour 400
Résultat:: StorageGRID supprime les deux copies de l'objet le jour 400 en réponse à la demande de suppression du client.




=== Exemple 4 : Le verrouillage d'objet S3 remplace la demande de suppression du client

Verrouillage d'objet S3:: La date de conservation pour une version d'objet est le 31/03/2026.  Aucune mesure de conservation légale n'est en vigueur.
Règle ILM conforme:: Stocker deux copies sur des nœuds de stockage « pour toujours »
Demande de suppression du client:: Publié le 31/03/2024
Résultat:: StorageGRID ne supprimera pas la version de l'objet car la date de conservation est encore dans 2 ans.

