---
permalink: ilm/view-cloud-storage-pool-details.html 
sidebar: sidebar 
keywords: view cloud storage pool 
summary: 'Vous pouvez afficher les détails d"un pool de stockage cloud pour déterminer où il est utilisé et voir quels nœuds et niveaux de stockage sont inclus.' 
---
= Afficher les détails du pool de stockage cloud
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez afficher les détails d'un pool de stockage cloud pour déterminer où il est utilisé et voir quels nœuds et niveaux de stockage sont inclus.

.Avant de commencer
* Vous êtes connecté au Grid Manager à l'aide d'unlink:../admin/web-browser-requirements.html["navigateur Web pris en charge"] .
* Tu aslink:../admin/admin-group-permissions.html["autorisations d'accès spécifiques"] .


.Étapes
. Sélectionnez *ILM* > *Pools de stockage* > *Pools de stockage cloud*.
+
Le tableau des pools de stockage cloud inclut les informations suivantes pour chaque pool de stockage cloud qui inclut des nœuds de stockage :

+
** *Nom* : Le nom d’affichage unique du pool.
** *URI* : l'identifiant de ressource uniforme du pool de stockage cloud.
** *Type de fournisseur* : quel fournisseur de cloud est utilisé pour ce pool de stockage cloud.
** *Conteneur* : le nom du bucket utilisé pour le pool de stockage cloud.
** *Utilisation ILM* : Comment la piscine est actuellement utilisée.  Un pool de stockage cloud peut être inutilisé ou utilisé dans une ou plusieurs règles ILM, profils de codage d'effacement ou les deux.
** *Dernière erreur* : la dernière erreur détectée lors d’un contrôle d’état de ce pool de stockage cloud.


. Pour afficher les détails d’un pool de stockage cloud spécifique, sélectionnez son nom.
+
La page de détails de la piscine apparaît.

. Consultez l'onglet *Authentification* pour en savoir plus sur le type d'authentification de ce pool de stockage cloud et pour modifier les détails d'authentification.
. Consultez l'onglet *Vérification du serveur* pour en savoir plus sur les détails de la vérification, modifier la vérification, télécharger un nouveau certificat ou copier le PEM du certificat.
. Consultez l'onglet *Utilisation ILM* pour déterminer si le pool de stockage cloud est actuellement utilisé dans des règles ILM ou des profils de codage d'effacement.
. En option, accédez à la page *Règles ILM* pourlink:working-with-ilm-rules-and-ilm-policies.html["connaître et gérer toutes les règles"] qui utilisent le pool de stockage cloud.

