---
permalink: ilm/viewing-storage-pool-details.html 
sidebar: sidebar 
keywords: storage pool, view details 
summary: 'Vous pouvez afficher les détails d"un pool de stockage pour déterminer où le pool de stockage est utilisé et pour voir quels nœuds et niveaux de stockage sont inclus.' 
---
= Afficher les détails du pool de stockage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez afficher les détails d'un pool de stockage pour déterminer où le pool de stockage est utilisé et pour voir quels nœuds et niveaux de stockage sont inclus.

.Avant de commencer
* Vous êtes connecté au Grid Manager à l'aide d'unlink:../admin/web-browser-requirements.html["navigateur Web pris en charge"] .
* Tu aslink:../admin/admin-group-permissions.html["autorisations d'accès spécifiques"] .


.Étapes
. Sélectionnez *ILM* > *Pools de stockage*.
+
Le tableau des pools de stockage inclut les informations suivantes pour chaque pool de stockage qui inclut des nœuds de stockage :

+
** *Nom* : le nom d’affichage unique du pool de stockage.
** *Nombre de nœuds* : le nombre de nœuds dans le pool de stockage.
** *Utilisation du stockage* : le pourcentage de l'espace utilisable total qui a été utilisé pour les données d'objet sur ce nœud.  Cette valeur n'inclut pas les métadonnées de l'objet.
** *Capacité totale* : la taille du pool de stockage, qui correspond à la quantité totale d'espace utilisable pour les données d'objet pour tous les nœuds du pool de stockage.
** *Utilisation ILM* : Comment le pool de stockage est actuellement utilisé.  Un pool de stockage peut être inutilisé ou utilisé dans une ou plusieurs règles ILM, profils de codage d'effacement ou les deux.


. Pour afficher les détails d’un pool de stockage spécifique, sélectionnez son nom.
+
La page de détails du pool de stockage s’affiche.

. Consultez l’onglet *Nœuds* pour en savoir plus sur les nœuds de stockage inclus dans le pool de stockage.
+
Le tableau comprend les informations suivantes pour chaque nœud :

+
** Nom du nœud
** Nom du site
** Qualité de stockage
** Utilisation du stockage : pourcentage de l’espace total utilisable pour les données d’objet qui a été utilisé pour le nœud de stockage.
+

NOTE: La même valeur d'utilisation du stockage (%) est également affichée dans le graphique Stockage utilisé - Données d'objet pour chaque nœud de stockage (sélectionnez *NODES* > *_Storage Node_* > *Storage*).



. Consultez l'onglet *Utilisation ILM* pour déterminer si le pool de stockage est actuellement utilisé dans des règles ILM ou des profils de codage d'effacement.
. Vous pouvez également accéder à la page *Règles ILM* pour en savoir plus sur les règles qui utilisent le pool de stockage et les gérer.
+
Voir lelink:working-with-ilm-rules-and-ilm-policies.html["instructions pour travailler avec les règles ILM"] .


