---
permalink: fabricpool/creating-traffic-classification-policy-for-fabricpool.html 
sidebar: sidebar 
keywords: fabricPool, traffic classification, traffic policy, QoS, quality of service 
summary: Vous pouvez éventuellement concevoir une stratégie de classification du trafic StorageGRID pour optimiser la qualité de service pour la charge de travail FabricPool . 
---
= Créer une politique de classification du trafic pour FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez éventuellement concevoir une stratégie de classification du trafic StorageGRID pour optimiser la qualité de service pour la charge de travail FabricPool .

Pour plus de détails sur cette tâche, voirlink:../admin/managing-traffic-classification-policies.html["Gérer les politiques de classification du trafic"] .  Pour utiliser l'assistant de configuration FabricPool pour effectuer cette tâche, accédez àlink:use-fabricpool-setup-wizard-steps.html["Accéder et terminer l'assistant de configuration de FabricPool"] .

.Avant de commencer
* Vous êtes connecté au Grid Manager à l'aide d'unlink:../admin/web-browser-requirements.html["navigateur Web pris en charge"] .
* Vous avez lelink:../admin/admin-group-permissions.html["Autorisation d'accès root"] .


.À propos de cette tâche
Les meilleures pratiques pour créer une politique de classification du trafic pour FabricPool dépendent de la charge de travail, comme suit :

* Si vous prévoyez de hiérarchiser les données de charge de travail principales de FabricPool vers StorageGRID, vous devez vous assurer que la charge de travail de FabricPool dispose de la majeure partie de la bande passante.  Vous pouvez créer une politique de classification du trafic pour limiter toutes les autres charges de travail.
+

NOTE: En général, les opérations de lecture de FabricPool sont plus importantes à prioriser que les opérations d’écriture.

+
Par exemple, si d’autres clients S3 utilisent ce système StorageGRID , vous devez créer une stratégie de classification du trafic.  Vous pouvez limiter le trafic réseau pour les autres buckets, locataires, sous-réseaux IP ou points de terminaison d'équilibrage de charge.

* En règle générale, vous ne devez pas imposer de limites de qualité de service à une charge de travail FabricPool ; vous devez uniquement limiter les autres charges de travail.
* Les limites imposées aux autres charges de travail doivent tenir compte du comportement de ces charges de travail.  Les limites imposées varieront également en fonction de la taille et des capacités de votre réseau et de la quantité d’utilisation prévue.


.Étapes
. Sélectionnez *CONFIGURATION* > *Réseau* > *Classification du trafic*.
. Sélectionnez *Créer*.
. Saisissez un nom et une description (facultatif) pour la politique et sélectionnez *Continuer*.
. Pour l’étape Ajouter des règles de correspondance, ajoutez au moins une règle.
+
.. Sélectionnez *Ajouter une règle*
.. Pour Type, sélectionnez *Point de terminaison de l'équilibreur de charge*, puis sélectionnez le point de terminaison de l'équilibreur de charge que vous avez créé pour FabricPool.
+
Vous pouvez également sélectionner le compte locataire ou le bucket FabricPool .

.. Si vous souhaitez que cette politique de trafic limite le trafic pour les autres points de terminaison, sélectionnez *Correspondance inverse*.


. Vous pouvez également ajouter une ou plusieurs limites pour contrôler le trafic réseau correspondant à la règle.
+

NOTE: StorageGRID collecte des métriques même si vous n'ajoutez aucune limite, afin que vous puissiez comprendre les tendances du trafic.

+
.. Sélectionnez *Ajouter une limite*.
.. Sélectionnez le type de trafic que vous souhaitez limiter et la limite à appliquer.


. Sélectionnez *Continuer*.
. Lisez et révisez la politique de classification du trafic.  Utilisez le bouton *Précédent* pour revenir en arrière et apporter les modifications nécessaires.  Lorsque vous êtes satisfait de la politique, sélectionnez *Enregistrer et continuer*.


.Après votre finition
link:../admin/viewing-network-traffic-metrics.html["Afficher les mesures du trafic réseau"]pour vérifier que les policiers appliquent les limites de circulation que vous attendez.
