---
permalink: fabricpool/using-storagegrid-ilm-with-fabricpool-data.html 
sidebar: sidebar 
keywords: FabricPool, requirements, ILM, information lifecycle management, ILM rule, ILM rules, ILM policy, erasure coding, replication, cloud storage pool, glacier 
summary: Vous pouvez utiliser cet exemple simple de politique comme point de départ pour vos propres règles et politiques ILM. 
---
= Configurer ILM pour les données FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser cet exemple simple de politique comme point de départ pour vos propres règles et politiques ILM.

Cet exemple suppose que vous concevez les règles ILM et une politique ILM pour un système StorageGRID doté de quatre nœuds de stockage dans un seul centre de données à Denver, Colorado.  Les données FabricPool dans cet exemple utilisent un bucket nommé `fabricpool-bucket` .


CAUTION: Les règles et politiques ILM suivantes ne sont que des exemples.  Il existe de nombreuses façons de configurer les règles ILM.  Avant d’activer une nouvelle politique, simulez-la pour confirmer qu’elle fonctionnera comme prévu pour protéger le contenu contre la perte.  Pour en savoir plus, voirlink:../ilm/index.html["Gérer les objets avec ILM"] .


CAUTION: Pour éviter toute perte de données, n’utilisez pas de règle ILM qui expirera ou supprimera les données de niveau cloud FabricPool .  Définissez la période de conservation sur *pour toujours* pour garantir que les objets FabricPool ne sont pas supprimés par StorageGRID ILM.

.Avant de commencer
* Vous avez examiné lelink:best-practices-ilm.html["meilleures pratiques pour utiliser ILM avec les données FabricPool"] .
* Vous êtes connecté au Grid Manager à l'aide d'unlink:../admin/web-browser-requirements.html["navigateur Web pris en charge"] .
* Vous avez lelink:../admin/admin-group-permissions.html["Autorisation d'accès ILM ou Root"] .
* Si vous avez effectué une mise à niveau vers StorageGRID 11.9 à partir d'une version précédente de StorageGRID , vous avez configuré le pool de stockage que vous utiliserez. En général, vous devez créer un pool de stockage pour chaque site StorageGRID que vous utiliserez pour stocker des données.
+

NOTE: Cette condition préalable ne s'applique pas si vous avez initialement installé StorageGRID 11.7 ou 11.8.  Lorsque vous installez initialement l’une de ces versions, des pools de stockage sont automatiquement créés pour chaque site.



.Étapes
. Créez une règle ILM qui s'applique uniquement aux données dans `fabricpool-bucket` Cet exemple de règle crée des copies à code d'effacement.
+
[cols="1a,2a"]
|===
| Définition de la règle | Exemple de valeur 


 a| 
Nom de la règle
 a| 
Codage d'effacement 2 + 1 pour les données FabricPool



 a| 
Nom du bucket
 a| 
`fabricpool-bucket`

Vous pouvez également filtrer sur le compte locataire FabricPool .



 a| 
Filtres avancés
 a| 
Taille de l'objet supérieure à 0,2 Mo.

*Remarque :* FabricPool écrit uniquement des objets de 4 Mo, mais vous devez ajouter un filtre de taille d’objet, car cette règle utilise le codage d’effacement.



 a| 
Heure de référence
 a| 
Temps d'ingestion



 a| 
Période et emplacements
 a| 
À partir du jour 0, stockez pour toujours

Stockez les objets par codage d'effacement à l'aide du schéma EC 2+1 à Denver et conservez ces objets dans StorageGRID pour toujours.


CAUTION: Pour éviter toute perte de données, n'utilisez pas de règle ILM qui expirera ou supprimera les données de niveau cloud FabricPool .



 a| 
Comportement d'ingestion
 a| 
Équilibré

|===
. Créez une règle ILM par défaut qui créera deux copies répliquées de tous les objets ne correspondant pas à la première règle.  Ne sélectionnez pas de filtre de base (compte locataire ou nom de bucket) ni de filtres avancés.
+
[cols="1a,2a"]
|===
| Définition de la règle | Exemple de valeur 


 a| 
Nom de la règle
 a| 
Deux copies répliquées



 a| 
Nom du bucket
 a| 
_aucun_



 a| 
Filtres avancés
 a| 
_aucun_



 a| 
Heure de référence
 a| 
Temps d'ingestion



 a| 
Période et emplacements
 a| 
À partir du jour 0, stockez pour toujours

Stockez les objets en répliquant 2 copies à Denver.



 a| 
Comportement d'ingestion
 a| 
Équilibré

|===
. Créez une politique ILM et sélectionnez les deux règles.  Étant donné que la règle de réplication n’utilise aucun filtre, elle peut être la règle par défaut (dernière) de la politique.
. Ingérer les objets de test dans la grille.
. Simulez la politique avec les objets de test pour vérifier le comportement.
. Activer la politique.


Lorsque cette politique est activée, StorageGRID place les données d’objet comme suit :

* Les données hiérarchisées à partir de FabricPool dans `fabricpool-bucket` sera codé par effacement en utilisant le schéma de codage par effacement 2+1.  Deux fragments de données et un fragment de parité seront placés sur trois nœuds de stockage différents.
* Tous les objets de tous les autres buckets seront répliqués.  Deux copies seront créées et placées sur deux nœuds de stockage différents.
* Les copies seront conservées dans StorageGRID pour toujours.  StorageGRID ILM ne supprimera pas ces objets.

